### ISSUE TITLE
Grid sorter

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#1]
This http://jsfiddle.net/dalcib/6kabF/2/

And This: https://groups.google.com/forum/#!topic/angular/vM2DEMK_NMA/discussion

F*cking awesome. We need it.

**Comment by dandoyon** [comment]
the first one looks quite nice, one thing that i don't like is all the embedded html in the javascript code, it would be nicer (if possible) to use the scripttag template for the pager.

**Comment by orneryd** [comment]
We are working on a simple. native, and templatable grid control...you might check it out.

https://github.com/Crash8308/ng-grid

**Comment by ProLoser** [comment]
Any interest in contributing it to AngularUI?

**Comment by orneryd** [comment]
hit us up on gchat today

**Comment by ProLoser** [comment]
https://github.com/timothyswt/angular-ui/tree/ng-grid

**Comment by orneryd** [comment]
I don't think that our grid project really "fits" with this project. Our grid makes a lot of assumptions for you and is more than just a directive for a control. We are on version 1.2.1 and support grouping/server side paging, sorting , filtering and is becoming more of a full featured grid than what I think you would want for this ui-package.

**Comment by orneryd** [comment]
Look like we ended up joining anyways. http://angular-ui.github.com/ng-grid/
