### ISSUE TITLE
maps unit test fails in ie9

### ISSUE THREAD

**Issue by boneskull** [angular-ui/angular-ui-OLDREPO#101]
IE 9.0 ERROR
    No such interface supported

```
at /Volumes/projects/angular-ui/test/lib/googlemaps/googlemaps.js:49
```

**Comment by boneskull** [comment]
also:
`IE 9.0 uiMap test infoWindow should recognize infowindow events in ui-event as "map-eventname" FAILED
    Expected undefined to be true.
`

**Comment by pkozlowski-opensource** [comment]
Also:

IE 9.0 uiMap test infoWindow should recognize infowindow events in ui-event as "map-eventname" FAILED
        ReferenceError: 'console' is undefined

**Comment by dandoyon** [comment]
I just saw this console.log statement in ui-map.

**Comment by pkozlowski-opensource** [comment]
yeh, would be cool if anyone more familiar with this directive could have a look... I would really love to have all the tests running in all browsers....

**Comment by ajoslin** [comment]
I never got the IE VM running on my mac :/  

.. and I don't see any console in the source.

**Comment by pkozlowski-opensource** [comment]
@ajoslin, Andy, it is in the spec source: https://github.com/angular-ui/angular-ui/blob/master/modules/directives/map/test/mapSpec.js#L13

**Comment by ProLoser** [comment]
Browserstack.Com

**Comment by ajoslin** [comment]
Ok, I pushed to mapsDev with that console.log removed.  Could someone test again?

**Comment by pkozlowski-opensource** [comment]
@ajoslin can't see your commits... Did you push somewhere else than https://github.com/angular-ui/angular-ui/commits/mapsDev?

**Comment by ajoslin** [comment]
Looks like I didn't actually push it, whoops.  It's up now.

**Comment by pkozlowski-opensource** [comment]
@ajoslin, looks like mapsDev is a really old branch and was merged with master AFAIK... The thing is that in the mapsDev there are no changes to the test setup done by @ProLoser so I can't really test on win... Could you create a new branch of master, sth like issue101 or mapsFix or whatever?

Anyway, after removing console.log in master I'm getting the same error as reported by @boneskull :

IE 9.0 uiMap test infoWindow should recognize infowindow events in ui-event as "map-eventname" FAILED
       Expected undefined to be true.

**Comment by ajoslin** [comment]
Gah, I can't get browserstack.com to run the tests either lol.  I just remembered I have a windows XP image I can use on virtualbox... I'll try to get everything running there...

**Comment by ProLoser** [comment]
Need to move this to ui-map

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-map

Please reopen this issue there if it is still relevant.
