### ISSUE TITLE
uiCurrency test dies in ie8

### ISSUE THREAD

**Issue by boneskull** [angular-ui/angular-ui-OLDREPO#103]
```

IE 8.0 uiCurrency use on a tag element should have a defined element FAILED
    Error: Unexpected call to method or property access.

```

**Comment by dandoyon** [comment]
All the directives that support "E"lement style will fail in IE8 and need the ieshiv most likely.

**Comment by cj** [comment]
@dandoyon I've included the ieshiv and directives using "E" still do not work.

**Comment by ProLoser** [comment]
Are you including the shiv in the `<head>` and NOT asynchronously?

**Comment by cj** [comment]
Correct, I'm including it in the head:

``` html
<!DOCTYPE html>
<html lang='en' ng-app='subro'>
<head>
<title>*******</title>
<meta charset='utf-8'>
<meta content='' name='description'>
<meta content='' name='author'>
<meta content='IE=edge,chrome=1' http-equiv='X-UA-Compatible'>
<!--[if lte IE 8]>
<script>
  //<![CDATA[
    window.myCustomTags = ["uiInput"];
  //]]>
</script>
<script src="/assets/angular.ui.ieshiv.js?body=1" type="text/javascript"></script>
<![endif]-->
<script src="/assets/jquery.js?body=1" type="text/javascript"></script>
<script src="/assets/jquery_ujs.js?body=1" type="text/javascript"></script>
<script src="/assets/bootbox.js?body=1" type="text/javascript"></script>
<script src="/assets/angular.min.js?body=1" type="text/javascript"></script>
<script src="/assets/angular-resource.js?body=1" type="text/javascript"></script>
<script src="/assets/angular.ui.js?body=1" type="text/javascript"></script>
<script src="/assets/angular-bootstrap.js?body=1" type="text/javascript"></script>
<script src="/assets/angular.js?body=1" type="text/javascript"></script>
```

**Comment by dandoyon** [comment]
To my knowledge ( I will verify this weekend ) nothing has changed with ui-currency in a long time. If tests ran with IE before they should still work. 

I do want to point out that I have encountered an anomalous situation that I haven't had time to look into and that is ui-currency not working at all. I'm suspicious that it has to do with bootstrap.js. 

Hopefully this weekend I can do some hunting around

my 2c

--dan

**Comment by llozano** [comment]
Anything on this?

**Comment by ProLoser** [comment]
@llozano we are removing ui-currency as it is no longer relevant due to enhancements that were added later to `ng-class`

**Comment by llozano** [comment]
@ProLoser I decided to follow up on this because the issue describes some IE8 incompatibility. I opened an issue regarding ui-map IE8 not loading the map. Can you point me to the right direction?

**Comment by ProLoser** [comment]
I have been noticing the requests for help on ui-map in IE8 however I did not build that directive nor do I use it as that's @ajoslin's brain-child. Unfortunately I've also been so swamped with work that I have not had time to take a look at this issue. Sorry.
