### ISSUE TITLE
uiJq test dies in ie8

### ISSUE THREAD

**Issue by boneskull** [angular-ui/angular-ui-OLDREPO#105]
```
IE 8.0 uiJq calling a jQuery element function should just like, sort of work and junk FAILED
    TypeError: Function.prototype.apply: argument is null or undefined
```

**Comment by ProLoser** [comment]
Should probably double check if this still occurs...

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-utils

Please reopen this issue there if it is still relevant.
