### ISSUE TITLE
Make file broken?

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#11]
I'm hoping it's not just me though. I cannot seem to make a new build. I'm going to push a new directive in (I am substituting chosen for select2) but I can't generate a new build.

Pete: do you mind taking a look at it?

**Comment by ProLoser** [comment]
I'm actually further confused as to the complexity of the project. Is having the src and stylesheets folders and everything necessary for testing?

Also, why doesn't the build file simply scan everything recursively inside of modules and just use that? It seems tedious to have this unusual web of directory paths and variables in the make file. You could just search for modules/_/_.js and so on.

**Comment by petebacondarwin** [comment]
Hi Dean
You are much more masterful than I with make. I like your factoring of the
makefile. Much clearer.
The reason behind the folder structure and module naming was to make each
directive its own little project so they could be pulled out and live
independently if wanted.
The proliferation of module names is hidden to the normal user as they
simply include ui.directives as a dependency. But it gets us away from the
bug prone process of reopening modules to add to them.
If modules are never going to be used alone then we could dispense with all
this but personally I would want to pick and choose which directives I
include in my apps.
Pete

...from my mobile.
On Apr 13, 2012 2:12 AM, "Dean Sofer" <
reply@reply.github.com>
wrote:

**Comment by ProLoser** [comment]
Picking and choosing was actually part of the original design, as I
intended to build a package assembler (similar to html5 boilerplate) so
that you could do exactly what you describe: pick and choose just what you
need.

My concern with the original approach is that it's just not how the code
should be designed, but there are other advantages too.

Firstly, with the original approach, you would have to always update the
parent(?) module with every addition, and for that matter, removal of each
piece. This means that simply removing the necessary directive or filter
would not be enough, you would have to manually modify the parent module
file. With this approach, simply removing the directive or filter will not
actually break anything whatsoever. Only the parent modules are 'included'
by 1 main module. There is no call to the child directives, meaning
removing them will throw no errors.

I understand the purpose of making each directive a self-contained project,
however since (I'm assuming) you're already including the AngularJs lib,
you should be able to simply include the module file too and everything
will behave perfectly normally.

Why do you think you're able to add new directives on the fly without
having to tweak the modules? Each directive is binded to the (pre-existing)
directive namespace. Those namespaces can be empty but as long as they are
initially declared (within the common module file) there will not be any
further issues. Just make sure you call the modules first and the rest will
work fine with as few or as many pieces as you want.

On a tangent note, is there a need to have src directories everywhere? It's
not critical or anything though.

On Fri, Apr 13, 2012 at 12:03 AM, Pete Bacon Darwin <
reply@reply.github.com

**Comment by petebacondarwin** [comment]
This appears to be resolved in master.
