### ISSUE TITLE
ngModal should support expression-based rendering

### ISSUE THREAD

**Issue by tdavis** [angular-ui/angular-ui-OLDREPO#112]
Currently, `ngModal` requires `ngModel` to be a model instance as it may also set the value when, e.g., closing a dialog. Unfortunately, this precludes conditional dialogs via `ngModel` expressions, such as "when model `foo == 'bar'`, render my dialog". This use-case exists for me: I want to provide a `select` drop-down that lets the user take different actions; each action requires interaction with a different modal dialog.

`ProLoser` in `#angularjs` helped me work through a partial solution, found here:

http://plunker.no.de/edit/io5ZVk

However, despite the fact that this directive contains `require: '?ngModel'`, it still throws an exception when `ngModel` is not present (though the functionality itself remains intact). He did not have time to debug this further and suggested I open an issue here. Thanks in advance for any help!

**Comment by petebacondarwin** [comment]
Easy enough fix.  You were checking to see if ngModel existed on line 37.
 You actually meant to check to see if model existed.
There are too many models and modals and so on so it is rather confusing.
Here is a working plunk, with model changed to modelController to make it
more clear:  http://plunker.no.de/edit/Kx3paP?live=preview
Pete

On 24 July 2012 21:39, Tom Davis <
reply@reply.github.com

**Comment by tdavis** [comment]
If you click "Run" in the Plunk and open up a JS console, you'll see that there is an error: `Error: No controller: ngModel`.

**Comment by petebacondarwin** [comment]
I think you problem was that you were including the angular-ui source file,
which had a different version of ui-modal.
Here is a version that is completely removed from angular-ui.  No errors.
http://plunker.no.de/edit/ACXiRI
Pete

On 24 July 2012 22:02, Tom Davis <
reply@reply.github.com

**Comment by boneskull** [comment]
It looks to me like the directive really does require ngModel so it should not be marked as optional... am I wrong?

**Comment by petebacondarwin** [comment]
The directive as shown in the last plunk does not require ng-model. In fact
I would say it makes more sense without it.

Pete
...from my mobile.
On Jul 25, 2012 12:35 AM, "Christopher Hiller" <
reply@reply.github.com>
wrote:

**Comment by tdavis** [comment]
Yes, the Plunk version should probably not have `ngModel` at all. I had initially tried to rename the directive, thinking the issue was the naming clash as well. However I'd failed to make the same change in the `$watch` call, leaving the directive broken and me left wondering what positive side-effect the clash was having!

Your Plunk is indeed appropriate; I amended it to remove `ngModel` entirely. Thanks!
