### ISSUE TITLE
Directives & Issues have their own modules

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#12]
Pete: I just noticed this. Why does every single directive and filter need it's own module?

This feels really anti-intuitive to me, and the solution we had before felt way more elegant. Is this just so that tests could work? In which case, I feel like perhaps we should make tests cater to the code, rather than the code cater to the tests.

I don't really want to get into debugging issues caused by creating a plethora of module namespaces, etc, and if we're hoping people emulate our approach it seems to set a poor standard.

**Comment by petebacondarwin** [comment]
I am happy to have the modules in a single namespace (or very few).  I would though question the idea that having many modules is setting a poor standard.  Notably the angular team themselves have used individual modules for each of the items that they have pulled out from the core.  It appears to me that modules are lightweight and once you have required them in your app, which you can do in tranches, the developer never has to think about them again.
What do multiple modules give you over a single big namespace?  I would argue that it creates greater flexibility in picking an choosing what you wish to include and use in your projects.
But then I am not too fussed as I said above.
