### ISSUE TITLE
reset directive may need a slight refactor

### ISSUE THREAD

**Issue by boneskull** [angular-ui/angular-ui-OLDREPO#123]
I'm looking at the reset directive and we're checking for the ngModel attribute and throwing an error.  Can't this same type of thing be accomplished by using a `require: 'ngModel'` and then passing it into the linking function?  

If so, I'm not sure what to do with the rest of the code once ngModel is passed into the linking function.  I don't quite have my head around ngModel yet.  Was wondering if PBD could look at this as he seems to know what's up with ngModel.

Please close this ticket if this is not necessary/doesn't make sense.

**Comment by ProLoser** [comment]
Reassigning to myself as I made this directive and it actually requires two refactors, one being that which you mention. The other is a flaw with the css

**Comment by ajoslin** [comment]
Also can we make the 'x' appear always if there's text, not just on hover? Or have an option for it (I have no idea how this directive works, but that would be nice)

**Comment by ProLoser** [comment]
@ajoslin you can just tweak the CSS if you want that. It's all done through CSS atm.
