### ISSUE TITLE
possible memory leak w/ auto-gen. forms?

### ISSUE THREAD

**Issue by zzal** [angular-ui/angular-ui-OLDREPO#130]
Hi all,

First off, great thanks for Christopher Hiller, having put this small but handy extension for AngularJS!

I'm having a small issue with duplicate controllers (seems like) when I dynamically generate my forms.
Somewhere in time, I'm prone to have crashes of my Chrome pane. 
If I insert this before the return line, line #204 in angular-ui.js :

``` javascript
console.log("setDate: "+controller.$viewValue);
```

It shows me that this logs one more time every time I generate a new form. I mean, the `controller.$render` is executed 4 times, suppose it's the fourth form that as been generated.

Maybe I have to kill something before I destroy my previous form? And how, if so?

**Comment by boneskull** [comment]
angular-ui.js is auto-generated, so it might be difficult for us to figure out where you are talking about exactly in the code.  If you can look at the angular-ui source and point us to the exact directive where this is happening, and hopefully provide us with a jsfiddle, we could help you further...
