### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#131]
I will try to take care of this this weekend.

**Comment by pkozlowski-opensource** [comment]
@ProLoser, Dean, I've got couple of PR pending: one for docs after fixing the unique filter (will be opening it in a couple of minutes) and fix for the #106. Actually, #106 triggers a question about IE8 suport: should we support it and if so should we try to fix all the IE8 issues before doing the release? #106 is about a bug in the code really (array.indexOf ont available) and not only about a test... Don't know for other IE8 issues but we might have bugs in the code as well....

**Comment by ProLoser** [comment]
I plan to remove the length filter since you can essentially do `{{ ( myArray | filter:{gender:'m'} ).length }}` instead. Anyone have problems with this?

**Comment by ProLoser** [comment]
Should have mentioned this sooner: if you're working on the next release, please work off of the angular-ui/release branch.

**Comment by ProLoser** [comment]
d36d16daa1001025c950858d970f2a5ecc85b67a
