### ISSUE TITLE
Version 0.2.0 release name is too short

### ISSUE THREAD

**Issue by ajoslin** [angular-ui/angular-ui-OLDREPO#137]
Need at least five more words.  megajuice-hamburgers-dangerzone-shnickerdoodle-regurgitation is not enough.

**Comment by ProLoser** [comment]
Ha ha ha ha
On Aug 6, 2012 5:10 AM, "Andy Joslin" <
reply@reply.github.com>
wrote:

**Comment by ProLoser** [comment]
mylittlepony-hemerrhoids-awesoomesauce

**Comment by Hoverbear** [comment]
+1

**Comment by boneskull** [comment]
WONTFIX

**Comment by Hoverbear** [comment]
Proposing the 0.3.0 release name be longer then 0.2.0 release name to help prevent this issue from cropping up again.

**Comment by ajoslin** [comment]
mylittlepony-hemerrhoids-awesomesauce-bossness-hummingbird-cheerwine-godsavethequeen

**Comment by ProLoser** [comment]
We should have started smaller so that each release gets bigger. WHAT HAST
WE WROTH?

On Sat, Aug 18, 2012 at 4:15 PM, Andy Joslin notifications@github.comwrote:

> mylittlepony-hemerrhoids-awesomesauce-bossness-hummingbird-cheerwine-woah-release
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/137#issuecomment-7849017.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by ProLoser** [comment]
Maybe replace awesomesauce with sriracha?

**Comment by ajoslin** [comment]
and add texaspete at the end.

mylittlepony-hemerrhoids-srirachasauce-bossness-hummingbird-cheerwine-godsavethequeen-texaspete

**Comment by ProLoser** [comment]
Cheerwine?

On Sat, Aug 18, 2012 at 5:00 PM, Andy Joslin notifications@github.comwrote:

> and add texaspete at the end.
> 
> mylittlepony-hemerrhoids-srirachasauce-bossness-hummingbird-cheerwine-godsavethequeen-texaspete
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/137#issuecomment-7849293.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by ajoslin** [comment]
A bawesome soda made in north carolina http://www.cheerwine.com/
