### ISSUE TITLE
AngularUI and Multiple jQuery UI Dialogs 

### ISSUE THREAD

**Issue by disperse** [angular-ui/angular-ui-OLDREPO#140]
I'm using the jQuery Passthrough module for AngularUI to separate content into dialogs on my page. The first dialog works great, the second dialog fails to correctly initialize.

Here's the jsfiddle:

http://jsfiddle.net/3wpKa/3/

**Comment by boneskull** [comment]
Hmm, this is bizarre.  This seems to fix the issue; wrapping it in divs.

http://jsfiddle.net/boneskull/3wpKa/5/

**Comment by disperse** [comment]
Thanks, that's a big help; I'm able to continue developing the application as planned.

**Comment by disperse** [comment]
So, another ui-jq question (let me know if you want me to take this offline or submit a different bug):

&lt;div ui-jq="dialog" ui-options="{title: 'Dialog 2', autoOpen: open, width: (.5 \* $(window).innerWidth)}"&gt;Dialog 2&lt;/div&gt;

I want to scale the dialog to the window, is there any way to make this work?  

http://jsfiddle.net/3wpKa/10/

**Comment by dandoyon** [comment]
not 100% sure whats going on here (well I kinda do). Having ui-options attribute is good for small apps but creating your own global ui-config for dialogs or in the case with example below, moving options into the controller maybe more of your liking. I did some fiddling with your fiddle and made its own app.  

http://jsfiddle.net/dandoyon/H6ewU/1/

**Comment by disperse** [comment]
Thanks dandoyon, that technique worked.  Trying to supply individual variables into the ui-options field didn't work but providing the complete object did.
