### ISSUE TITLE
"$digest already in progress" Error when updating model bound to tinymce textarea

### ISSUE THREAD

**Issue by disperse** [angular-ui/angular-ui-OLDREPO#148]
See:  http://jsbin.com/udayah/2/edit

In the app I'm working on the text is not updated but I get the same error.  The problem must be related.

**Comment by disperse** [comment]
I fixed the issue in my app where the text didn't update but the error still appears in the console.

**Comment by MrSaints** [comment]
I'm getting the same issue too. I believe it's a problem on Angular UI's side.

**Comment by kjakub** [comment]
yes, here too. Any clue?

**Comment by ProLoser** [comment]
This should be fixed in master and the latest release. I do not see the error in the fiddle.

**Comment by ProLoser** [comment]
@kjakub if you can confirm this is fixed in the latest version I will close this ticket.

**Comment by kjakub** [comment]
@ProLoser ticket is fixed - correct. Gem https://rubygems.org/gems/angularjs-rails is outdated. taking back.
