### ISSUE TITLE
New ui-href directive

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#151]
Compliments of @stefan-h-singer on IRC. Need to test it again though after I retouched it. Too busy to make a PR atm.

``` js
angular.module('ui.directives').directive('uiHref', ['$location', function($location) {
    return {
      link: function(scope, element, attrs) {
          var href;
          attrs.$observe("uiHref", function(value) {
            attrs.$set("href", value);
            href = value;
          });
          element.click(function(event){
            event.preventDefault();
            $location.path(href);
          });
      }
    };
}]);
```

If you specify `ui-href="some/routed/{{path}}/to/a/page"` it will attach a natural href attribute (so that you can right-click and copy/bookmark the link) but also binds a click event that does `$location.path(uiHref)`. This way you can use HTML5's hot-swap URL feature and ALSO have bookmark-able links. I'm thinking this could potentially be useful to others.

**Comment by stefan-h-singer** [comment]
For what it's worth, this works a treat for me and I'm using it all over the place in our project. Sorry I haven't made a PR yet :)

**Comment by ProLoser** [comment]
I think this is native behavior now. https://github.com/angular/angular.js/blob/c0ad2efb24e4fffff6cb503ca821fe7e0bd4618b/src/ng/directive/booleanAttrs.js#L321-L342 as you can see it's creating a simple `href` attribute already. And I could have sworn you have to do `target="_self"` to get it NOT to use `$location`
