### ISSUE TITLE
ui-keypress needs to be refactored

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#154]
ui-keypress now passes the $event object just like uiEvent does, however I ran into a few problems when working with the demo:
1. The event is binded to keydown. It is impossible to preventDefault() with the intended effect on this event.
2. It is impossible to handle multiple keys simultaneously in keypress, keydown must be used.

For this reason I think we should add 2 more variations to this directive:

ui-keypress, for common behavior, but only support a single key
ui-keydown, for multiple key behavior
ui-keyup, for any other cases

We can keep all 3 cases in the same file as different directives since they are slow closely related. It would also be ideal to get as much DRY reuse as possible out of the code.
## Related Discussions:
- https://groups.google.com/forum/?fromgroups#!searchin/angular-ui/keypress/angular-ui/RLFSPb6Vtsg/2RdDHks9kWkJ%5B1-25%5D
- https://groups.google.com/forum/?fromgroups#!searchin/angular-ui/keypress/angular-ui/bI6MLOGm_NQ/0DMuxX2rRu8J%5B1-25%5D

**Comment by ajoslin** [comment]
I think we do need to worry about backwards compatibility with ui-keypress, though?  It's probably the most widely-used directive.

Also, we should add ability to have the same actions split by spaces, like regular events.  

``` html
<div ui-keypress="{'enter shift': 'enterOrShiftAction()'}"></div>
```

**Comment by ProLoser** [comment]
I agree about spaces. We should drop the dashes entirely. 

As for backwards, the directive is Honestly broken and we aren't stable. We should make it very visible and clear that there is an api change but I don't think we should focus on backwards compatibility.

**Comment by ajoslin** [comment]
Ok, I guess.  we are early and setting up a good api is important.

**Comment by ProLoser** [comment]
I got this one started here: https://github.com/angular-ui/angular-ui/blob/keypress/modules/directives/keypress/keypress.js but I'm tired and will have to finish it in the next few days.

If anyone wants to give a crack at continuing the cleanup be my guest.

Note: yes I'm aware the function clutters the global namespace. We can look at putting the directive (or the entire lib) in a closure to avoid this later, for now my main priority is to correct this directive.

I took out the unusual string syntax, and dropped the dash separator in exchange for spaces (which is more consistent with binding multiple events at once in jquery). I feel as though it would be possible to cleanup the logic a little bit more too, but haven't had a chance to do this yet.

**Comment by ProLoser** [comment]
@ajoslin is the events directive capable of having multiple events cause the same trigger? My current implementation is inconsistent with what you proposed (this did not occur to me until I just reread it now). I can go back to the dashed-notation so that you may group multi-keypresses together using dashes but separate groups by spaces, or we can just require to declare multiple key:value pairs with identical values. I'm open to suggestions.

**Comment by ajoslin** [comment]
Hey dean,

Yeah, uievent lets you have multiple events in one key triggering the same
value.  I think dash was OK as a separator, and space could be used as an
'or' operator inside a key, so its consistent with uievent.

**Comment by dandoyon** [comment]
I just happening to be glancing at jquery-ui and found this at top. Could be of use in rewrite

```
keyCode: {
    ALT: 18,
    BACKSPACE: 8,
    CAPS_LOCK: 20,
    COMMA: 188,
    COMMAND: 91,
    COMMAND_LEFT: 91, // COMMAND
    COMMAND_RIGHT: 93,
    CONTROL: 17,
    DELETE: 46,
    DOWN: 40,
    END: 35,
    ENTER: 13,
    ESCAPE: 27,
    HOME: 36,
    INSERT: 45,
    LEFT: 37,
    MENU: 93, // COMMAND_RIGHT
    NUMPAD_ADD: 107,
    NUMPAD_DECIMAL: 110,
    NUMPAD_DIVIDE: 111,
    NUMPAD_ENTER: 108,
    NUMPAD_MULTIPLY: 106,
    NUMPAD_SUBTRACT: 109,
    PAGE_DOWN: 34,
    PAGE_UP: 33,
    PERIOD: 190,
    RIGHT: 39,
    SHIFT: 16,
    SPACE: 32,
    TAB: 9,
    UP: 38,
    WINDOWS: 91 // COMMAND
}
```

**Comment by pkozlowski-opensource** [comment]
@dandoyon Dan, yes, we've got something similar but not as complete as jQuery's:
https://github.com/angular-ui/angular-ui/blob/d0bd0c12a92623aec11069b617358079656f3229/modules/directives/keypress/keypress.js#L3

**Comment by kevinwestern** [comment]
If suggestions are still open, I'd suggest the rules css follows: 

``` javascript
<div ui-keypress="{'enter, shift': 'enterOrShiftAction()'}"></div>
```

That way it's familiar with what people already know.

**Comment by ProLoser** [comment]
@kevinwestern bindings in jquery are already separated by spaces to represent alternatives. However multiple bindings put together has not been covered natively.

**Comment by kevinwestern** [comment]
Oh yeah, I forgot about jQuery :(

**Comment by ajoslin** [comment]
We could still support commas, though.. Although it would be less efficient.
