### ISSUE TITLE
Push v0.3.0 this weekend?

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#158]
I finally have some time for a breather. Should I go through and collect the open pull requests this weekend? Perhaps I may also have some time to resolve some tickets too?

**Comment by pkozlowski-opensource** [comment]
+1 for 0.3 this weekend. 
We've got some fixes done, some PR waiting. I should also have some time this weekend to look into tickets.

**Comment by ajoslin** [comment]
Go for it.  I also started the builder, I'll open a PR for that (probably won't be done this weekend though)

**Comment by dandoyon** [comment]
I have been dragging my feet, I have the angularjs rewrites of bootstrap dropdowntoggle and tabble directives. Just tried to push to my git and its complaining. I may have frig'd up my ssh stuff when I installed homebrew....

argh

**Comment by ProLoser** [comment]
Moving @pkozlowski-opensource groups posting onto this thread:

I guess we will be releasing 0.3 this weekend so we need to resolve
some of the issues. From what I can see those are open items that
needs attention:

#152 (ui-mask)
#154 (keypress rewrite)
#161 (datepicker)
#167 (datepicker, is it
the same as above?)
#162 (ui-currency)
#172 (PR for full callendar)

AFAIK Dean is on the keypress and boneskull started to have a look
into datepicker. Given this I can have a look into the ui-mask and the
PR, unless someone started to work on those items already.

Question: are we going to push
#151 this weekend?

At the same time there are issues that I believe we should close:
#150
#141

**Comment by petebacondarwin** [comment]
I believe my date picker plunk solves the depicted problems but it fails
some unit tests as they don't run apply to ensure the watches have run
before checking their expectations.

... sent from my tablet

**Comment by boneskull** [comment]
I've fixed 161 to my satisfaction using Pete's code.  This may also fix 167.  I plan to work on this a bit more this weekend, but I need to rebase my branch or something like that because my PR couldn't be automatically merged, so I'm doing something wrong.

Chris

**Comment by boneskull** [comment]
OK, I was able to make a PR for this.

**Comment by boneskull** [comment]
On Aug 23, 2012, at 12:49 PM, Pete Bacon Darwin notifications@github.com wrote:

> > #161 https://github.com/angular-ui/angular-ui/issues/161 (datepicker) 
> > #167 https://github.com/angular-ui/angular-ui/issues/167 (datepicker, 
> > is it 
> > the same as above?) 

I've pushed fixes for these two issues in PR 177. https://github.com/angular-ui/angular-ui/pull/177

**Comment by pkozlowski-opensource** [comment]
On my side I've pushed fix for #152 (ui-mask). Could someone please review?
