### ISSUE TITLE
ui-currency oneway binding redux

### ISSUE THREAD

**Issue by dandoyon** [angular-ui/angular-ui-OLDREPO#162]
If anyone has time, please look and comment this the ui-currency directive changes I've made and let me know if you think 
these are good or not. 

https://github.com/dandoyon/angular-ui/tree/ui-currency-oneway

I've done a couple of things. First you can do <span ui-currency>{{foo}}</span> which is pretty simple when you want to style
an ng-bind value. 

Also, I (should've done this separately but oh well) I added a couple of options { 'bignum' : "100", 'smallnum' : '-100' } and an attribute is-total. What I'm providing is a way to allow for providing styles to numbers that are real big/small based on the value provided. Right now positive numbers are tied to big numbers, negative to small. 

You could imagine in an accounting application wanting to give more visibility in certain situations. I  provided is-total attribute to prevent the new ui-bignum, ui-small num css classes from being applied where you don't want this behavior. 

If I have time this weekend, I'll create a fiddle to look at. 

--thx

**Comment by ProLoser** [comment]
@dandoyon I know this is super old, but did this ever get merged in / completed?

**Comment by nateabele** [comment]
This repo is discontinued, and this feature has been removed.
