### ISSUE TITLE
Can't add markers to map from controller

### ISSUE THREAD

**Issue by andrew-jones** [angular-ui/angular-ui-OLDREPO#173]
I've setup an example here, http://plnkr.co/edit/LO7ci1

Markers aren't added to the map.  I've followed the example page, with the exception of defining the marker in the controller.

**Comment by andrew-jones** [comment]
I'm available on IRC if required.

**Comment by ajoslin** [comment]
Hi Andrew,

Unfortunately, the map is created in a directive - so it won't exist on the first run of the controller.

You could $watch until the map variable exists, though:

``` javascript
$scope.$watch('myMap', function(map) {
  if (map) {
    //map exists now!!
  }
});
```

Since the map requires an element we had to create it using a directive - there wasn't a better way we could think of.

**Comment by ProLoser** [comment]
Why do you have to pass the map as a parameter? Perhaps we can abstract
this?

**Comment by pckhoi** [comment]
Thanks to ajoslin's comment above, I come to a solution. I use this instead of the default directive:

```
app.directive('uiMapMarker', ['$parse', function($parse) {
    var events = 'animation_changed click clickable_changed cursor_changed ' +
        'dblclick drag dragend draggable_changed dragstart flat_changed icon_changed ' +
        'mousedown mouseout mouseover mouseup position_changed rightclick ' +
        'shadow_changed shape_changed title_changed visible_changed zindex_changed';
    return {
        restrict: 'A',
        link: function (scope, elm, attrs) {
            var mapName = attrs.map;
            var lat = parseFloat(attrs.lat);
            var lon = parseFloat(attrs.lon);
            f = scope.$watch(mapName, function(map) {
                if (map) {
                    var marker = new google.maps.Marker({
                        map: map,
                        position: new google.maps.LatLng(lat, lon)
                    });
                    var model = $parse(attrs.uiMapMarker);

                    model.assign(scope, marker);
                    bindMapEvents(scope, events, marker, elm);
                    f();
                }
            });
        }
    };
}]);
```

It allow you to declare which map you hook to and also lat and lon on the element. No need to write anything in controller.

**Comment by ProLoser** [comment]
@ajoslin can you review this and close it if it's no longer relevant?

**Comment by ajoslin** [comment]
Ah, I missed this one.

@pckhoi, why are you doing it this way?  Couldn't you just create the marker with `new google.maps.Marker($scope.myMap, ...)` in your controller?

**Comment by ProLoser** [comment]
I would think `$scope.myMap` is undefined when the controller's constructor
is being fired.

**Comment by ajoslin** [comment]
Yeah, that's what the `$watch` is for.  You could also just do a `setTimeout` before doing anything.

But it's really bad that the user has to do this...

**Comment by ProLoser** [comment]
Hmm touche. Your suggestion didn't have a `$watch`. I'm just trying to
close as many tix as possible so feel free to address or reject this one as
you see fit.

**Comment by JakobJingleheimer** [comment]
Just a heads up for anyone else with this problem: I encased the element with the `ui-map` attribute within a `ui-if`that watches a variable whose boolean value I set in the controller after I've finished gathering/prepping data for the ui-map directives (I'm retrieving map options, marker locations, etc via ajax).

``` html
<div ui-if="mapdata_ready">

    <div
      id="map_canvas"
      ui-map="map.map"
      ui-options="map.options"
    ></div>

    <div
      ng-repeat="marker in map.markers"
      ui-map-marker="map.markers[$index]"
      ui-event="{'map-click':'openMarkerInfo(marker)'}"
    ></div>

    <div
      ic-map-info-box="map.infowindow"
      ng-include="'views/infowindow.html'"
    ></div>

</div>
```

**Comment by vpixle** [comment]
Gentleman this one is one of the most frequent issue, would anybody create a simple working Plunker that can show up markers from controller? There is too many "you should probably do this" and "... btw, make sure that" which makes the whole thing even more tricky. Forty lines of code may help thousand people! Many thanx in advance.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-map (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-map

Please reopen this issue there if it is still relevant.
