### ISSUE TITLE
ui-focus directive to overcome ng-cloak on body

### ISSUE THREAD

**Issue by prasad83** [angular-ui/angular-ui-OLDREPO#174]
``` javascript
angular.module('ui.directives').directive('uiFocus', ['ui.config', '$timeout', function(uiConfig, $timeout){
    return {
        restrict: 'EAC',
        link: function (scope, iElement, iAttrs) {
            iElement.focus();
        }
    }
}]);
```

ng-cloak use on body knocks default autofoucs form element behavior on FF - use ui-focus instead.

Usage:

``` html
<body ng-cloak>
    <form>
        <input type="text"  ui-focus required="required">
   </form>
</body>
```

**Comment by ProLoser** [comment]
I highly recommend not putting cloak on the body tag. Can you provide a plunker or fiddle that demonstrates this issue? 

Also, I am pretty sure you could just do ui-jq=focus

**Comment by ProLoser** [comment]
I see this issue. However I recommend NOT using it as an alternative to autofocus, but instead creating a directive around the autofocus attribute that simply fixes firefox behavior.

Regardless, I don't really think we should be implementing such a simple directive because 1: the best implementation would be NOT to namespace it, and that is out of our 'jurisdiction', and 2: if you don't mind the namespace then you might as well do `ui-jq="focus"`

However nothings stopping you from creating an autofocus directive in your own app.

**Comment by petebacondarwin** [comment]
How about a pull request on the angularjs project itself??

... sent from my tablet

**Comment by ProLoser** [comment]
Do you think this should be merged? I figured the PR was a moot point as I
intended to close this ticket once I got some confirmation from others.

On Thu, Aug 23, 2012 at 2:00 PM, Pete Bacon Darwin <notifications@github.com

> wrote:
> 
> How about a pull request on the angularjs project itself??
> 
> ... sent from my tablet
> On Aug 23, 2012 9:49 PM, "Dean Sofer" notifications@github.com wrote:
> 
> > I see this issue. However I recommend NOT using it as an alternative to
> > autofocus, but instead creating a directive around the autofocus
> > attribute
> > that simply fixes firefox behavior.
> > 
> > Regardless, I don't really think we should be implementing such a simple
> > directive because 1: the best implementation would be NOT to namespace
> > it,
> > and that is out of our 'jurisdiction', and 2: if you don't mind the
> > namespace then you might as well do ui-jq="focus"
> > 
> > However nothings stopping you from creating an autofocus directive in
> > your
> > own app.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/angular-ui/angular-ui/issues/174#issuecomment-7983561>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/174#issuecomment-7983875.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by petebacondarwin** [comment]
I meant that the person who wrote it should put in a pull request to the
angularjs project rather than ours.

... sent from my tablet

**Comment by ProLoser** [comment]
Oh. Ya. I thought that too but then figured they would reach the same
conclusion I did.

On Thu, Aug 23, 2012 at 2:10 PM, Pete Bacon Darwin <notifications@github.com

> wrote:
> 
> I meant that the person who wrote it should put in a pull request to the
> angularjs project rather than ours.
> 
> ... sent from my tablet
> On Aug 23, 2012 10:02 PM, "Dean Sofer" notifications@github.com wrote:
> 
> > Do you think this should be merged? I figured the PR was a moot point as
> > I
> > intended to close this ticket once I got some confirmation from others.
> > 
> > On Thu, Aug 23, 2012 at 2:00 PM, Pete Bacon Darwin <
> > notifications@github.com
> > 
> > > wrote:
> > > 
> > > How about a pull request on the angularjs project itself??
> > > 
> > > ... sent from my tablet
> > > On Aug 23, 2012 9:49 PM, "Dean Sofer" notifications@github.com
> > > wrote:
> > > 
> > > > I see this issue. However I recommend NOT using it as an alternative
> > > > to
> > > > autofocus, but instead creating a directive around the autofocus
> > > > attribute
> > > > that simply fixes firefox behavior.
> > > > 
> > > > Regardless, I don't really think we should be implementing such a
> > > > simple
> > > > directive because 1: the best implementation would be NOT to
> > > > namespace
> > > > it,
> > > > and that is out of our 'jurisdiction', and 2: if you don't mind the
> > > > namespace then you might as well do ui-jq="focus"
> > > > 
> > > > However nothings stopping you from creating an autofocus directive
> > > > in
> > > > your
> > > > own app.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > 
> > > https://github.com/angular-ui/angular-ui/issues/174#issuecomment-7983561>.
> > > 
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/angular-ui/angular-ui/issues/174#issuecomment-7983875>.
> > 
> > ## 
> > 
> > Dean J Sofer
> > DeanSofer@gmail.com
> > 
> > BS Computer Information Systems
> > California State Polytechnic University, Pomona
> > Telephone: 714-900-2254
> > Website: www.DeanSofer.com
> > Github: github.com/ProLoser
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/angular-ui/angular-ui/issues/174#issuecomment-7983950>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/174#issuecomment-7984180.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser
