### ISSUE TITLE
Bootstrap ui stuff

### ISSUE THREAD

**Issue by ajoslin** [angular-ui/angular-ui-OLDREPO#18]
How should I move some bootstrap ui stuff I've written ( https://github.com/ajoslin/angular-bootstrap-ui ) into angular-ui?  A lot of the directives will have a dependency of a certain bootstrap JS script (eg modalDirective.coffee depends on bootstrap-modal.js, written by twitter guys).  How would I set up these dependencies?

**Comment by ProLoser** [comment]
We're working this out ourselves, we'll be able to go over it in the hangout.

Currently, at the very least I'm using javadoc conventions on each of my module file with the `@requires` or `@require` fields referring to URLS or something. At the very least until we have something better setup.
