### ISSUE TITLE
grunt build doesn't work on windows

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular-ui/angular-ui-OLDREPO#180]
After changes introduced in the #160 `grunt build` doesn't work on windows anymore (it produces almost empty build files). This is due to hard-coded unix-style paths: https://github.com/angular-ui/angular-ui/blob/master/grunt.js#L76

The remedy is simple, we should be using `path.sep` from node's path. PR will follow shortly.

**Comment by petebacondarwin** [comment]
Actually it would be nicer to replace the grunt.file.recurse with
grunt.file.expandDirs('modules/*', ...)

Pete
...from my mobile.

**Comment by pkozlowski-opensource** [comment]
Fixed in 1ba6a6a and 9aab96f. Closing.
