### ISSUE TITLE
Idea for a new uiResource service

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#182]
There has been a lot of questions and complaints regarding getting `$resource` to return a promise object. I was discussing different solutions I might try and thought this might be a grounds for a good service. It's all "theoretical programming" so keep in mind I have never used `$resource` or `$q` and none of this is tested. More work would need to be done to make this functional.

This code comes with 3 proposed enhancements, each of which could be used independently of one another. I'm also making an assumption that every method call eventually goes through `$resource.query()`.

I also think it might be better to looking into making a **decorator** instead, but I haven't researched how to do this. I also don't like that I'm supplementing objects rather than the original object definition (like the prototype or something).

``` js
// Using a factory so that 'new' will not be called, since it's already called on $resource when injected
app.factory('uiResource', ['ngResource', '$q', function($resource, $q){

  // Feature #1
  // The data reference would contain a data.prototype.$promise attribute that devs can use as they wish
  var oldQuery = $resource.query;
  $resource.query = function(options){
    var that = this, data;
    options.success = function(response, code){
      data.prototype.$promise.resolve(data, code);
    };
    data = oldQuery(options);
    data.prototype.$promise = $q.defer();
    return data;
  };

  // Feature #2
  // Alternative to $resource.query() that returns a promise instead of a reference
  $resource.promise = function(options){
    var that = this,
        promise = $q.defer();
    options.success = function(data, code) {
      promise.resolve(data, code);
    };
    options.error = function(data, code) {
      promise.reject(data, code);
    };
    that.query(options);
    return promise;
  };

  // Feature #3
  // A reference to all promises (unfinished). We could store promise objects in here for easy access at any time. Perhaps namespace each promise?
  $resource.promises = [];

  return $resource;
}]);
```

Part of the beauty of this is that people do not have to change any code in order to start using these features as the API remains the same. They merely change the injection string:

``` js
MyController.$inject = ['ngResource'];
// becomos
MyController.$inject = ['uiResource'];
```

**Comment by pkozlowski-opensource** [comment]
Thnx for opening this ticket, I would like to spend some time on this topic as well. But _after_ ui-input is done and Travis up and running :-)

**Comment by dandoyon** [comment]
Dean,

A while back there was a pretty extensive thread on Misko's rewrite of $resource (which did not get into 1.0) and an RFC regarding what would make for a good resource impl.  You might want to take a look there just for reference.

I'm not sure about overwriting the existing query object, it may be confusing to someone using resource already. What about naming it something like 'fetch' instead? 
I'm using resource right now but have not used $q, I believe I understand its use but until I use it, I can't speak to it with any authority. 

It will take me a bit to wrap my head around what the three features are providing. I agree that there is quite a bit of confusion surrounding the resource.

I'd like to play with it and see how it improves my life. I've been pretty busy as of late but will do a reset with angular-ui shortly

--dan

**Comment by ProLoser** [comment]
I don't use $resource or $q, this just was my ideas I proposed from
discussions. Honestly I would benefit in no immediate way if we were to
implement this but I know a lot of other people would.

I'm wrapping the `.query()` method so that I can supplement its behavior.
It is not supposed to replace it but instead add one more feature, however
it should not be overriding the `success` callback. This is more food for
thought.

On Wed, Aug 29, 2012 at 5:33 PM, Dan Doyon notifications@github.com wrote:

> Dean,
> 
> A while back there was a pretty extensive thread on Misko's rewrite of
> $resource (which did not get into 1.0) and an RFC regarding what would make
> for a good resource impl. You might want to take a look there just for
> reference.
> 
> I'm not sure about overwriting the existing query object, it may be
> confusing to someone using resource already. What about naming it something
> like 'fetch' instead?
> I'm using resource right now but have not used $q, I believe I understand
> its use but until I use it, I can't speak to it with any authority.
> 
> It will take me a bit to wrap my head around what the three features are
> providing. I agree that there is quite a bit of confusion surrounding the
> resource.
> 
> I'd like to play with it and see how it improves my life. I've been pretty
> busy as of late but will do a reset with angular-ui shortly
> 
> --dan
> 
> On Aug 29, 2012, at 3:05 PM, Dean Sofer wrote:
> 
> > There has been a lot of questions and complaints regarding getting
> > $resource to return a promise object. I was discussing different solutions
> > I might try and thought this might be a grounds for a good service. It's
> > all "theoretical programming" so keep in mind I have never used $resource
> > or $q and none of this is tested. More work would need to be done to make
> > this functional.
> > 
> > This code comes with 3 proposed enhancements, each of which could be
> > used independently of one another. I'm also making an assumption that every
> > method call eventually goes through $resource.query().
> > 
> > I also think it might be better to looking into making a decorator
> > instead, but I haven't researched how to do this. I also don't like that
> > I'm supplementing objects rather than the original object definition (like
> > the prototype or something).
> > 
> > // Using a factory so that 'new' will not be called, since it's already
> > called on $resource when injected
> > app.factory('uiResource', ['ngResource', '$q', function($resource, $q){
> > 
> > // Feature #1
> > // The data reference would contain a data.prototype.$promise attribute
> > that devs can use as they wish
> > var oldQuery = $resource.query;
> > $resource.query = function(options){
> > var that = this, data;
> > options.success = function(response, code){
> > data.prototype.$promise.resolve(data, code);
> > };
> > data = oldQuery(options);
> > data.prototype.$promise = $q.defer();
> > return data;
> > };
> > 
> > // Feature #2
> > // Alternative to $resource.query() that returns a promise instead of a
> > reference
> > $resource.promise = function(options){
> > var that = this,
> > promise = $q.defer();
> > options.success = function(data, code) {
> > promise.resolve(data, code);
> > };
> > options.error = function(data, code) {
> > promise.reject(data, code);
> > };
> > that.query(options);
> > return promise;
> > };
> > 
> > // Feature #3
> > // A reference to all promises (unfinished). We could store promise
> > objects in here for easy access at any time. Perhaps namespace each
> > promise?
> > $resource.promises = [];
> > 
> > return $resource;
> > }]);
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/182#issuecomment-8145925.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by dandoyon** [comment]
Got it! You are a selfless individual my friend

+1
