### ISSUE TITLE
Please create an npm package 

### ISSUE THREAD

**Issue by jasonkuhrt** [angular-ui/angular-ui-OLDREPO#184]
This would be very much appreciated.

I wonder/realize you guys might be waiting for/relying on yeoman.io for package distribution but until then something we can use through (for example) browserify would be, again, much appreciated.

**Comment by ProLoser** [comment]
I'm not sure how to organize a client-side project for NPM. I know Edward
who made the AngularJS NPM project, but it was a some sort of
Node.js+AngularJS boilerplate and I think it's very out of date and
possibly unfinished.

Of course you could always submit a PR if you have your own idea on how to
do this :)
On Thu, Aug 30, 2012 at 12:42 PM, Jason Kuhrt notifications@github.comwrote:

> This would be very much appreciated.
> 
> I wonder/realize you guys might be waiting for/relying on yeoman.io for
> package distribution but until then something we can use through (for
> example) browserify would be, again, much appreciated.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/184.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by ProLoser** [comment]
We're on bower (apparently). Also 22efd124ed4efc3c812e7dd1135d8c3d6db1da0a
