### ISSUE TITLE
angularjs with select2

### ISSUE THREAD

**Issue by javedwahid** [angular-ui/angular-ui-OLDREPO#187]
Hi,

I am trying to get 2 dropdowns to sync together using angularjs.  which works, but not when the dropdowns are select2 dropdowns:  here is a fiddle to demonstrate what I'm talking about: http://jsfiddle.net/SDSCc/5/

One thing I did notice is that on the select2 website, the format they use for programmatically changing the value of the dropdown is $('#ID').select2('val', VALUE);

which is why I'm thinking that making the ng-model of the 2 dropdowns the same doesn't work, because angularjs doesn't know how to set the value of the select2 dropdown.  I'm wondering if anyone has been able to get this to work?

thanks in advance for the help.

**Comment by ProLoser** [comment]
If you're not using our directive, how do you expect this to work? Are you aware there is a ui-select2 directive?

**Comment by ProLoser** [comment]
http://plnkr.co/edit/gist:3172544?p=preview&s=select2

**Comment by javedwahid** [comment]
I was not aware of the ui-select2 directive.  Thank you. I was able to get it to work, the example really helped. I notice that using ui-select2 automatically turns the <select> into a select2 dropdown without having to call $('.select-select2').select2();  but now I can't figure out a way to set the width to what I want it to be, I used to do $('.select-select2').select( { width: '100px' } ); - do you know how to set this?

Thanks again

**Comment by ProLoser** [comment]
There are instructions on the demo page, you really should go check it out.
Essentially you can do either ui-select="{width:200}" or
ui-select2="select2config" or you can instead define your settings app-wide
by using the approach outlined in ui.config. I personally recommend using
ui.config and only passing options if you want to override the defaults.

If you don't mind, close this issue if this resolves your problems :)

On Wed, Sep 5, 2012 at 1:20 PM, javedwahid notifications@github.com wrote:

> I was not aware of the ui-select2 directive. Thank you. I was able to get
> it to work, the example really helped. I notice that using ui-select2
> automatically turns the into a select2 dropdown without having to call
> $('.select-select2').select2(); but now I can't figure out a way to set the
> width to what I want it to be, I used to do $('.select-select2').select( {
> width: '100px' } ); - do you know how to set this?
> 
> Thanks again
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/187#issuecomment-8312467.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by javedwahid** [comment]
I will check that out, thanks
