### ISSUE TITLE
Create jsFiddle's for all the given examples

### ISSUE THREAD

**Issue by guilleferrer** [angular-ui/angular-ui-OLDREPO#192]
It would be nice to have jsFiddle examples for All the examples you provide here, so it is easier to understand and experiment how to use every directive you have implemented.

**Comment by pkozlowski-opensource** [comment]
@guilleferrer we've got examples on the http://angular-ui.github.com/ page. 

But effectively, it would be nice to have the ability to run each and every example in a separate jsFiddle, exactly like on the AngularJS home page. 

Would you be interested in contributing such changes to our existing pages?

**Comment by guilleferrer** [comment]
Yes, I could help.
Should I create the jsFiddles myself and then i pass you the url so you can
include it in the docs ?
I won't have time to to them all at once, so I will be sending you one by
one all the examples.
Is that ok?

2012/10/21 Pawel Kozlowski notifications@github.com

> @guilleferrer https://github.com/guilleferrer we've got examples on the
> http://angular-ui.github.com/ page.
> 
> But effectively, it would be nice to have the ability to run each and
> every example in a separate jsFiddle, exactly like on the AngularJS home
> page.
> 
> Would you be interested in contributing such changes to our existing pages?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/192#issuecomment-9641733.

## 

Guillermo Ferrer Moregó
+34666041955
guilleferrer@gmail.com

**Comment by pkozlowski-opensource** [comment]
@guilleferrer, no, no, we shouldn't be creating fiddles by hand, it would create maintenance hell :-(

Please have a look at the AngularJS home page - what those guys are doing is that you can create a jsFiddle "on the fly"  by posting fiddle's content to the jsFiddle web site. With this approach "the only source of truth" is in the repository (examples checked it) and fiddles are created on the fly.

So, all in all, the effort would be more to see how to automatically create fiddles / plunks from the examples we've got already, rather than creating those from scratch by coping & pasting code.

**Comment by ProLoser** [comment]
Or we can create plunkers and use gists :)

On Mon, Oct 22, 2012 at 10:44 AM, Pawel Kozlowski
notifications@github.comwrote:

> @guilleferrer https://github.com/guilleferrer, no, no, we shouldn't be
> creating fiddles by hand, it would create maintenance hell :-(
> 
> Please have a look at the AngularJS home page - what those guys are doing
> is that you can create a jsFiddle "on the fly" by posting fiddle's content
> to the jsFiddle web site. With this approach "the only source of truth" is
> in the repository (examples checked it) and fiddles are created on the fly.
> 
> So, all in all, the effort would be more to see how to automatically
> create fiddles / plunks from the examples we've got already, rather than
> creating those from scratch by coping & pasting code.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/192#issuecomment-9673280.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by pkozlowski-opensource** [comment]
Yes, was thinking abut gists as well. The only thing is that examples need to somehow correspond to our released versions. I mean, we might change examples witch each release. So, we would have to sync gists with our main repo.

What I was thinking of was more like having examples checked-in next to the source code and then both dynamically generate docs / examples from it and have this ability to create gists / plunks on the fly. Once again, the source code repo should be the only source of truth for me.

**Comment by guilleferrer** [comment]
Maybe a good option would be creating first Guists, so we have the version
control, and then we can create jsFiddles from those gists, using this :
http://doc.jsfiddle.net/use/gist_read.html

What do you think?

2012/10/22 Pawel Kozlowski notifications@github.com

> Yes, was thinking abut gists as well. The only thing is that examples need
> to somehow correspond to our released versions. I mean, we might change
> examples witch each release. So, we would have to sync gists with our main
> repo.
> 
> What I was thinking of was more like having examples checked-in next to
> the source code and then both dynamically generate docs / examples from it
> and have this ability to create gists / plunks on the fly. Once again, the
> source code repo should be the only source of truth for me.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/192#issuecomment-9674299.

## 

Guillermo Ferrer Moregó
+34666041955
guilleferrer@gmail.com

**Comment by dandoyon** [comment]
Saw this thread yesterday and this is "close to home" since I did the jsfiddle integration for the angularjs site.  I'll have to review my code to see what I did, but it would be great to have it integrated into our doc so that its in one place, less room for error.  The gist solution looks interesting too. 

--dan

**Comment by pkozlowski-opensource** [comment]
Well, the only problem with gists is that those are separated from the source code and its version... 
@dandoyon I didn't know that you contributed jsFiddle integration to AngularJS. It would be so awesome if we could have sth like this for angular-ui...

**Comment by nateabele** [comment]
This repo is discontinued. Please reopen this issue against the relevant repositories as applicable.
