### ISSUE TITLE
Select2 directive is broken with tag widget type.

### ISSUE THREAD

**Issue by wesalvaro** [angular-ui/angular-ui-OLDREPO#193]
When using a Select2 tag widget, the data binding is not two-way, and is not updated on dirty scope.

The data going into a tag widget is Array.<string>
The data coming out of a tag widget is Array.<{id:string, text:string}>

Updating the values in an $apply does not update the widget consistently.

**Comment by wesalvaro** [comment]
I'd like to take this as I've worked on a solution locally. I don't have a pull request ready, though.

**Comment by ProLoser** [comment]
Here you go. In fact, take 3, just to be safe.

On Tue, Sep 11, 2012 at 11:26 PM, Wes Alvaro notifications@github.comwrote:

> I'd like to take this as I've worked on a solution locally. I don't have a
> pull request ready, though.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/193#issuecomment-8483429.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by ProLoser** [comment]
@wesalvaro WHERE ARE YOU MAN? We miss you.

**Comment by ProLoser** [comment]
http://plnkr.co/edit/tJ5amoJGXwgOmX4VZf8j
