### ISSUE TITLE
Datepicker and i18n

### ISSUE THREAD

**Issue by ghost** [angular-ui/angular-ui-OLDREPO#194]
Actually I can't seem to find a way to make the datepicker work with the currently included angular_<culture>.js script included in my page.

I managed to make it somewhat work passing the "dateformat" option in the ui-date attribute, but this works only for the rendering of the date, but not for reading the date from the objects.

Example: if I read from a server-side service the date 10 august 2012 in italian format (10/08/2012), even if I set the datepicker format to "Italian", the date will be interpreted as english, so I will get October 8 instead of August 10.

From that point, if I change date with the datepicker it will be correct, but anyway it's useless like that. And all the other things about the datepicker aren't localized like day and month names, etc.

I even tried including jquery ui i18n module and setting the defaults using the regional attribute, which usually works, but it didn't help either.

I couldn't find anything on the docs that point on how to make the datepicker work correctly with i18n. I think this is a critical usability feature.

**Comment by ProLoser** [comment]
Have you tried passing the options to ui.config? I'm not familiar with i18n in datepicker. Is the problem you are having with the datepicker itself working properly or are you struggling to pass the correct options to datepicker?

**Comment by ghost** [comment]
I couldn't find a clear explanation of how ui.config works, and there's no example related to the datepicker. When working with plain jquery and jquery ui you just include the right i18n file based on your desired culture and the datepicker automatically works, both in display and date formatting (both reading and writing) meaning that if I set italian when it reads a date string it expects it to be in italian format, and displayes it in italian format, etc.

If you could provide a full example on how to achieve it it would be great. I don't mind using either jquery ui i18n or angular i18n as long as it works and it doesn't require to configure every single input with ui-date manually.

**Comment by ProLoser** [comment]
You can pass options to every instance in one location using ui.config.
There is a brief explanation of how it works at the top of the demo page.
If jQuery ui just automatically starts localizing as soon as you attach a
file to the document and it's not working then this could be a different
problem.

Can you create a plunker or fiddle showing your problem and attempted
solution? This would help speed things up exponentially.

**Comment by petebacondarwin** [comment]
Here is a fiddle to get you started.   http://jsfiddle.net/qGeuU/
The date picker uses the dateFormat option to specify what format the
string that you pass can be.
The localization doesn't actually make any difference to the date parsing,
it is purely for display purposes.
You can either set the dateFormat per date directive as shown or you can
use the ui.config object in this version:  http://jsfiddle.net/qGeuU/1/
By the way, you'll notice that I have overridden the current release of
date picker with the master from github (in the resources section on the
left).  We need to release a new version of angular-ui with this fixed
version of the datepicker.
Pete

**Comment by ghost** [comment]
I've tried your fiddle and it works correctly. I can replace the hardcoded 'dd/mm/yy' with $.datepicker.regional.dateFormat to make it dynamic and it's perfect.

However it works only in the fiddle, and it doesn't work with the version of angular UI I have downloaded. For instance, the date 31/05/2012 becomes 05/07/2014 (wtf?) and I can't understand why. I think your "overridden" stuff is what fixed the behaviour. I hope you'll release it soon.

**Comment by petebacondarwin** [comment]
For now just link to the following file in your application (after the
angular-ui.js file).
https://raw.github.com/angular-ui/angular-ui/master/modules/directives/date/date.js
Pete

**Comment by ghost** [comment]
Thanks, including that file changed the behaviour. I noticed, even in the fiddle, that passing the dateformat to ui.config is redundant. If you comment it out, it still works fine. The date string must match the format specified in the jquery.ui.i18n file as it should.

I noticed, however, a change of behaviour when I render the dates outside the textboxes with ui-date. Without your file they were rendered as I passed them, now they get rendered in the json ISO format, like 2012-08-31T22:00:00.000Z when outputting them with the {{ myVar }} directive. Is that intended?

**Comment by petebacondarwin** [comment]
Yes, this is intended.  We really don't want to be working with strings -
real javascript Date objects are much better.  So by default the date
directive wants the model to be a Date object.  If you pass in a string it
parses it but then converts it to a Date object.  This gives you lots of
power to manipulate the model value as a date but can confuse the first
time user, since the default in angular bindingins is to convert Date
objects to ISO format strings.  You can modify this with the built-in
angular date filter:  http://docs.angularjs.org/api/ng.filter:date .
Pete

**Comment by ghost** [comment]
It's really fine as it is. It's just that I'm used to pass all pre-formatted strings to my html views to simplify i18n management just in case client-side scripting is not enabled. Some cultures use comma for decimals, others use dot. Dates have many formatting styles, etc, so I tend to preformat server-side and pass strings, but your reasoning is sound and very welcome.

**Comment by ghost** [comment]
I've found another problem. I tried to post a date modified by your component. Inspecting the value posted with firebug, I noticed that it's not what I see in the textbox. In fact, it removed the timezone component, meaning that in my textbox I have 31/05/2012 (31 may), it removed 2 hours (here in italy we're actually at +2, one for zone and one for daylight saving  time) and in the posted data I have 30/05/2012 22:00 (10 pm)

I think that's a bug. Or am I missing something?

**Comment by petebacondarwin** [comment]
What exactly did you post?  Is it the Date object?  How is this being
serialized?  I would imagine that it is being serialized into a UTC format.
 You server should then apply the relevant time zone mapping?

**Comment by ghost** [comment]
I'm still struggling with this. I'll try to be as clear as possible.

I'm receiving from the server an object, the date field contains: "2012-05-31T00:00:00" (inspected with firebug, in the console, json data received from the ajax GET) which is, as far as I know, a correct date. When doing:

&lt;input type="text" ng-model="row.myField" ui-date /&gt;

I get this inside the textbox: 10/02/2018 which in italy culture is 10 february 2018 and it's not even close to 31 May 2012

I then tried to change it through the datepicker. I selected 01/03/2017 (1st march 2017) and it appeared correctly in the datepicker. Then made the post. Inspecting the POST data with firebug, the field contains "2017-02-28T23:00:00.000Z" which is 1 hour less what I picked on the datepicker.

I think I'm not doing anything wrong here. I'm never converting from or to string, always using date objects, but the data is wrong both when reading and when posting.

Can you please help me out on this? I'd hate to have to swtich to another framework because this is the only big problem I'm having so far.

**Comment by petebacondarwin** [comment]
If the format you have specified is dd/mm/yy then this must be the format
of the string you pass in. I found that if it doesn't match exactly then
the query datepicker doesn't parse it correctly. You can try this out in
the fiddle I provided.
On the way out the date is a javascript object and by default it will
specialize to a iso string, which you can see is utc 0. Italy is utc 1. So
this is why it looks like this.

Pete
...from my mobile.

**Comment by ghost** [comment]
So basically I should send the dates from the server in a preformatted string matching the culture, and for the writing part I should convert the received data from UTC to local time to make everything right.

**Comment by petebacondarwin** [comment]
Personally, I would transmit dates to and from in is format then create a
date object before adding it to the scope. If you don't have control over
the server and know that what the server wants is fixed then I would do the
formatting manually before sending to the server. In any case this would
done in some request/response interceptor.

Pete
...from my mobile.

**Comment by johannesjo** [comment]
Still no way to configure this in the options??
