### ISSUE TITLE
Add IEShiv and Templates folder to Docs / Demo site

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#195]
There is no mention of the IE Shiv anywhere. I also spoke to the core team and confirmed that it is impossible to introspect the element-level directives for IEShiv so the array must be populated manually. We should provide these instructions to developers. In addition, the IEShiv MUST be loaded synchronously before the rest of the DOM is loaded (namely in the head). This too should be clarified in the docs.

**Comment by dandoyon** [comment]
I'll see about putting some time in this weekend with this

--dan

**Comment by dandoyon** [comment]
I've completed the needful for IEShiv, will do templates later.
