### ISSUE TITLE
datepicker sets date to '1/1/1970' when value is undefined or blank

### ISSUE THREAD

**Issue by sweisman** [angular-ui/angular-ui-OLDREPO#199]
I am using the datepicker widget in a project. It works as expected when a date is set. But if the ng-model date is blank or undefined, the date defaults to '1/1/1970'. Using the jQuery UI widget by itself results in the expected behavior of an empty date. Is this a bug? How can I force a blank date when the source is blank?

**Comment by petebacondarwin** [comment]
Have you tried master?

Pete
...from my mobile.

**Comment by sweisman** [comment]
That fixed it! Thanks.
