### ISSUE TITLE
datepicker escape key question

### ISSUE THREAD

**Issue by sweisman** [angular-ui/angular-ui-OLDREPO#200]
I have a datepicker field that I display on a modal window. I create this modal using plain old jQuery as all the other solutions that I found weren't very satisfactory or easy enough to use.

This adds an escape key exit with this function:

function modal_key(event)
{
        if (event.which == 27)
            modal_hide(modal_id);
}

$('body').bind('keyup', modal_key);

I then unbind() after the escape. However when a datepicker is active and visible, the escape doesn't just close it, but it closes the entire modal window. I added datepicker beforeShow and onClose() functions to remove and add the modal escape key event, but that didn't seem to solve the problem. Can someone help on this?

**Comment by ProLoser** [comment]
You have to stop propagation of the event before it reaches whatever DOM element the modal escape was binded to. If both bind to the body tag then it may be tricky.

**Comment by sweisman** [comment]
It turns out datepicker uses keydown. When I switch my code to use the same, it works!
