### ISSUE TITLE
date filter for datepicker?

### ISSUE THREAD

**Issue by sweisman** [angular-ui/angular-ui-OLDREPO#201]
I have controller that renders dates in two separate controls. The internal format is "yyyy-D-M" (eg 2012-0901). In one place I have "{{item.birth_date | date:'M/d/yyyy'}}". This works great and renders the date the way I want without having to reformat it. In another location I have a datepicker. I can get the widget to work with the internal date format. But I don't know how to change this when rendered. Is there some way to apply a date filter to this widget?

Here is the usage for the datepicker:

&lt;input ui-date="birth_date_options" ng-model="item.birth_date"&gt;

For the static text:

{{item.birth_date | date:'M/d/yyyy'}}

**Comment by sweisman** [comment]
This is a separate question, but I figure it's related. This datepicker is on a popup modal form. The form has a cancel button, but I see that whatever changes are done on the popup are reflected in real time in the static field. First, that's just AWESOME! But second is, I actually don't want that. I want updates to be done after submit or nothing if canceled. Is there an example somewhere of this behavior?

**Comment by petebacondarwin** [comment]
Try copying the value to a different field for the pop up and manually
copying it back across when the pop up is closed.
Pete

**Comment by petebacondarwin** [comment]
Not entirely sure what you are asking here.  Can you make a fiddle or
plunkr to demo it?

**Comment by sweisman** [comment]
I think I'll have the second issue worked out soon. I am more interested in having the datepicker displayed the date the same way as the div with a date filter applied.

**Comment by petebacondarwin** [comment]
OK, so what you are saying is that from the server the dates are coming in
this format, "yyyy-D-M", but that you want to display them in this format,
 "M/d/yyyy"?
What I suggest is that you convert the string from the server into a Date
object at the point of entry, i.e. when you receive the response object -
possibly in a http response interceptor?  Then you can set the format of
the datepicker to whoever you want it to be displayed but the model will
always be a good old Date object.  Then you can set the date filter to
format the Date object who you want it too. Unfortunately the date filter
uses a different set of formatting characters to the datepicker.  One is
provided by the AngularJS library the other is provided by the JQuery UI
library. So you have to have two different formatting strings.  We could
knock up a special uiDate filter that used the $.datepicker.format method
to do the formatting to be more consistent.
Pete

**Comment by alexanderwilms** [comment]
You should be able to give a default format in your config: 
var angularUi = angular.module('MyApp.angularUI', ['ui']);
angularUi.value('ui.config', {
    date: {
        dateFormat: 'dd.mm.yy'
    }
});
