### ISSUE TITLE
Google maps ui icons are garbled

### ISSUE THREAD

**Issue by oborder** [angular-ui/angular-ui-OLDREPO#209]
I am using linux on my desktop and did not check this on the other platforms yet,
but google maps sample has icons for zooming all garbled (except the top circle)..
I have tried in firefox, chrome and opera..

I am not enclosing jsfiddle as it happens with angular-ui maps demo on http://angular-ui.github.com/,
as well as in my app. 

I have uploaded a screenshot at http://postimage.org/image/9pf9ck8vh/.

**Comment by ajoslin** [comment]
Hmm.. I'm not sure about this.   I'll play with it a bit.

**Comment by BrianChapman** [comment]
It's related to Twitter's Bootstap. Place an id="mapCanvas" on the tag containing the ui-map directive and add 

#mapCanvas img {
  max-width: none;
}

to the css and it should be fixed.
