### ISSUE TITLE
Google maps ui TypeError

### ISSUE THREAD

**Issue by jasonkuhrt** [angular-ui/angular-ui-OLDREPO#210]
I'm getting the following error in console, although it seems to be harmless, so far?

```
TypeError: Object function (self, locals) {
      return fn(self, locals, left, right);
    } has no method 'assign'
    at link (http://localhost:3000/lib/client/vendor/angular_ui/angular-ui.js?5a43d6ad35a304f3d2dd33386463aafb0336666e:501:17)
    at nodeLinkFn (http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:4223:13)
    at compositeLinkFn (http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:3838:14)
    at compositeLinkFn (http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:3841:12)
    at compositeLinkFn (http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:3841:12)
    at compositeLinkFn (http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:3841:12)
    at compositeLinkFn (http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:3841:12)
    at http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:3750:30
    at update (http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:13696:11)
    at http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:8002:24 <div style="width:100%;height:400px;" ui-map="ui-map" ui-options="map_options"> angular.js:5526

```

**Comment by ProLoser** [comment]
This stack trace seems like it isn't all gibberish. Try inspecting the code
and stepping through it. What is on line 501 column 17? Put in a breakpoint
just before it and check all the variable values. Sounds like the $parse
might be failing or something (too busy to look at the exact code right
now).

On Wed, Sep 26, 2012 at 7:32 PM, Jason Kuhrt notifications@github.comwrote:

> I'm getting the following error in console, although it seems to be
> harmless, so far?
> 
> TypeError: Object function (self, locals) {
>       return fn(self, locals, left, right);
>     } has no method 'assign'
>     at link (http://localhost:3000/lib/client/vendor/angular_ui/angular-ui.js?5a43d6ad35a304f3d2dd33386463aafb0336666e:501:17)
>     at nodeLinkFn (http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:4223:13)
>     at compositeLinkFn (http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:3838:14)
>     at compositeLinkFn (http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:3841:12)
>     at compositeLinkFn (http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:3841:12)
>     at compositeLinkFn (http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:3841:12)
>     at compositeLinkFn (http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:3841:12)
>     at http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:3750:30
>     at update (http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:13696:11)
>     at http://localhost:3000/packages/jasonkuhrt_angularjs/angular.js?35be6af770f839570a813807489abf57785cedf9:8002:24 <div style="width:100%;height:400px;" ui-map="ui-map" ui-options="map_options"> angular.js:5526
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/210.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by petebacondarwin** [comment]
Sounds like you are putting a non assignable expression into ng-model or
other attribute.

Pete
...from my mobile.
