### ISSUE TITLE
Sortable breaks the model

### ISSUE THREAD

**Issue by OwlyCode** [angular-ui/angular-ui-OLDREPO#211]
Hi!

When applying sortable to a list, I tried to take the last element and bring it up to the top. It results in a blank element appearing in the list.

I looked into the code, maybe the onUpdate function has a bug?

``` javascript
onUpdate = function(e, ui) {
   var end, start;
   start = ui.item.data('ui-sortable-start');
   end = ui.item.index();
   ngModel.$modelValue.splice(end, 0, ngModel.$modelValue.splice(start, 1)[0]);
   return scope.$apply();
};
```

**Comment by OwlyCode** [comment]
I found my problem. But it's a bit ambiguous. 
1. My model was an array of 3 items. 
2. The sortable had 4 items in it, 1 hardcoded and fixed, 3 draggable from a loop on the model.

I took out the fixed one, everything works fine. The indexes of the starting and ending of the drag and drops were falsified by this extra item. Even by adding this:

``` javascript
module.value('ui.config', {
    sortable:{
        items: ".movable",
        handle: ".handle",
        axis: 'y'
    }
});
```

**Comment by ProLoser** [comment]
I'm closing this. If people want us to explicitly support both static and dynamic items they can open a new issue. Sorry it took 4 months for me to respond to this lol

**Comment by ProLoser** [comment]
PS: if you're still paying attention, and would like us to tackle this issue feel free to add a comment and I will reopen.

**Comment by OwlyCode** [comment]
It's OK. My problem was solved by actually removing the fixed element in the list. But as I'm probably not the only one to experiment this, maybe looking if a fix is needed could be great.

I'll create a sample which reproduces it this evening.

**Comment by ProLoser** [comment]
I understand the use case that created the issue. However, I would imagine trying to solve this raises new question:

What object should I put into the model that represents the static items?

Frankly, it's easier just to tell people they must use dynamic items only, but I suppose someone might want an entirely fixed list too. I'll have to review the code some more to see if it's been hardcoded to ng-repeat  

## 

Dean Sofer
DeanSofer.com
714.900.2254

**Comment by OwlyCode** [comment]
It's not a common problem. The best example for me is if you want a categorized list with separators. It's a single big list with fixed items that delimitates sections. But maybe considering this as one big list is a mistake and there is another way I can't figure at the moment to design it. I'm quite inexperienced at angular. In my case, the problem was not blocking as a change to the design "solved" the problem without writing something complicated or hard to maintain.

To make it simple, for me we can consider implementing this feature useless if there is another simple way to do it.

**Comment by ProLoser** [comment]
Actually, I think if you create indexes in the array that mirror the statically placed nodes it should work perfectly:

``` html
<script>
$scope.items = ['One', 'Two'];
</script>
<ul ng-model="items" ui-sortable>
  <li>First</li>
  <li>Second</li>
</ul>
```

I was going to do a mixed version but I can't figure out how to NOT make it complicated...
