### ISSUE TITLE
Date directive: element.datepicker doesn't work

### ISSUE THREAD

**Issue by frapontillo** [angular-ui/angular-ui-OLDREPO#213]
I'm using the latest version of anything: jQuery 1.8.2, jQueryUI 1.8.24 and Angular 1.0.2. Still, I'm having some issues with the `date` directive. The directive uses:

``` javascript
element.datepicker
```

to initialize the jQuery UI widget, but the Chrome console says "Object [[object HTMLDivElement]] has no method 'datepicker'".
If I change the directive so that it uses:

``` javascript
S(element).datepicker
```

everything works. So, is there anything wrong that I'm doing or was there some update that broke the expected behavior?

**Comment by pkozlowski-opensource** [comment]
Could you try to share a jsFiddle / plunk? 
I've answered a similar question on SO recently: http://stackoverflow.com/questions/12472244/how-to-integrate-angularui-to-angularjs/12474114#12474114

There is a jsFiddle in the answer that you can use as a starting point.

**Comment by frapontillo** [comment]
I have changed the jQuery plugin from 1.7.1 to 1.8.2 (which is the latest version) and I was able to replicate the behavior described in my first post: http://jsfiddle.net/frapontillo/reRPY/ .
I am submitting a pull request with the fix (compiled and tested too).

**Comment by frapontillo** [comment]
I have been able to sort it out: I was referencing Angular.js before jQuery. So the element was a regular HTML element and not a jQuery one, I suppose.

**Comment by petebacondarwin** [comment]
Actually element was a jqLite object - AngularJS implementation of JQuery)
used when JQuery is not found.
