### ISSUE TITLE
select2 doesn't watch options repeated using data-ng-repeat

### ISSUE THREAD

**Issue by PeteAppleton** [angular-ui/angular-ui-OLDREPO#215]
If the select2 directive is used with a repeating set of options using the Angular data-ng-repeat flavour of the ngRepeat directive then it doesn't watch changes to the model and consequently doesn't operate correctly - for example, using

<option value="{{opt.id}}" ng-repeat="opt in options">{{opt.name}}</option>

behaves as expected, but

<option value="{{opt.id}}" data-ng-repeat="opt in options">{{opt.name}}</option>

doesn't.  This is because the jQuery selector in the compile function is coded to look for an 'ng-repeat' attribute.

The partial diff below corrects the issue in my environment - apologies, it's created against a subset of the Angular UI code.

```
            // Enable watching of the options dataset if in use
            if (tElm.is('select')) {
-               repeatOption = tElm.find('option[ng-repeat]');
+               repeatOption = tElm.find('option[ng-repeat], option[data-ng-repeat]');
                if (repeatOption.length) {
-                   watch = repeatOption.attr('ng-repeat').split(' ').pop();
+                   watch = (repeatOption.attr('ng-repeat') || repeatOption.attr('data-ng-repeat')).split(' ').pop();
```

Thanks, and thanks for the library :)

Pete

**Comment by ProLoser** [comment]
Your 2 examples are identical.

Also this: https://github.com/angular-ui/angular-ui/blob/master/modules/directives/select2/select2.js#L21

But I realized a few days ago that this breaks when used with filters

**Comment by ProLoser** [comment]
Ah nvm I should finish reading everything you put down before jumping to conclusions lol.

**Comment by ProLoser** [comment]
Can you create a branch on your fork and open a PR? I can't find your commits in the tree. **Remember** to _not_ commit the updated build files.

**Comment by PeteAppleton** [comment]
Sure, no problem - will do tomorrow as about to pack in for the day now.  Thanks :)
