### ISSUE TITLE
Angular-ui Select2 with multiple selection

### ISSUE THREAD

**Issue by Codier** [angular-ui/angular-ui-OLDREPO#218]
It seems that the multiple selection functionality of Select2 is not available in Angular-ui Select2 widget? Or I just don't know how to do it. 

I have an array as local data. I want to enable multiple selection. How do I do that?
Thanks!

**Comment by ProLoser** [comment]
You must use a `<input multiple>` (or `multiple:true`). If you provide a fiddle or something to look at it would better help us help you. We're not all psychic :)

**Comment by Codier** [comment]
Hi I am really sorry for the late reply! It seems that github does not give me notification for this thread. I have figured it out. sorry for the trouble!
