### ISSUE TITLE
LazyLoader for assets

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#22]
I am currently researching how to lazy load javascript (and potentially css) files into my page. If this isn't natively supported by angular, but a helper approach is developed, this would definitely be something to throw into the project.

Worth checking out: https://github.com/cmelion/angular-yepnope
However I would personally prefer a solution with 0 dependencies

**Comment by ajoslin** [comment]
Look at what angular-seed uses https://github.com/angular/angular-seed/blob/master/app/index-async.html

**Comment by ProLoser** [comment]
Spoke to the core team many many months ago. Since angular requires ALL modules to be loaded up front they don't really advocate the use of a lazy-loader.
