### ISSUE TITLE
CodeMirror directive sensitive to line endings

### ISSUE THREAD

**Issue by akimball** [angular-ui/angular-ui-OLDREPO#222]
The CodeMirror directive has code to [only update the model if the value has changed](https://github.com/angular-ui/angular-ui/blob/master/modules/directives/codemirror/codemirror.js#L24), but this does not work on first change if the source code has CRLF as line endings. This then causes the [little problem](https://github.com/angular-ui/angular-ui/blob/master/modules/directives/codemirror/codemirror.js#L22) to occur

**Comment by ProLoser** [comment]
Need to verify if this still occurs...

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-codemirror (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-codemirror

Please reopen this issue there if it is still relevant.
