### ISSUE TITLE
Multiple jQuery UI widgets in Passthrough

### ISSUE THREAD

**Issue by DavidSouther** [angular-ui/angular-ui-OLDREPO#223]
ui-jq doesn't allow for multiple jQuery UI calls on a single element. It is thus impossible to, say, have an element that is both resizable and draggable using ui-jq alone (rather than adding the funtionality in ::link

http://jsfiddle.net/southerd/bzgSM/

**Comment by ProLoser** [comment]
Okay, we COULD add support for this, but honestly wouldn't you want way
more configuration when using draggable and resizeable? Plus this
introduces some new questions such as execution order, or more importantly,
how do we pass options for each respective function?

**Comment by DavidSouther** [comment]
The least invasive approach would, I think, be allowing the 4th or 5th syntaxes from the fiddle (comma or space separated). Execution order is left to right. `ui-options` would then be treated as a JSON string, wrapping it in `[ ]` and passing each object in the array to the function at the same instance. 

EG: 

``` HTML
<div ui-jq="resizable, draggable" ui-options="{handles: 'e'}, {}">
    <p>It could do both!</p>
</div>
```

**Comment by dandoyon** [comment]
I saw your prior question and was thinking the same thing.  If you can add a feature request on github with your example, that would be great

thanks for using angular-ui

--dan

**Comment by DavidSouther** [comment]
dandoyon, I thought this thread was a feature request? Or should I re-tag it on GitHub? If so, as what?

**Comment by dandoyon** [comment]
Googlegroup is more for discussion , I'll put it in github 

No worries 

-- dan

**Comment by dandoyon** [comment]
I'm an idiot, put it down to lack of sleep, I thought this thread came through the googlegroup.... this is the right place.

**Comment by ProLoser** [comment]
May need some votes on this. No one actually KNOWS this but I actually already use multiple arguments in uiOptions in the (semi unlikely) event that the plugin takes multiple parameters, it actually takes all your parameters (separated by comma) and passes all of them to the jQuery plugin.

Of course since no one is probably using this feature you would not be losing anything. I suppose I could also just disable this feature when using multiple plugins...

**Comment by ProLoser** [comment]
This project is discontinued. Please reopen this issue on angular-ui/ui-utils if it's still relevant.
