### ISSUE TITLE
ui-keypress issues

### ISSUE THREAD

**Issue by ssbanerje** [angular-ui/angular-ui-OLDREPO#226]
Hi,
I am running into some problems using the keypress as follows-

``` html
<div ng-controller="GBNController">
...
<input id="search-field" type="text" placeholder="JSON Query" ng-model="queryText" ui-keypress="{enter: foo()}"/>
...
</div>
```

and my javascript has - 

``` javascript
var AngApp = angular.module('gbn', ['ui']);
var GBNController = function($scope) {
    $scope.queryText = '';
    $scope.foo = function() {
        alert('test');
    }
};

```

Now this function foo is called only when the document is loaded and then after that, the `return` keypress event in the text field is never handled.

I am using the current [head](https://github.com/angular-ui/angular-ui/tree/1d831cdf891dcbe9c1c2e7d95cd5c17f2b97fe69) of the master branch.

Am I doing something wrong here, or is this broken??

**Comment by ssbanerje** [comment]
I managed to fix it.... 
I had to pass the callback as a string!

```
ui-keypress="{enter: 'foo()'}"
```

**Comment by ProLoser** [comment]
Ah yes sorry if that was not clear. Perhaps you can add a note to the demo
Page to point it out as a pull request?
