### ISSUE TITLE
angular ui , lastest angular version

### ISSUE THREAD

**Issue by gkielwasser** [angular-ui/angular-ui-OLDREPO#23]
hi,
I have tried to update angular version to the latest version but angular-ui module doesn't work anymore. 
I'm encountering the problem with the ui-date directive. It is due to the change of isolate scope bindings definition.

Thanks

**Comment by dandoyon** [comment]
This is on our radar, there was a big change in how isolate scope in directives was done between the RC and the final version.

**Comment by ProLoser** [comment]
Closing this as we are now on v1.0.1. Feel free to comment and we will reopen this issue if you encounter any further problems, or simply create a new ticket.
