### ISSUE TITLE
Select2 Multiple prevent sorting?

### ISSUE THREAD

**Issue by gaiottino** [angular-ui/angular-ui-OLDREPO#233]
Hi,

I'm using the Select2 directive as follows

``` html
<select ui-select2 multiple ng-model="things">
  <option ng-repeat="thins in available_things" ng-value="thing">{{thing}}</option>
</select>
```

The problem I have is that the directive seems to order the resulting "things" each time I select a thing but the order in which I select things is important to me. 

This is not how Select2 behaves normally and I can't find what's causing this. Would appreciate some insight in how to fix this. "things" is just an array of strings.

**Comment by ProLoser** [comment]
Does this PR address your issue? https://github.com/angular-ui/angular-ui/pull/229

**Comment by gaiottino** [comment]
No. A filter won't help me as I want to keep the original order.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-select2 (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-select2

Please reopen this issue there if it is still relevant.
