### ISSUE TITLE
delaying map initialization until mapOptions exist

### ISSUE THREAD

**Issue by bennlich** [angular-ui/angular-ui-OLDREPO#234]
Hey--just started using the ui-map directive. I was thinking it might be nice to delay the map initialization until some non-null map options are present. This way you could load map options asynchronously.

Currently, I'm initializing the map at some arbitrary (lat, lon), and panning it when I get the real coords, but it'd be nice to just wait to initialize until the coords come in (which is what I did prior to switching to angular-ui).

I'm willing to work on this but want to see if others think it's a good idea / have suggestions for how to approach it. Would the right idea be to make the ui-map directive $watch the ui-options and bind the map initialization to their presence?

**Comment by ajoslin** [comment]
Hi bennlich,

This would be really easy with `ui-if`.

``` html
<div ui-if="myCondition()">
  <div ui-map="hello" ui-options="myoptions">
  </div>
</div>
```

**Comment by bennlich** [comment]
Oh! Cool. Thanks!
