### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by jevonearth** [angular-ui/angular-ui-OLDREPO#238]
Feature request to offer multipart file upload. Ideally multi file upload, supporting drag/drop, progress bar, and with iframe fall-back support for IE.

Perhaps base it on https://github.com/blueimp/jQuery-File-Upload

**Comment by SeyZ** [comment]
+1

**Comment by wesleycho** [comment]
This repository is discontinued - if you would like to make this a new feature, I would recommend opening up the request issue in the `angular-ui/ui-utils` repository.

**Comment by joseym** [comment]
https://github.com/blueimp/jQuery-File-Upload already has an angular module: https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload-angular.js
