### ISSUE TITLE
Changing options in controller doesn't update view

### ISSUE THREAD

**Issue by twoolworth** [angular-ui/angular-ui-OLDREPO#24]
If you need to change the dateOptions later on based on say a ng-change event from a select it doesn't update the views date picker with the new options. I have a condition that depending on what select option you chose it restricts what days are available to select in the date picker. If I have the restriction in the beginning it works. applying it later within the controllers change handler doesn't work..

My basic controller code:

``` javascript
$scope.startDateOptions = {minDate: 0};

$scope.unavailableDates = [
        "2012/01/29","2012/01/30","2012/01/31",
        "2012/02/29","2012/02/29",
        "2012/03/29","2012/03/30","2012/03/31",
        "2012/04/29","2012/04/30",
        "2012/05/29","2012/05/30","2012/05/31",
        "2012/06/29","2012/06/30",
        "2012/07/29","2012/07/30","2012/07/31",
        "2012/08/29","2012/08/30","2012/08/31",
        "2012/09/29","2012/09/30",
        "2012/10/29","2012/10/30","2012/10/31",
        "2012/11/29","2012/11/30",
        "2012/12/29","2012/12/30","2012/12/31"
    ]; // yyyy/MM/dd

    $scope.unavailableDays = ["Saturday","Sunday"];

    $scope.unavailable = function(date) {
        $scope.ymd = date.getFullYear() + "/" + ("0"+(date.getMonth()+1)).slice(-2) + "/" + ("0"+date.getDate()).slice(-2);
        $scope.day = new Date($scope.ymd).getDay();
        if ($.inArray($scope.ymd, $scope.unavailableDates) < 0 && $.inArray($scope.days[$scope.day], $scope.unavailableDays) < 0) {
            return [true, "enabled"];
        } else {
            return [false,"disabled"];
        }
    }

$scope.selectedFrequencyChanged = function() {
        $scope.showDayOfWeek = angular.equals($scope.selectedFrequency.value, "weekly");

        $scope.startDateOptions = {minDate: 0, beforeShowDay:$scope.unavailable};
    }
```

Here is the select dispatching the change event:

``` javascript
<select id="input_frequency" ng-model="selectedFrequency" ng-options="f.frequency for f in frequencies" ng-change="selectedFrequencyChanged()" class="span2"></select>
```

Here is the input I'm using within the view:

``` javascript
<input ui-date="startDateOptions" id="startdate" type="text" ng-model="service.startdate" value="{{service.startdate}}" class="span3">
```

Am I just missing something?

**Comment by dandoyon** [comment]
We'll take a look

**Comment by petebacondarwin** [comment]
Yes the directive is not watching the options attribute.  This is straightforward to change but I have no time till the start of July.

**Comment by dandoyon** [comment]
No worries, I assigned it, more as a PR move to keep people interested. 

I'm going to be more active now, so there will be more activity and notifications. 

--Dan

**Comment by ProLoser** [comment]
Has this been addressed in the latest revisions?

**Comment by sajal** [comment]
friendly bump :)

I am already using the date widget in one place where I need to select a single date, the original idea was to populate the mindate and maxdate using ajax, but since those cant be set dynamically, I can set pass those along within the page's html. Id love to be able to change them later using ajax.

However, now I need to select a date range based off ( http://jqueryui.com/demos/datepicker/date-range.html ) .
Here the maxdate of the first box is dynamically set if a date is selected in the second box, and vice-versa. The only way to do this currently would be to deal with jquery-ui directly, which i really want to avoid.

Is there any chance this can get prioritized?

I see the original source if in coffee script, I will try converting it to .js and see if I can make it work but its unlikely given my limited knowledge of angular.

**Comment by dandoyon** [comment]
Salal, here is the generated javascript from our build process git://gist.github.com/3342707.git. If you have success, I can migrate into coffeescript.  If you are struggling, just get back to us and we'll take a look. Pete is offline for this month but someone else will. Sorry this has lapsed

--dan

**Comment by petebacondarwin** [comment]
I started to look at this then went off on holiday. I will get on it in
Sept.

Pete
...from my mobile.

**Comment by sajal** [comment]
Hi Dan,

I think i got it to work. http://jsfiddle.net/sajal/Whzh5/3/ 

Basically I added this before the last return statement:-

```
          scope.$watch(attrs.uiDate, function(options){
              Object.keys(options).forEach(function(o){
                  element.datepicker( "option", o, options[o] )
              })
          }, true);
```

I have no idea if this is the correct method.

This is what jquery-ui has to say about it

```
//getter
var minDate = $( ".selector" ).datepicker( "option", "minDate" );
//setter
$( ".selector" ).datepicker( "option", "minDate", new Date(2007, 1 - 1, 1) );
```

**Comment by sajal** [comment]
https://gist.github.com/3342925 the updated script

**Comment by petebacondarwin** [comment]
I started to look at this then went off on holiday.

Pete
...from my mobile.

**Comment by dandoyon** [comment]
Great, I'll take a look later

**Comment by dandoyon** [comment]
Sajal,

I've take a look at diff, the one thing that I will need to discuss with other devs is use of Object.keys, if not mistaken this is a recent ECMA script addition. 

-dan

**Comment by dandoyon** [comment]
Object.keys is an ECMA 5 construct and is not compatible with IE8, old FF, Opera 11.5. For this code you've done, I may use a polyfill instead, but it does put a fire under my feet to add a polyfill lib for angular-ui uses. 

http://kangax.github.com/es5-compat-table/

**Comment by sajal** [comment]
aha.. didn't realize Object.keys is so new... For the application I am building, it would have only a handful of users and old browser support is not a requirement... So I will override the directive until angular-ui comes up with a more elegant solution :)

I have been using Object.keys all over the place...

**Comment by dandoyon** [comment]
here's a polyfill I found, https://gist.github.com/1034464 its not 100% ES5 compatible but I may pull it in and tweak.

**Comment by jameswyse** [comment]
You could just do it with jQuery, not sure what the performance is like though compared to native Object.keys.

`var keysArray = $.map(options, function(value, key) { return key; });`

Object.keys is probably in underscore.js too.

**Comment by dandoyon** [comment]
cool thanks

**Comment by petebacondarwin** [comment]
As you can see github has very cleverly seen that I have generated a pull request to fix this.
Please take a look.  It basically uses the same strategy as James suggested but is written in coffeescript using its

```
for own key,value in object
```

construct, which is nice and doesn't rely on ECMA 5, polyfills or jquery.

The one downside to this approach is that it doesn't pick up deleted options.  E.g. if you remove a field from the options object, the watch is triggered but the date widget does not have that option removed and returned to its default value.

Is this a problem?  I had tried to overcome this by recreating the date widget each time but it was fiddly and not very nice.  Another option would be to store and compare the previous options each time?

**Comment by sajal** [comment]
Deleted options is not a problem for me. I don't see a case where i would need to delete an option. If i had to do it id just set that option to jquery datepickers default.

(unrelated) i just realized... I should be using `for (key in object) { ... }` everywhere... instead of getting `Object.keys()` and looping thru it..

**Comment by boneskull** [comment]
You may want to consider using angular.forEach(); with the "key in object" syntax you will have to deal with all of the keys up the prototype chain.
