### ISSUE TITLE
Tooltip (ui-jq="tooltip") doesn't disappear on ng-view change

### ISSUE THREAD

**Issue by herrerodani** [angular-ui/angular-ui-OLDREPO#241]
Hello, 
I have
a href="/products" title="Easiest. Binding. Ever!" ui-jq="tooltip">Hover over me for static Tooltip</a>
in my page. When I click this link, a ng-view refresh is done, but the tooltip keeps in place.

Thank you very much.

**Comment by ProLoser** [comment]
I have had this happen outside of angular with the native tooltip. I don't
really have a good suggestion on how to fix it. It might be helpful to open
this bug ticket on the Bootstrap repo instead, as it occurs any time you
remove or hide a DOM element that created the tooltip.

On Wed, Oct 24, 2012 at 6:45 AM, herrerodani notifications@github.comwrote:

> Hello,
> I have
> Hover over me for static Tooltip http://products
> in my page. When I click this link, a ng-view refresh is done, but the
> tooltip keeps in place.
> 
> Thank you very much.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/241.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser
