### ISSUE TITLE
Using a layout manager in angular?

### ISSUE THREAD

**Issue by dkorz** [angular-ui/angular-ui-OLDREPO#246]
I've gotten to a point where I need to layout beyond what can be done in CSS. The jquery ui layout plugin does what I need at least for now. I'm looking for some direction on how to do this.

Should I try the jquery plugin wrapper or should I make a directive wrapping this myself? I'm trying mightily to not reinvent the wheel by writing a directive from scratch although that might result in a better angular solution. 

Is a layout manager something that angular-ui would accept?

Any guidance will be appreciated!

**Comment by ProLoser** [comment]
What is it you want to accomplish?

**Comment by dkorz** [comment]
I would like to be able to add markup in a partial or a directive's
template that controls the layout of child elements. I have panels that
contain fixed sized areas for titles, toolbars, etc. with another area that
should take the rest of the space. In some cases the fixed size areas need
to be adjustable with a splitter after display with an initial width (or
height) like 10em or 20%. A "border layout manager" lets me use a class
name, attiribute, or element name to create north, south, east, west, and
center sections where the center div gets whatever is left over from the
other divs as well as putting the other four divs in the right place.

In Dojo I used a BorderContainer. It looks like the jquery-ui layout
manager provides similar capabilities but I think the plugin code should be
wrapped into a directive when using angular but I'm not certain.

**Comment by ProLoser** [comment]
Ya I would probably not recommend using a third party plugin for something
like this because it would a: be way easier to do in vanilla angular and b:
just seems like awkward design to me.  Are you just hiding and relocating
content? I mean asside from the moveable dividers, I don't really get the
main advantage of using a plugin for layout. You could do everything you
described (minus the panel toggles/dragging) with pure css, and the rest
could be done fairly easily with angular.

**Comment by dkorz** [comment]
Well ignoring the splitter feature for a moment what I was trying to
describe is a kind a "stretchy" design that can't be done just with CSS. As
a more concrete example I have a widget to show a list of items. The widget
will be placed inside a div whose height will vary, say it's 50% of the
window. The list widget has a div containing a title that has a height of
2em and another div with a list of links also 2em. The last div should use
the remainder of the space. It contains ng-repeat elements and has overflow
auto so it will scroll. All the available space should be used. Without
javascript to initially size and handle resize events how do I size the
third div's height? There's no way in CSS to say 100% - 4em. It's also
harder than this because the links elements can wrap making the second div
2 or 4em in height.

I don't think this is an unusual problem design. Pretty much all the
frameworks that try to support "desktop like" layout have a layout manager
class, e.g. ExtJS.  I'm doing this type of sizing already in one directive
and <shame>a couple controllers</shame> but it feels like it should be a
directive in angular so the common code can be re-used.

**Comment by yarsh** [comment]
@dkorz - Did you ever solve this issue - I too find myself needing the functionality provided by the jQuery UI Layout plugin...

**Comment by dkorz** [comment]
No, we extended a few custom directives to handle the space filling where
it hurt the most and deferred the splitter feature. :(

**Comment by ajoslin** [comment]
Have you heard of angular layout directive? https://github.com/rur/angular-layout-directive

It hasn't been updated for awhile, but you could give it a look :-)

**Comment by ProLoser** [comment]
@ajoslin i think that project is closer to a router than a layout directive.

@dkorz I rewrote `ui-jq` to defer execution until children have been linked specifically to tackle this sort of issue. We have messed around with using layout managers at my company, and although it's not perfect is IS possible. I just don't think it's the right direction to go in when it can be avoided.

In fact, we are going with [CSS flexbox](https://github.com/ProLoser/Flexbox.less/) instead and will be handling the toggling/resizing behaviors manually. However we are fortunate in that we can target newer browsers.

**Comment by yarsh** [comment]
Thanks.  Do you by chance know of a place to get a sample angular js app
for login/ authentication?  It seems there should be one out there but I
can't find one and implementing it from scratch seems like a waste of time
(I love how Meteor lets you get that using one command but Meteor just
seems too immature to start building a real life web app with it).

**Comment by ProLoser** [comment]
Woulda liked this guy to merge the project into ui: https://github.com/witoldsz/angular-http-auth

**Comment by panpur** [comment]
I think someone has implemented directive for layout:
http://lorenzofox3.github.io/flexy-layout/src/index.html

But I would love to also have this feature in Angular UI in case the above link is no longer supported in the future.

**Comment by daniel-halldorsson** [comment]
There is now a layout plugin in angular-ui (ui-layout) needs more docs and functionality though, it is very basic.
https://github.com/angular-ui/ui-layout
