### ISSUE TITLE
v0.3.1 patch

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#248]
I'm going to be focusing on #197, #198 and #204 tonight and will try to push a patch with merges.

The first two are two identical alternative approaches to the same thing, and unfortunately I'm not exactly sure which one to choose.

I am also going to try to get the async unit tests I started for TinyMCE and Select2 working.

I will be working on the build server too so that we can improve our process.

**Comment by ProLoser** [comment]
I pushed some rebuilt files that contain our fix from the merge with dan. For some reason the tests are failing despite working locally. No idea why.

**Comment by pkozlowski-opensource** [comment]
It is not about tests, it is Travis-CI failing on `npm install`... Suspecting Travis issues...

**Comment by ProLoser** [comment]
I was getting the same error at work which is why I had to wait till I got
home to build. Need to check the package file for errors.
