### ISSUE TITLE
Code review of uiCurrency

### ISSUE THREAD

**Issue by dandoyon** [angular-ui/angular-ui-OLDREPO#25]
Finally finding time to start contributing, please take a look at module.  Until we get squared away with our approach 
to 1.0 production version, I did a bit of shenanigans so I didn't have to fix existing code. If its ok, i'll do a pull request.  
I need to do a bit more on readme.

https://github.com/dandoyon/angular-ui/tree/d1853c59ead94038e67f5ebfedc80be8e4178604/modules/directives/currency

Any comments, suggestions are appreciated

--dan

**Comment by ProLoser** [comment]
If you can throw a demo on the angular-ui.github.com project to confirm it works, I wish i had more time to be more thorough (with tests and everything). I'm a little confused honestly how to go about testing directives in all honesty.

I'm very behind schedule with my job but I do sincerely intend to update all my of directives and luckily my job DOES ensure they at the very least function properly lol.

I actually keep the entire unminified file in my project at work so that I can ensure things don't fubar.

**Comment by dandoyon** [comment]
will do thanks for looking

**Comment by ProLoser** [comment]
Hey Dan, I'm not sure exactly where `controllerOptions` are coming from but perhaps you should try using `ui.config` instead? I find it to be the most intuitive to use, but anyone is free to disagree with me on that point.

The Select2 directive has a good example of the logic I use for extending the `ui.config` as set of default options. Also, I declare an empty `ui.config` inside the module declarations at the beginning of AngularUI so it is safe to assume to the object exists, and when users redeclare this variable in their module it simply overrides our empty declaration.

**Comment by dandoyon** [comment]
Thanks for for the code review Dean. I took a bit of a holiday from angular. Will definitely look at your ui:options code. Best to be consistent. 

Not sure if I'll get to meetup tomorrow.

--dan

**Comment by dandoyon** [comment]
Dean looking at uiSelect2 code (trunk)

I see this 
         opts = angular.extend({}, options, scope.$eval(attrs.uiSelect2));
but was expecting
         opts = angular.extend({}, options, scope.$eval(attrs.uiOptions));

am I missing something? Bug?
BTW, i think this is awesome way of handling default configs for angular-ui.

**Comment by ProLoser** [comment]
I use uiOptions for the ui-jq directive because the primary expression
(uiJq) is already being used to specify the name of the plugin. However for
Select2 I simply allow you to pass options directly as the expression.

On Sun, Jul 8, 2012 at 9:40 PM, dandoyon <
reply@reply.github.com

**Comment by ProLoser** [comment]
Closing this since the refactor is now merged
