### ISSUE TITLE
uiKeypress stopped working

### ISSUE THREAD

**Issue by hparra** [angular-ui/angular-ui-OLDREPO#254]
Binding uiKeypress stopped working as usual with 0eac4de11d8cd5d9777df43adaa74c1f3c91ec1c

All tests pass.

Binding events to body. Not sure if this is a jQuery issue. Ideas?

**Comment by ProLoser** [comment]
This seems to work for me. Can you create a fiddle or plnk or paste what you are doing?

**Comment by hparra** [comment]
It's hard since I'm binding listeners to BODY but this is a non-issue now. I was using the wrong listener ("keypress" instead of "keydown") as defined by http://www.quirksmode.org/dom/events/keys.html. For some reason "keypress" was working in a pre 0eac4de version. Correction of behavior is probably a side effect of afd83b7b371ce118d6e0647228f6fbec26655372. Thanks. HGPA
