### ISSUE TITLE
Create a directive for a form wizard

### ISSUE THREAD

**Issue by tadchristiansen** [angular-ui/angular-ui-OLDREPO#258]
There are a ton of plugins for creating a form wizard. It seems like, with AngularJS, you would be able to create a cool directive that has this functionality. I came to angular-ui looking for something like this and didn't see anything. Is this in the works? Are there plans for doing something like this? If not, I may just make an attempt of it on my own and share it with you guys. I just didn't want to reinvent the wheel.

**Comment by ProLoser** [comment]
Uh... You can create one if you want to? With the power of AngularJS natively, I don't really see a large benefit in creating a specific directive. Seems like it would just add more obfuscation/complexity rather than simplicity.

What would the directive even do for you?

P.S.

I worked on a form wizard for CakePHP, so it's not to say I have 0 experience with that sort of interaction. However the big reasons for having the wizard there are not present in an AngularJS environment.

**Comment by tadchristiansen** [comment]
First off, you are completely right. For whatever reason I thought the jq-ui stuff wouldn't work. I just tried it and it works fine. 

As for having the wizard or not, I totally agree. Our designer feels that he does not want to overwhelm the user with tons of questions and wants to gradually lead them through all the questions. I am not a big fan of it myself.

Sorry for taking your time on this one, I should have realized the jq-ui pass through was all I needed.

**Comment by tadchristiansen** [comment]
I have a question, and since you have some experience with this I was wondering if you could answer it: http://stackoverflow.com/questions/13289704/how-can-i-get-formwizard-with-steps-inside-directives-with-angular-ui-jquery-pas

I tried posting it here but had formatting issues.

**Comment by tadchristiansen** [comment]
Thinking about it some more, maybe I should just ditch the formwizard and just use ngSwitch.

**Comment by ProLoser** [comment]
That is sort of what I was saying in the first place lol. Or you can use
ng-include with a variable

**Comment by tadchristiansen** [comment]
Rereading you first post I see what you are saying. I thought you were saying that there was no reason for a directive. Not that there was no reason to use the plugin at all. I realize now that you were saying there is no need for the formwizard at all. 

What are some of the reasons I would use ng-include over ng-switch? It seems to me ng-switch will be easier to work with but I am still fairly new to angularJS.

**Comment by ProLoser** [comment]
Sorry mistake on my part, I was thinking about ng-view not ng-switch.
Ng-include lets you throw the contents of each step into its own partial,
and I think it would be safer to put controllers in each partial.
If your logic is not that big you could just not put ng-controller in the
partials or if the html is not that big you can just use switch.

**Comment by tadchristiansen** [comment]
Interesting. Thanks for the information. Right now I have all of the steps using the same controller because I have a step1, step2, step3, and then step4 is a review of steps 1, 2, and 3. This way all the steps share the same scope. I think I remember seeing a way to have the contollers share scope but the way I have it seems more straight forward to me (not that I am an expert or anything). Thanks again for taking the time to answer my questions. I am sure they seem so simple to you :).
