### ISSUE TITLE
No compatible version found: grunt-recess@'>=0.1.3- <0.2.0-' 

### ISSUE THREAD

**Issue by ghost** [angular-ui/angular-ui-OLDREPO#260]
<code>
npm ERR! Error: No compatible version found: grunt-recess@'>=0.1.3- <0.2.0-'
npm ERR! Valid install targets:
npm ERR! ["0.1.0"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR!     at next_ (/usr/share/npm/lib/cache.js:438:17)
npm ERR!     at next (/usr/share/npm/lib/cache.js:415:44)
npm ERR!     at /usr/share/npm/lib/cache.js:408:5
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/cornihilio/src/b2bcm/angular-ui/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.5.0-18-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/cornihilio/src/test/angular-ui
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: grunt-recess@'>=0.1.3- <0.2.0-'
npm ERR! message Valid install targets:
npm ERR! message ["0.1.0"]
npm http 304 https://registry.npmjs.org/async
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/cornihilio/src/test/angular-ui/npm-debug.log
npm not ok
</code>

**Comment by ProLoser** [comment]
Just tested npm install with the latest from master and it worked fine for me. Are you on the latest? grunt-recess was recently updated.
