### ISSUE TITLE
Issue/Need help using ui-if with validation in AngularJS and Angular-UI

### ISSUE THREAD

**Issue by jigneshjdesai** [angular-ui/angular-ui-OLDREPO#261]
Greetings folks,

I am trying to use ui-if directive to remove/add control for “Callback Date” on the selection of specific item from the drop down in my app. That is working fine. I have also added validation for required fields using AngularJS validation. The dynamic control “Callback Date” is required field if present on the screen and that control is added to the DOM using ui-if when user selects “Callback” from the “Disposition” dropdown and removed if user selects any other value. I have Save button which I am disabling using the form.$invalid. It seems to be working fine except for one scenario. The scenario goes like this, user selected “Callback” in Disposition dropdown >> app added “Callback Date” control to the DOM and probably to the Form’s control collection >> user, without entering anything in the “Callback Date” changes the value of Disposition dropdown. >> app removed the “Callback Date” control. After this, save button will stay disabled even if all the required controls have values filled. I think even after the ui-if removed control from the DOM, but I think it is somehow staying in Form’s control collection with $invalid state.

Can you guys please help me fix this issue? Below is the fiddle I have created with this functionality. 

http://jsfiddle.net/jigneshjdesai/JhYph/10/

Many Thanks,

Jignesh J. Desai

**Comment by ProLoser** [comment]
Removing html from the DOM does not affect the javascript's business logic
(such as what data is required and what isn't). You should instead /
additionally use ng-required.

On Tue, Nov 13, 2012 at 2:26 PM, jigneshjdesai notifications@github.comwrote:

> Greetings folks,
> 
> I am trying to use ui-if directive to remove/add control for “Callback
> Date” on the selection of specific item from the drop down in my app. That
> is working fine. I have also added validation for required fields using
> AngularJS validation. The dynamic control “Callback Date” is required field
> if present on the screen and that control is added to the DOM using ui-if
> when user selects “Callback” from the “Disposition” dropdown and removed if
> user selects any other value. I have Save button which I am disabling using
> the form.$invalid. It seems to be working fine except for one scenario. The
> scenario goes like this, user selected “Callback” in Disposition dropdown
> 
> > > app added “Callback Date” control to the DOM and probably to the Form’s
> > > control collection >> user, without entering anything in the “Callback
> > > Date” changes the value of Disposition dropdown. >> app removed the
> > > “Callback Date” control. After this, save button will stay disabled even if
> > > all the required controls have values filled. I think even after the ui-if
> > > removed control from the DOM, but I think it is somehow staying in Form’s
> > > control collection with $invalid state.
> 
> Can you guys please help me fix this issue? Below is the fiddle I have
> created with this functionality.
> 
> http://jsfiddle.net/jigneshjdesai/JhYph/10/
> 
> Many Thanks,
> 
> Jignesh J. Desai
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/261.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by jigneshjdesai** [comment]
Thanks for the reply Dean. That fixed the issue.

Many Thanks,
Jignesh

On Tue, Nov 13, 2012 at 6:00 PM, Dean Sofer notifications@github.comwrote:

> Removing html from the DOM does not affect the javascript's business logic
> (such as what data is required and what isn't). You should instead /
> additionally use ng-required.
> 
> On Tue, Nov 13, 2012 at 2:26 PM, jigneshjdesai notifications@github.comwrote:
> 
> > Greetings folks,
> > 
> > I am trying to use ui-if directive to remove/add control for “Callback
> > Date” on the selection of specific item from the drop down in my app.
> > That
> > is working fine. I have also added validation for required fields using
> > AngularJS validation. The dynamic control “Callback Date” is required
> > field
> > if present on the screen and that control is added to the DOM using
> > ui-if
> > when user selects “Callback” from the “Disposition” dropdown and removed
> > if
> > user selects any other value. I have Save button which I am disabling
> > using
> > the form.$invalid. It seems to be working fine except for one scenario.
> > The
> > scenario goes like this, user selected “Callback” in Disposition
> > dropdown
> > 
> > > > app added “Callback Date” control to the DOM and probably to the
> > > > Form’s
> > > > control collection >> user, without entering anything in the “Callback
> > > > Date” changes the value of Disposition dropdown. >> app removed the
> > > > “Callback Date” control. After this, save button will stay disabled even
> > > > if
> > > > all the required controls have values filled. I think even after the
> > > > ui-if
> > > > removed control from the DOM, but I think it is somehow staying in
> > > > Form’s
> > > > control collection with $invalid state.
> > 
> > Can you guys please help me fix this issue? Below is the fiddle I have
> > created with this functionality.
> > 
> > http://jsfiddle.net/jigneshjdesai/JhYph/10/
> > 
> > Many Thanks,
> > 
> > Jignesh J. Desai
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/angular-ui/angular-ui/issues/261>.
> 
> ## 
> 
> Dean J Sofer
> DeanSofer@gmail.com
> 
> BS Computer Information Systems
> California State Polytechnic University, Pomona
> Telephone: 714-900-2254
> Website: www.DeanSofer.com
> Github: github.com/ProLoser
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/261#issuecomment-10349619.

## 

Thanks & Regards,
Jignesh J. Desai

**Comment by pkozlowski-opensource** [comment]
Guess this one can be closed now.
