### ISSUE TITLE
Where is the demo page in the repo?

### ISSUE THREAD

**Issue by ghost** [angular-ui/angular-ui-OLDREPO#262]
I am very interested in seeing the source for this http://angular-ui.github.com/ but I can't seem to locate it anywhere in the repo (and I did try grep).

**Comment by pkozlowski-opensource** [comment]
It is in a separate repo under the angular-ui organization: https://github.com/angular-ui/angular-ui.github.com

**Comment by ProLoser** [comment]
Why can't all bugs be this easy?

**Comment by pkozlowski-opensource** [comment]
@ProLoser yeh, this would be awesome :-) I must say that I kind of like this CLOSE button in GH :-)
