### ISSUE TITLE
ui-if breaks other directives inside it

### ISSUE THREAD

**Issue by ghost** [angular-ui/angular-ui-OLDREPO#266]
Inside a ui-if element, changing the value of a model no longer updates the scope. Is this a bug or something I'm messing up?

**Comment by petebacondarwin** [comment]
Any chance this model is bound to a primitive value (i.e. a string or a
number) rather than a field on an object?  ui-if creates a new scope so
ng-model has no way of knowing where the primitive value came from.

**Comment by ghost** [comment]
Ahh, okay, that was it. Thanks!
