### ISSUE TITLE
[angular-ui] Arrow up/down key not working

### ISSUE THREAD

**Issue by kanheren** [angular-ui/angular-ui-OLDREPO#267]
13("enter" key press) is working fine for me but don't know why arrowKeyUp("38") and arrowKeyDown("40")  not working.

html code:

``` html
<body ng-controller="myListCtrl" ui-keypress="{ 38:'say()', 40:'say()', 13:'say()' }">
```

Controllers code:

``` js
myApp = angular.module('myApp',['ui']);
function myListCtrl($scope) {
    $scope.say = function(){
        alert('worked!');
    };
}
```

**Comment by ajoslin** [comment]
Note: you can write

```js
myCode()
```
or
```html
<div></div>
```

And it will come out pretty, all colored up :smile:. I fixed it for you

Anyway, you are right.. ui-keypress doesn't work for arrow keys.  The browser keypress event just doesn't catch arrow keys for some reason.  It does work with ui-keydown or ui-keyup though: http://plnkr.co/edit/Y213z4?p=preview

**Comment by kanheren** [comment]
Thanks for the fix.

Its working in all the browser now.

**Comment by alexanderwilms** [comment]
Just tested the plunker mentioned above in Chrome and ui-keypress does not work for arrow keys.

**Comment by ProLoser** [comment]
@alexanderwilms [Arrow keys do not trigger keypress events](http://stackoverflow.com/questions/5597060/detecting-arrow-keys-in-javascript).

**Comment by malcolmocean** [comment]
Just thought I'd throw it out there that apparently keypress refers to the insertion of a character while keydown and keyup refer to the pushing of a physical button. Therefore keypress won't work for any key that doesn't have an actual character associated with it.

For more see http://www.quirksmode.org/dom/events/keys.html

ETA: Ahh, just realized I was beaten to the chase.

**Comment by ProLoser** [comment]
2 months ago lol.

**Comment by malcolmocean** [comment]
Yeah, I glanced at the other comments but didn't see an explanation. Of course, this is is the internet, and hyperlinks can be the best explanations.
