### ISSUE TITLE
angular module namespacing problem

### ISSUE THREAD

**Issue by dandoyon** [angular-ui/angular-ui-OLDREPO#27]
This is a pretty major problem (and came at a loss of whatever hair i have left) with an easy, albeit annoying
solution. The problem is that the angular module namespacing  is not behaving as one would hope.  

The module.FOOBAR namespacing is not additive. So if you, create a directive

angular.module('ui.directives').directive('uiFoo', [], function() {})

and then create

angular.module('ui.directives').directive('uiBar', [], function() {})

Then you will only have one directive 'uiBar', 'uiFoo' is lost to the bitbucket

I'm going to put in a feature request on angular.js site. In the meantime, there are a couple of alternatives 
(and probably more). 
1. Individually namespaced directives and then aggregated in ui.directives
   angular.module('ui.directives.uiFoo').directive('uiFoo', [], function() {})
   angular.module('ui.directives.uiBar').directive('uiBar', [], function() {})
   angular.module('ui.directives',['uiFoo', 'uiBar'])
   
   this kinda fits the slicing and dicing, we are proposing, however, I think we'll need to generate the module.js file.
2. Clump all the files together into one file under a 'ui.directives' module, this flies in face of the slicing and dicing. 

I believe this problem is in both current and 1.0.0 versions of angular.

**Comment by ProLoser** [comment]
This sounds like a critical bug with Angular, if you are forced to create a MODULE for each and every directive... I'm sorry but that's just retarded (and sounds like it would break my current internal setup).

Is this just something that is new to 1.0 stable?

**Comment by ProLoser** [comment]
It might just be me but your syntax looks wrong.

I just updated the angular-ui website to v1.0.1 and don't see any problems or errors. All directives appear to work fine.

Normally I do:

```
directive('uiFoo', [function(){

}])
```

I do not use 3 parameters, just 2, and make the function the last parameter in the array. That or I leave out the array altogether, but I never have anything other than 2 parameters to the directive function.

I went into the angular source code to confirm this (since documentation clearly sucks bawsl) and this appears to be the [same syntax they use](https://github.com/angular/angular.js/blob/master/src/ng/directive/ngInclude.js#L81)

**Comment by dandoyon** [comment]
Hmm, if this is the solution, then that is great, I don't know where I got 3 params from, probably copy and paste. 

what is bothersome is that this way of doing things actually works.... 

thanks for looking into

I'll look at existing stuff and fix.

--dan

**Comment by dandoyon** [comment]
Well, after finding out what the problem is, I went to doc for sanity check and saw that disqus thread already captured problem. 

http://docs.angularjs.org/api/angular.module

Ver 1: http://jsfiddle.net/A8Vgk/7/      Nope

Ver2: http://jsfiddle.net/ewKKE/1/      Yep

the problem is when you provided 'requires' array it does not work as expected. So, if we have any directives that have requires things fall apart.

**Comment by dandoyon** [comment]
filed bug

https://github.com/angular/angular.js/issues/1097

**Comment by ProLoser** [comment]
Actually, I thought we identified this a while ago when we were making
everything into separate modules. This is not a bug.

The first time you declare the module, you should inject whatever
dependencies you have for it. After that, you simply leave out the
injection array and it will re-use the original module declared earlier.
This is how AngularUI is currently setup.

On Tue, Jun 26, 2012 at 9:29 PM, dandoyon <
reply@reply.github.com

**Comment by dandoyon** [comment]
So, I would say its not an angular-ui bug but an angular.js one or at least an inconsistency. Sorry, I missed the original discussion, I made the fortunate/unfortunate mistake of copying Pete's date wrapper as a basis for my currency 
directive and this started me down into the bowels. I'm actually glad (even though I wasted copious amounts of time).

I'm OK with this as long as we don't encounter a situation whereby a directive needs injectables, then we need to rethink.

**Comment by ProLoser** [comment]
No you have the syntax confused. I suppose it was with Pete that we
realized what was going on.

Here is how it works:

You DECLARE a module by passing it's dependencies. You RECALL it by NOT
passing its dependencies.

Directives however are different. You are free to have dependencies or
leave them out as you wish. You can attach them to the MODULE when you
initially create it OR when you RECALL it, it will not behave differently.

So to summary: directives are free at any time to have dependencies or
leave out dependencies. Modules however should only list dependencies the
very first time (when you create it). After that you must NOT list
dependencies or you will wipe out the original module and create a new one.

On Tue, Jun 26, 2012 at 9:58 PM, dandoyon <
reply@reply.github.com

**Comment by dandoyon** [comment]
I think, IMHO, that what should happen on the angular side of things is to throw an exception if you are redeclaring a module.

angular.module('foo',[])
angular.module('foo',['bar'])

this would've saved a bit of grief.

Thank you for the clarification.
