### ISSUE TITLE
Date picker displays date correctly, but doesn't sync with source

### ISSUE THREAD

**Issue by sweisman** [angular-ui/angular-ui-OLDREPO#271]
This is separate from, but related to, issue 201, which I also submitted.

I have a datepicker widget. The incoming values are of the format "yy-mm-dd". When I use this invocation:

&lt;input ui-date="date_options" ui-date-format="yy-mm-dd" ng-model="item.birth_date"&gt;

I get the widget to instantiate correctly, but when I modify the date and refer to item.birth_date later (eg for submitting a form to the server), item.birth_date is always null. However, when I remove ui-date-format, like this:

&lt;input ui-date="date_options" ng-model="item.birth_date"&gt;

the widget doesn't instantiate correctly (it is always null), but when I modify the date and refer to it later, item.birth_date is set, as expected.

Am I doing something wrong, or is this a bug?

**Comment by petebacondarwin** [comment]
@sweisman : I have fixed what I think is the problem with commit 2f10e50e98c438a00732edb9ba352fa31b8b77cf - in master now.
