### ISSUE TITLE
Date ISO 8601 problem

### ISSUE THREAD

**Issue by philjones88** [angular-ui/angular-ui-OLDREPO#272]
Hi,

I'm trying to use the Date directive with JSON returned from an ASP.NET Web API service.

It returns datetimes like:

{
receivedAt: "2012-11-20T11:02:49.1223416+00:00"
}

But I can't seem to get it working with the Date directive like:

<input ng-model="item.receivedAt" ui-date-format="yy-mm-dd" ui-date>

As it says:

Extra/unparsed characters found in date: T11:02:49.1223416+00:00 

Any ideas anyone?

**Comment by petebacondarwin** [comment]
I am looking into this.  I have just fixed a different bug and in the new version this doesn't seem to happen:  
Can you try this out?
http://plnkr.co/edit/PLjGH2?p=preview
Pete

**Comment by philjones88** [comment]
Hi,

That works but can't get it into the UK/World format of yy-mm-dd without the same error though?

**Comment by philjones88** [comment]
Sorry, closed by mistake, your fix works but doesn't allow formatting to yy-mm-dd?

**Comment by petebacondarwin** [comment]
What exactly are you trying to do?  Can you modify the plunker above to demonstrate?

**Comment by philjones88** [comment]
http://plnkr.co/edit/hNXtsN?p=preview

Brain freeze, re-reading it after a coffee I realise trying to put:

ui-date-format="yy-mm-dd"

Was silly, found all the options list at:

http://api.jqueryui.com/datepicker/

I'll close it again!
