### ISSUE TITLE
Angular-ui in a CDN

### ISSUE THREAD

**Issue by tiagoroldao** [angular-ui/angular-ui-OLDREPO#273]
I believe angular-ui isn't in a CDN yet, wouldn't that be a good idea? Maybe http://cdnjs.com/ ?

**Comment by dandoyon** [comment]
Great idea google may give us a place

**Comment by i-am-logger** [comment]
are there any news regarding CDN ?

**Comment by ProLoser** [comment]
Been too busy and felt it raises new concerns, such as our build process and stability of the lib.

Regardless, nothing's stopping you from doing this yourself on our behalf to cdnjs like @tiagoroldao mentions

**Comment by wesleycho** [comment]
This repository is has been discontinued, I recommend opening a new issue in the appropriate plugin repository if it is still an issue.
