### ISSUE TITLE
Error in Select2

### ISSUE THREAD

**Issue by ivangarcia2** [angular-ui/angular-ui-OLDREPO#274]
I'm getting an error with the select2 component when I don't specify the ngMultiple attribute.

The error comes from line 96:

``` javascript

          scope.$watch(attrs.ngMultiple, function(newVal) {
            elm.select2(opts);
          });

```

I have solved it this way:

``` javascript
        if (attrs.ngMultiple){
          scope.$watch(attrs.ngMultiple, function(newVal) {
            elm.select2(opts);
          });
        }
```

This is the error shown in console if I don't apply the patch:

TypeError: Cannot read property 'exp' of undefined
    at watchFnToHumanReadableString (http://localhost/test.html:319:19)
    at Object.$delegate.**proto**.$watch (http://localhost/test.html:351:28)
    at https://raw.github.com/angular-ui/angular-ui/master/build/angular-ui.js:946:15
    at nodeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.1/angular.js:4223:13)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.1/angular.js:3838:14)
    at nodeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.1/angular.js:4217:24)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.1/angular.js:3838:14)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.1/angular.js:3841:12)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.1/angular.js:3750:30
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.1/angular.js:932:25 <select ui-select2="" ng-model="selectedSingle" data-placeholder="-- Select One --" class="ng-pristine ng-valid">

**Comment by callado4** [comment]
I've seen this error when I have Batarang enabled, so it seems to be something related to what Batarang is doing.

**Comment by ProLoser** [comment]
1. Open a pull request
2. What line is 946 of your angular-ui.js?
3. What is the code in question on test.html?
4. Why do you think this fixes it? (`TypeError: Cannot read property 'exp' of undefined` does not seem related to multiple)

**Comment by davisford** [comment]
Ditto here -- I just did a git pull on HEAD of angular-ui and rebuilt (commit c95c16ee9cfd080b389bbe4eb8ce16662ce06a2b), definitely seems to be triggered by Batarang.  If I enable batarang, I have the error noted above; disable batarang and it goes away.

For reference the HTML I have is this:

``` html
<select ng-model="selectedFilters" ui-select2="{multiple:true}" ng-change="onFilterChange(selectedFilters)">
  <option ng-repeat="filter in filters" value="{{filter.value}}"> {{filter.text}} </option>
</select>
```

**Comment by pavelsavara** [comment]
Same issue with select2 , AngularJS v1.1.1 and latest Batarang from web store (where could I check it's version ?).

**Comment by munsellj** [comment]
Same here, if I have Batarang Enabled in Chrome Extensions I get this error even with 0.3.2 unless I add an ng-multiple attribute to my <select> tag.  Even ng-multiple="" or ng-multiple="false" will seem to resolve the error and allow Select2 to work properly.  

Note on disabling Batarang: I have to fully disable it by unchecking "Enable" on the Chrome Extensions settings page to fix the issue.  Unchecking the "Enable" checkbox in the tabs at the top of the AngularJS tab for Batarang in the Chrome Dev Tools won't fix the issue.

Makes me a bit uneasy, but thanks for the tip on the issue being somehow related to ng-multiple, at least works around the issue for now.

**Comment by ProLoser** [comment]
Not sure how to fix this yet

**Comment by ivangarcia2** [comment]
Why don't you use my solution? Is working fine for me. I'm sorry but I don't know how to make a pull request, but it as simple as check when the ng-multiple attribute is present or not:

  if (attrs.ngMultiple){
          scope.$watch(attrs.ngMultiple, function(newVal) {
            elm.select2(opts);
          });
  }

**Comment by ProLoser** [comment]
If you look at my commit when I closed the bug, your code is already merged in. So either this didn't fix the problem or people are using the wrong version.  

## 

Dean Sofer
DeanSofer.com
714.900.2254

**Comment by ProLoser** [comment]
https://github.com/angular-ui/angular-ui/blob/master/modules/directives/select2/select2.js#L98-L102

## 

Dean Sofer
DeanSofer.com
714.900.2254

**Comment by munsellj** [comment]
@ProLoser I think I know what happened.  You did indeed merge that fix but it looks like the /build directory wasn't updated for the v0.3.2 release because while /modules/directives/select2/select2.js source file includes the fix, /build/angular-ui.js doesn't.  I'm guessing maybe something went wrong with the build before releasing v0.3.2(or someone forget to do it).

I cloned master and built locally and I see the change in /build/angular-ui.js after building.  The fix does also seem to resolve the issue for me, I no longer need to specify a ng-multiple attribute in order for ui-select2 to work with Batarang Enabled.

Thanks and keep up the good work!

**Comment by ProLoser** [comment]
I'm aware that the build was not updated, I'm trying to get a bunch of PRs merged before releasing a new build. Good to know it has the fix. Just keep an eye out for v0.4.0, and sorry it's taking so long!

**Comment by dabit3** [comment]
Thank you! Disabling batarang did the trick for me as well.
