### ISSUE TITLE
Please rebuild with ui-date-format fix

### ISSUE THREAD

**Issue by tsenying** [angular-ui/angular-ui-OLDREPO#280]
Would you push a build for commit 2f10e50?

**Comment by pmn** [comment]
+1 this would be very useful to me as well

**Comment by ProLoser** [comment]
@joshkurz since you're going to (or already) doing this, do you mind making sure this gets in there too?

**Comment by joshkurz** [comment]
sure thing

On Tue, Dec 4, 2012 at 5:29 PM, Dean Sofer notifications@github.com wrote:

> @joshkurz https://github.com/joshkurz since you're going to (or
> already) doing this, do you mind making sure this gets in there too?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/280#issuecomment-11018702.

## 

_Josh Kurz_
*
Head of Web Development*
SEO
Social Media
Digital Photography
Internet Marketing

cell#      404-641-7807
office#    404-593-0851
fax#       404-506-9642
*Dillinger Media *
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by joshkurz** [comment]
the head is now on v0.3.2
