### ISSUE TITLE
Agree Release Process

### ISSUE THREAD

**Issue by petebacondarwin** [angular-ui/angular-ui-OLDREPO#281]
So someone has requested a new release containing fixes I pushed for the date directive.

What should the process be here?

Are we safe running releases off the master branch?

What checking is going into commits that are merged there?
Currently there are at least three failing tests in the master branch.  We shouldn't really be accepting merges into master until they have been shown to pass on a side branch in travis at least.

I don't really have time this month but someone ought to go through and either fix the failing tests or roll back those modules to working versions.

Also, can we encourage people to branch their own repositories when working on stuff?  It is really difficult to see what is going on when you have loads of changes on other peoples master branches. The process should be:

**Contributor**
- fork main repos to own repos on GitHub
- clone the repos to local machine
- checkout -b name-of-my-changes
- develop stuff, including tests!
- build and test
- commit
- push to own repos
- send Pull Request

**Core Team**
- Add remote to PR repos to local machine repos
- Pull in branch from PR
- Build and test locally
- (Possibly rebase, cherry pick, rewrite commit msgs, etc.)
- Push branch to main repos
- Check that travis runs successfully
- Fast Forward merge into master locally (i.e. no nasty branch merges - might require rebase, see above)
- Push to main repos [Question is where?]
- Check that travis still runs successfully
- Close PR and related issues
- [Create a new release if appropriate]

**This last point is key here:**
- I think we should have a branch for the next major and next minor releases...
  
  Currently we are on 0.3.1, so we should have a 0.3.x branch and a 0.4.x branch.  We could also have a 1.x branch if we were developing something very new.
- All merges would go into the 0.4.x branch, since this will be the next minor release.
- If we have a bug fix then we should cherry pick this into the 0.3.x branch and immediately release a new version (e.g. from 0.3.3 to 0.3.4).
- A new release would involve merging the relevant branch (say 0.3.x or 0.4.x) into master.  I.E. We say that master is always the current release and only releases will merge into it.  If we released to 0.4.0 then the 0.3.x branch would become an old release bug fix branch, the 0.4.x would become a bug fix branch and we would create a new 0.5.x branch for new features.  The 0.3.x would only be supported with occasional bug fixes but most work would now focus on 0.4.x and 0.5.x.
- It may be to keep it more understandable we have 0.3.x, master and current branches.  The current would become the GitHub default branch and master would be the 0.4.x branch.

What do you think?

Pete

**Comment by ProLoser** [comment]
Agreed. I was thinking about this too when I saw that bug get opened.

My one and only question is regarding [Create a new release if
appropriate]. When do we determine a new release is NOT appropriate? I
realize that we are _hoping_ to put a large batch of fixes or updates
together and push them out at the same time but the bottom line is we don't
have anyone doing this on a regular basis in an official capacity.

Perhaps we should include build versions too so that we will not feel as
discouraged from pushing minor fixes when other bugs are still open?

**Comment by petebacondarwin** [comment]
My view was that any bug fix (i.e. a PR that gets merged into 0.3.x) would
be released immediately, since this is an easy decision and doesn't break
anyone's current app.
If a new feature is added then we would be bumping to 0.4 and so that would
need a bit more thought and also it would be better to lump these kind of
changes together for easier release management.
So you would see in the tag list something like this:

0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.4.0, 0.3.7, 0.4.1, 0.4.2,
0.4.3, 0.4.4, 0.3.8, 0.5.0, 0.4.5

and so on.

**Comment by joshkurz** [comment]
So with this in mind the PR I have open atm would be merged in and tagged
as the 0.3.2 update. Then any future updates made to the calendar directive
would yield further 0.0.x increments.
If we add a new directive to the repo then that would be considered a new
feature yielding a 0.x.0 increment, or is a new feature something that can
be added to an existing directive as well?

Would there be a need to change the version at all if just tests were
updated, or is the version only updated if the directive itself is altered?

By the way thanks for making me a core member. Its a real honor. My skills
have increased drastically from working with the team, especially when it
comes to testing. I will take a look at the tests that are currently
failing and try to fix them.

On Thu, Nov 29, 2012 at 5:11 AM, Pete Bacon Darwin <notifications@github.com

> wrote:
> 
> My view was that any bug fix (i.e. a PR that gets merged into 0.3.x) would
> be released immediately, since this is an easy decision and doesn't break
> anyone's current app.
> If a new feature is added then we would be bumping to 0.4 and so that
> would
> need a bit more thought and also it would be better to lump these kind of
> changes together for easier release management.
> So you would see in the tag list something like this:
> 
> 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.4.0, 0.3.7, 0.4.1, 0.4.2,
> 0.4.3, 0.4.4, 0.3.8, 0.5.0, 0.4.5
> 
> and so on.
> 
> On 29 November 2012 10:02, Dean Sofer notifications@github.com wrote:
> 
> > Agreed. I was thinking about this too when I saw that bug get opened.
> > 
> > My one and only question is regarding [Create a new release if
> > appropriate]. When do we determine a new release is NOT appropriate? I
> > realize that we are _hoping_ to put a large batch of fixes or updates
> > together and push them out at the same time but the bottom line is we
> > don't
> > have anyone doing this on a regular basis in an official capacity.
> > 
> > Perhaps we should include build versions too so that we will not feel as
> > discouraged from pushing minor fixes when other bugs are still open?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/angular-ui/angular-ui/issues/281#issuecomment-10841304>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/281#issuecomment-10841553.

## 

_Josh Kurz_
*
Head of Web Development*
SEO
Social Media
Digital Photography
Internet Marketing

cell#      404-641-7807
office#    404-593-0851
fax#       404-506-9642
*Dillinger Media *
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by joshkurz** [comment]
And my bad for leaving my email tag everywhere. Its an accident every time
I do it.

## 

_Josh Kurz_
*

*

**Comment by petebacondarwin** [comment]
If we are following the "Semantic Versioning http://semver.org/"
specification then every new feature is a minor release change:

   1.

   Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards
   compatible bug fixes are introduced. A bug fix is defined as an internal
   change that fixes incorrect behavior.
   2.

   Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards
   compatible functionality is introduced to the public API. It MUST be
   incremented if any public API functionality is marked as deprecated. It MAY
   be incremented if substantial new functionality or improvements are
   introduced within the private code. It MAY include patch level changes.
   Patch version MUST be reset to 0 when minor version is incremented.
   3.

   Major version X (X.y.z | X > 0) MUST be incremented if any backwards
   incompatible changes are introduced to the public API. It MAY include minor
   and patch level changes. Patch and minor version MUST be reset to 0 when
   major version is incremented.

**Comment by ProLoser** [comment]
So to clarify, I personally would throw additional unit tests into a patch.
And don't worry about the footers, happens for everyone.

On Thu, Nov 29, 2012 at 2:48 AM, Pete Bacon Darwin <notifications@github.com

> wrote:
> 
> If we are following the "Semantic Versioning http://semver.org/"
> specification then every new feature is a minor release change:
> 
> 1.
> 
> Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards
> compatible bug fixes are introduced. A bug fix is defined as an internal
> change that fixes incorrect behavior.
> 2.
> 
> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards
> compatible functionality is introduced to the public API. It MUST be
> incremented if any public API functionality is marked as deprecated. It
> MAY
> be incremented if substantial new functionality or improvements are
> introduced within the private code. It MAY include patch level changes.
> Patch version MUST be reset to 0 when minor version is incremented.
> 3.
> 
> Major version X (X.y.z | X > 0) MUST be incremented if any backwards
> incompatible changes are introduced to the public API. It MAY include
> minor
> and patch level changes. Patch and minor version MUST be reset to 0 when
> major version is incremented.
> 
> On 29 November 2012 10:43, Josh Kurz notifications@github.com wrote:
> 
> > And my bad for leaving my email tag everywhere. Its an accident every
> > time
> > I do it.
> > 
> > ## 
> > 
> > _Josh Kurz_
> > *
> > 
> > *
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/angular-ui/angular-ui/issues/281#issuecomment-10842438>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/281#issuecomment-10842588.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by joshkurz** [comment]
ok so I just merged in the updated calendar, and also updated the version
number to 0.3.2.  Was this the correct move?

On Thu, Nov 29, 2012 at 1:44 PM, Dean Sofer notifications@github.comwrote:

> So to clarify, I personally would throw additional unit tests into a
> patch.
> And don't worry about the footers, happens for everyone.
> 
> On Thu, Nov 29, 2012 at 2:48 AM, Pete Bacon Darwin <
> notifications@github.com
> 
> > wrote:
> > 
> > If we are following the "Semantic Versioning http://semver.org/"
> > specification then every new feature is a minor release change:
> > 
> > 1.
> > 
> > Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards
> > compatible bug fixes are introduced. A bug fix is defined as an internal
> > change that fixes incorrect behavior.
> > 2.
> > 
> > Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards
> > compatible functionality is introduced to the public API. It MUST be
> > incremented if any public API functionality is marked as deprecated. It
> > MAY
> > be incremented if substantial new functionality or improvements are
> > introduced within the private code. It MAY include patch level changes.
> > Patch version MUST be reset to 0 when minor version is incremented.
> > 3.
> > 
> > Major version X (X.y.z | X > 0) MUST be incremented if any backwards
> > incompatible changes are introduced to the public API. It MAY include
> > minor
> > and patch level changes. Patch and minor version MUST be reset to 0 when
> > major version is incremented.
> > 
> > On 29 November 2012 10:43, Josh Kurz notifications@github.com wrote:
> > 
> > > And my bad for leaving my email tag everywhere. Its an accident every
> > > time
> > > I do it.
> > > 
> > > ## 
> > > 
> > > _Josh Kurz_
> > > *
> > > 
> > > *
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/angular-ui/angular-ui/issues/281#issuecomment-10842438>.
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/angular-ui/angular-ui/issues/281#issuecomment-10842588>.
> 
> ## 
> 
> Dean J Sofer
> DeanSofer@gmail.com
> 
> BS Computer Information Systems
> California State Polytechnic University, Pomona
> Telephone: 714-900-2254
> Website: www.DeanSofer.com
> Github: github.com/ProLoser
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/281#issuecomment-10860609.

## 

_Josh Kurz_
*
Head of Web Development*
SEO
Social Media
Digital Photography
Internet Marketing

cell#      404-641-7807
office#    404-593-0851
fax#       404-506-9642
*Dillinger Media *
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by petebacondarwin** [comment]
Hi Josh
This is not quite right.
First if you are happy to merge in your changes to the master, my personal preference is to rebase the local branch and then merge (fast forward only) onto master.  Then you get a much cleaner history without loads of merge commits and side branches everywhere.  Doing this is also a good discipline as it makes you think about the merge of your branch in more concrete terms and also offers the opportunity to squash commits and modify commit messages to make it easier to follow what you did when looking back at the history.

Second, if you are going to push a release then, right now you should follow the procedure in the README: https://github.com/angular-ui/angular-ui#publishing.  This includes building and tagging the release files, which you haven't done.

If I get some time later this month I am going to try to recalibrate the branches and release process in line with what is discussed in this issue.  We should probably automate it with a grunt task.

Regards
Pete

**Comment by ProLoser** [comment]
Side note. I might recommend making the merge / rebase separate from the
release commit. The commit that is tagged should only contain new build
files and changelog and nothing else. Thoughts @pete?

**Comment by pkozlowski-opensource** [comment]
@ProLoser @petebacondarwin +1 for having a dedicated release commit. As @ProLoser is saying it should have only check-in of the build files (till we've got a better idea), version change etc. But we should really try to automate this process so cutting a release is easy.

**Comment by pete** [comment]
@ProLoser Seems reasonable.

**Comment by joshkurz** [comment]
Ok so I should have re-based everything together, which I thought I had,
and then built and tagged the release files. Overall there should have been
two commits. One for the changes to the files and one for the tagged
release build.

Is it ok?

On Mon, Dec 3, 2012 at 1:04 PM, Pete notifications@github.com wrote:

> @ProLoser https://github.com/ProLoser Seems reasonable.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/281#issuecomment-10963940.

## 

_Josh Kurz_
*
Head of Web Development*
SEO
Social Media
Digital Photography
Internet Marketing

cell#      404-641-7807
office#    404-593-0851
fax#       404-506-9642
*Dillinger Media *
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by petebacondarwin** [comment]
@josh: At least two commits - you don't have to squash all your changes
into one commit.  Just few enough to make it easy to see what you were
doing.  I tend to commit a lot in development but less in PRs.

**Comment by joshkurz** [comment]
ok thanks Pete. I will take that into consideration as I make further PRs, and wont merge any until everyone is satisfied.

So what are the next steps then?

**Comment by joshkurz** [comment]
ok So i have pushed a new build version of the master file set. We are now on v0.3.2.

**Comment by petebacondarwin** [comment]
Well done Josh!

**Comment by ProLoser** [comment]
So I was looking at Bootstrap, and it looks like they have a similar setup to ours:
1. There are no build files in their master
2. Their tags are on master and also do not contain build files
3. Only gh-pages branch has the download.zip, and it appears that they do not keep past revisions

For the sake of just having this sorted out, should we adopt a similar approach?

We could relocate the AngularUI docs to the gh-pages branch of the AngularUI project and make the existing home page a generalized, organization-wide landing page?

**This would mean that only `gh-pages` would contain build files, and only the latest build**

**Comment by ProLoser** [comment]
I kind of like this idea ^^ so unless someone vetos this in the next few days I will probably move forwards with it.

**Comment by pkozlowski-opensource** [comment]
+1

Initially I was proposing moving build files to the angular-ui.github.com but since now we've got multiple repos under one angular-ui umbrella the `gh-pages` make more sense. 

I guess that any change that gets the build files out of master is the good one. I would keep several versions (for different releases) in the gh-pages though.

**Comment by ProLoser** [comment]
Well the revision history in the gh-pages branch would still contain the build files, but it wouldn't be tagged? (lest it show up in the list of tags as duplicates)

**Comment by pkozlowski-opensource** [comment]
What I'm after here is to be able to reference builds from a plunker / fiddle. Which basically means that we need to have several version available.

As gh-pages are generated I don't think tags will help much here. 

So I would be still in favor of commiting released files with a version in their name to the gh-pages. Unless there is an easier way to be able to reference past releases and not hit raw.github all the time.

**Comment by ProLoser** [comment]
Touche Salesman.

Back to the drawing board. I'm still thinking the build server is the 'proper' solution, just need to stop playing video games and actually work on it lol.

**Comment by petebacondarwin** [comment]
Can't we just copy the build files into the gh-pages branch under their own
folder, i.e. that references their build version?

**Comment by pkozlowski-opensource** [comment]
This would work for me as well :-)
