### ISSUE TITLE
Lot's of errors and issues

### ISSUE THREAD

**Issue by isAlmogK** [angular-ui/angular-ui-OLDREPO#287]
I'm getting lot's of errors just using ui-if and model, I looked at the examples and my code is 100% the same not sure what's going on. 

This is what I'm getting 

TypeError: Object [[object HTMLDivElement]] has no method 'on'
at update (http://localhost:3501/scripts/vendor/angular.js:13696:11) <div id="modalGuy" class="fade ng-pristine ng-valid modal hide" ui-modal="" ng-model="modalShown"> 

Has to do with modal 

And I'm getting this error for ever ui-if that I use 
TypeError: Object [[object HTMLDivElement]] has no method 'trigger'

**Comment by ProLoser** [comment]
Can you paste some code you're using to create the problem? Or (better yet) a jsfiddle or plunker that reproduces this bug?

**Comment by isAlmogK** [comment]
I can do a jsfiddle but not sure how to reproduce this as it's all in the view.  

Here is what I'm doing for ui-if very basic 

``` html
<td ui-if="game.status == 1"><a href="" ng-click="deactivate(game)" class="game_status"><img src="../img/status-active.png" alt="Unpublish"></a>ACTIVE</td>
```

**Comment by mickhrmweb** [comment]
I've been experiencing this same issue, and have found a reproduction: http://jsfiddle.net/q3qKE/4/

Edit: I am using Chrome 23 under Xubuntu 12.10, the errors are in the JS console.

**Comment by petebacondarwin** [comment]
I guess you are talking about this line blowing up?

iterStartElement.parent().trigger("$childrenChanged");

trigger is not a method on jqLite (i.e. it only works on ful jQuery).  I
would say that this is a bit of a pointless bit of code any way and
probably if it going to be used at all should be
$scope.emit('$childrenChanged') anyway.

I recently made a tidied up version of ui-if for a chapter in my book.  I
should probably push it back into angular-ui

Pete

**Comment by fredrikholmen** [comment]
What is the full version of jquery? I'm using ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js and get the error. What jquery library should I be using? Great if you add you can update the angular-ui library and thanks for a great extension.

**Comment by petebacondarwin** [comment]
Have a look at the this PR https://github.com/angular-ui/angular-ui/pull/365.
 See if this works better for you.

**Comment by fredrikholmen** [comment]
Thank you. That seems to work much better. No more exceptions.

//F

---

Fredrik Holmén
CTO & Co-Founder

Keybroker, Jakobsbergsgatan 16, 111 44 Stockholm, Sweden
Mobile +46 734 332 501 | Main +46 8 5100 5700
fredrik.holmen@keybroker.com | keybroker.com

Keybroker:  Consistently driving more profitable online sales - Try us.

**Comment by ProLoser** [comment]
#365
