### ISSUE TITLE
jQuery Passthrough: two way data binding

### ISSUE THREAD

**Issue by bfcamara** [angular-ui/angular-ui-OLDREPO#293]
I am trying to use the jQuery Passthrough to integrated with spin.js jquery plugin (https://github.com/neteye/jquery-plugins/tree/master/activity-indicator)

```
<div id="busyindicator" data-ui-jq="activity" data-ui-options="isBusy"></div>
```

In my controller i have the property isBusy.

I thought that changing the isBusy value in the model  would fire the $.fn.activity function, but as far as I can get I am wrong, right?

How can I get the intended bahavior?

Thanks in advance

Bruno

**Comment by ProLoser** [comment]
Changing the options does not refire the directive. At this time the passthrough does not support being re-fired more than once. I've been trying to think of good ways to make this possible, but I do not have any clear ideas for a good API to accomplish this.
