### ISSUE TITLE
jq dialog passthrough doesn't destroy on app navigation

### ISSUE THREAD

**Issue by djabor** [angular-ui/angular-ui-OLDREPO#294]
Currently, when registering multiple passed-through Jquery-UI Dialogs over multiple views, the dialogs are appended to the page html successfully, but are not unregistered/destructed when navigating. This is causing the two-way binding to cease working for unclear reasons.

Example:
 two non-html5 views, with a dialog in each view:
# /main

``` html
 <div id="dialog1" ui-jq="dialog">{{someBinding}}</div>
```
# /gallery

``` html
<div id="dialog2" ui-jq="dialog">{{someOtherBinding}}</div>
```

when opening each of these pages directly (hard refresh or initial browser navigation)
both dialogs work fine and bindings work perfectly.
there is a single dialog registered in the page

But when navigating from either #/main to #/gallery or vice versa from withing the application,
both pages contain both dialogs.

for now i am fixing this by running the destruct manually on every page load,
another possible workaround is to have all dialogs on the root layout, but that will clearly result in a mess with scopes.

In any case, the dialogs should destruct on navigation automatically or by some setting in angular-ui.

EDIT:
I also just realized that when navigating from #/main -> #/gallery -> #/main , #dialog1 is added resulting in 2 #dialog1 dialogs, this is what breaks the two-way binding.

**Comment by ProLoser** [comment]
I'm going to close this as it's outside the scope of `ui-jq`

You might want to take a look at using http://angular-ui.github.com/bootstrap/#/dialog instead
