### ISSUE TITLE
IE 8 and 9

### ISSUE THREAD

**Issue by johntom** [angular-ui/angular-ui-OLDREPO#297]
Hi,
If I add the following line to my directives.js file without any other code I get the following errors in IE 8 and IE9 and my app breaks. No problem for Chrome and FF.
angular.module('myApp.directives', ['ui'])
TIA
John

references in index.jade
  script(src='http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js')
  script(src='https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.min.js')
  script(src='http://ajax.googleapis.com/ajax/libs/angularjs/1.0.3/angular.js')
  script(src='http://twitter.github.com/bootstrap/assets/js/bootstrap.min.js')
  script(src='https://raw.github.com/angular-ui/angular-ui/master/build/angular-ui.js')

SEC7113: CSS was ignored due to mime type mismatch 
angular-ui.min.css
SEC7112: Script from https://raw.github.com/angular-ui/angular-ui/master/build/angular-ui.js was blocked due to mime type mismatch 
login
SCRIPT5022: No module: ui 
angular.js, line 1058 character 11

**Comment by ProLoser** [comment]
Sounds like you should be downloading the lib files rather than using raw.github (github doesn't like serving assets remotely).

**Comment by johntom** [comment]
Thanks Dean
I originally had a local reference and didn't realize that github issue because it never showed up in chrome.
very much appreciated,
John
