### ISSUE TITLE
Twitter Bootstrap Model 

### ISSUE THREAD

**Issue by isAlmogK** [angular-ui/angular-ui-OLDREPO#298]
Hi, 
Wanted to request a feature would it be possible to have to another option for lightbox / model then Twitter Bootstrap Model. 

We wanted to use this but when adding the bootstrap CSS file we have a number of issues with our current CSS files.  

Also the Twitter Bootstrap Model has lot' of issues you can you even see this at http://builtwith.angularjs.org/

**Comment by ProLoser** [comment]
Maybe we should replace it with this and move the existing one to the
bootstrap project instead.

**Comment by pkozlowski-opensource** [comment]
Boostrap project has modal already: https://github.com/angular-ui/bootstrap/tree/master/src/modal

@almogdesign what are the issues you are talking about, exactly?

**Comment by isAlmogK** [comment]
If your app already has CSS styles adding the Twitter Bootstrap CSS file creates conflicts. Twitter Bootstrap is designed to be the base making it hard to add the Model to an existing app. I would suggest something that does not create conflicts

**Comment by ProLoser** [comment]
@pkozlowski-opensource I think it would be appropriate to finally remove ui-modal (or replace it with the one I linked to) altogether?

It was something I figured we'd do eventually anyway.

Here is the modal I intended to link to: http://plnkr.co/edit/gist:3758344?p=preview

**Comment by isAlmogK** [comment]
I did get it working everything but the animation

**Comment by isAlmogK** [comment]
Closing this and opening a new text, explaining what needs to be updated.

**Comment by ProLoser** [comment]
PINGING EVERYONE:

Should we go ahead and remove/replace this module?

I can put in a refined version of the demo I linked?

**Comment by isAlmogK** [comment]
No the model works great you just need to understand how to use it, the best thing to do is update docs they created most of the issues and maybe the CSS movie it to the UI CSS.

**Comment by ProLoser** [comment]
I honestly think this implementation is no longer relevant to AngularUI as it is the only Bootstrap plugin in this project. There is already another project that is entirely bootstrap that contains the same functionality (or probably better).

**Comment by isAlmogK** [comment]
What project is that would be glad to check it out. I think AngularUI needs more Bootstrap plugins it would be great. Bye the way we have an alert plugin we can open source will tell my CTO about this.

**Comment by ProLoser** [comment]
https://github.com/angular-ui/bootstrap

**Comment by pkozlowski-opensource** [comment]
+1 for redirecting people top the implementation in the boostrap repo. Hopefully soon we will have a nice contribution to this modal so it can be triggered from a controller / service.

**Comment by ProLoser** [comment]
bf20d8877475cd19de3f8e58c7f4474788a08700
