### ISSUE TITLE
Which version is stable for download / production? 

### ISSUE THREAD

**Issue by isAlmogK** [angular-ui/angular-ui-OLDREPO#299]
Hi wanted to know which version is good for download I see there are tags and the master?

**Comment by joshkurz** [comment]
v0.3.2 is the latest version of angular-ui. The current build is the exact replica of the tag. The build is stable, with exceptions for the current bugs in play on the issues list that have not been resolved. Currently their is only one branch of angular-ui, which is the stable branch. The plan in the future is to have feature branches that are documented as unstable and one stable branch.

**Comment by isAlmogK** [comment]
Do you recommend working fromt the tag or the master branch?

**Comment by ProLoser** [comment]
We are generally careful not to merge into master broken code, but if you
work off of master you will have to build the files yourself. we only build
on each tag.

**Comment by isAlmogK** [comment]
Thanks will stay with the tag don't fill like building them each time. Closing this still having issues with the model even when I remove all my CSS and just bootstrap is that stable?
