### ISSUE TITLE
Twitter Bootstrap Model Issues 

### ISSUE THREAD

**Issue by isAlmogK** [angular-ui/angular-ui-OLDREPO#300]
So I had some issues with the Twitter Bootstrap Model, I finally got everything working I would suggest updating docs so other people don't run into this issue. 

On the docs you have the following How? and then in the code example you have the 

``` javascript
<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-modal.js"></script>
```

This is incorrect using the following javascript file the modal does not animate it. I went ahead and download the full bootstrap.js file. 

Also it's important to do that the order of the CSS files and JS file for bootstrap matter. 

There are other issues with the docs for example your not calling the correct modal.

**Comment by ProLoser** [comment]
Do you think you could open a Pull Request with the fixes? https://github.com/angular-ui/angular-ui.github.com

Would be amazingly appreciated!

**Comment by isAlmogK** [comment]
Yes of course will do it the mooring it's 2 am here, keep this open until I get done. Would be glad to join and help with docs, getting started guides, ect..

**Comment by ProLoser** [comment]
If you're going to be that awesome, feel free to take any creative liberties you wish with the docs. No good ideas get rejected around here, so if you want to add more pages or what-have-you for a startup guide, etc, feel free.

**Comment by andyczerwonka** [comment]
Any update on this? I'm having issues getting the modal dialog to work and I'm wondering if it's related.

**Comment by ProLoser** [comment]
@andyczerwonka this actually will be removed from AngularUI in the near future as it has been relocated to [angular-ui/bootstrap](https://github.com/angular-ui/bootstrap)

**Comment by andyczerwonka** [comment]
Yes, I solved my issue by going there and grabbing modal.js directive.
