### ISSUE TITLE
Twitter bootstrap responsive navbar not working when angular UI is included

### ISSUE THREAD

**Issue by habdelra** [angular-ui/angular-ui-OLDREPO#301]
It seems like the twitter bootstrap responsive navbar's "hamburger" button stops working when the angular UI modules are included in the page

**Comment by joshkurz** [comment]
is there any way you could provide a jsfiddle or plunker of this error? I have never seen this before.

**Comment by oliversalzburg** [comment]
@joshkurz Could be this https://github.com/angular/angular.js/issues/1674

**Comment by ProLoser** [comment]
@oliversalzburg that looks like an astute observation. @habdeira any chance you're still around to confirm this? If not perhaps someone can confirm that this indeed solves the problem.

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/bootstrap

Please reopen this issue there if it is still relevant.
