### ISSUE TITLE
datepicker is not closeable on IE

### ISSUE THREAD

**Issue by nidi3** [angular-ui/angular-ui-OLDREPO#302]
On IE, when you select a date, the calendar popup is not closed and stays open.

The problem seems to be line 31:
element.datepicker("setDate", element.val());

removing this line, the problem disappears and the datepicker still works.
What is this line supposed to do?

**Comment by petebacondarwin** [comment]
@nidi3 Have you tried removing it and running the unit tests?

**Comment by chrisjaure** [comment]
For reference, this test fails when removing that line:

```
uiDate should update the input field correctly on a manual update FAILED
Expected '2012-8-01' to equal '2012-08-01'.
```

**Comment by petebacondarwin** [comment]
I think this may be fixed in master but I haven't tried it. Can you check?
The change is to add 

```
element.blur();
```

after line 31.

**Comment by jeffnorris1** [comment]
adding that line doesn't fix the issue

**Comment by Graham-Foster** [comment]
Has this issue been addressed as of yet?

In my implementation the text input itself is readonly (allowing the date to only be selected through the popup) so I'm thinking the failing test referenced by chrisjaure wouldn't impact things too greatly and so removing line 31 may solve the problem until there is a real solution.

**Comment by nidi3** [comment]
As a workaround, I block the popup for some amount of time:

``` javascript
...
//prevent opening the popup for the next 1000ms, thank you IE8
$timeout(function () {
  opts.openable=true;
}, 1000);
opts.openable=false;
element.datepicker("setDate", element.val());
...
```

and

``` javascript
opts.beforeShow = function (element, instance) {
  return instance.settings.openable;
}
```

**Comment by chrisjaure** [comment]
Here's my solution. Replace line 32 with this:

``` javascript
// check whether the date needs to be set
if ($.datepicker.formatDate(element.datepicker('option', 'dateFormat'), date) !== element.val()) {
  element.datepicker("setDate", element.val());
}
```

All tests still pass last time I checked.

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-date

Please reopen this issue there if it is still relevant.
