### ISSUE TITLE
Codemirror directive not rendering due to "TypeError: Object [[object HTMLTextAreaElement]] has no method 'is'"

### ISSUE THREAD

**Issue by pearlchen** [angular-ui/angular-ui-OLDREPO#303]
I was trying to include the CodemMirror directive but kept on getting a:

```
"TypeError: Object [[object HTMLTextAreaElement]] has no method 'is'"
    at link (http://angular-ui.github.com/angular-ui/build/angular-ui.js:129:16)
```

When I dug deeper, `elm` was actually an Array. So this works:

```
// Only works on textareas
//if (!elm.is('textarea')) {
if (elm[0].type !== 'textarea') {
  throw new Error('ui-codemirror can only be applied to a textarea element');
}
```

Example:
http://jsfiddle.net/pearl/MLbW9/

However I don't get this error on the http://angular-ui.github.com/ webpage, where CodeMirror obviously works.

**Comment by ProLoser** [comment]
Interesting. You can either add jQuery or we can write out code for $.fn.is()  

## 

Dean Sofer

**Comment by pearlchen** [comment]
Oh! I see.... .is() is a jQuery method. 

I'll include jQuery but I think it would be good to clarify in the README requirements that jQuery _is_ an requirement.

"jQuery / Plugins (depends on directive). Check specific directive dependencies for more information" is vague and nothing led me to believe that jQuery was required for CodeMirror after digging around. (And seems strange, in this scenario, to require it only to test if something is a textarea or not.)

Thanks.

**Comment by michaelahlers** [comment]
I still think this is an issue&mdash;I ran into this problem, even having jQuery loaded prior to Angular UI. The following patch to `angular-ui.js` fixes it. (Using AngularJS 1.1.2, Angular UI 0.3.2, and jQuery 1.9.0.)

``` diff
@@ -678,7 +678,7 @@
     require: 'ngModel',
     link: function (scope, elm, attrs, ngModel) {
       // Only works on textareas
-      if (!elm.is('textarea')) {
+      if (!$(elm).is('textarea')) {
         throw new Error('ui-codemirror can only be applied to a textarea element');
       }
```

**Comment by ProLoser** [comment]
That.... doesn't make sense. An angular element === jQuery element

**Comment by joseym** [comment]
@michaelahlers - I'm confused, `elm` should be a jQuery object already. That's like wrapping jquery in jquery.

**Comment by ajoslin** [comment]
Why not just do if (elm[0].tagName.toLowerCase()=='textarea' and fix the is problem?

**Comment by ProLoser** [comment]
Doesn't CodeMirror have a jquery dependency?

**Comment by ProLoser** [comment]
Guess not

**Comment by ProLoser** [comment]
@ajoslin is `tagName.toLowerCase()` better than `type`?

**Comment by ProLoser** [comment]
https://github.com/angular-ui/angular-ui/commit/c10e0a1d35b466cd3a18148b6b49cf99d4948953#L0R14

**Comment by ajoslin** [comment]
I don't really know what `type` is.. there's no documentation for it on mdn lol https://developer.mozilla.org/en-US/docs/DOM/element

**Comment by michaelahlers** [comment]
@joseym, that confuses me, too. However, AngularJS by itself, with its &ldquo;[jQuery lite](http://docs.angularjs.org/api/angular.element)&rdquo; implementation, is not documented to provide the `is` function on element objects (and no such function appears in the code base). One way or another, this code depends on a proper jQuery object.

**Comment by joseym** [comment]
interesting... rather than passing a jquery object to jquery you could pass the dom element to jquery with `elm[0]`

**Comment by ProLoser** [comment]
@joseym i will smack you if you do that. You  don't LEAVE jQuery just to go back into it. It's just as redundant.

@michaelahlers: you are correct, and I assumed CodeMirror depends on jQuery but I was wrong. The code has already been refactored to remove this dependency. If you're wrapping angular elements in jquery elements though then you're doing it wrong. Correct your lib import order and angular will just use jQuery INSTEAD of jqlite.

**Comment by pearlchen** [comment]
Not important anymore but `type` is a property of HTML inputs, e.g. textareas and input fields. 

However, `tagName.toLowerCase()` is probably best used since someone might try applying CodeMirror to a `div`.

**Comment by michaelahlers** [comment]
@ProLoser, I was never proposing that as a solution.

**Comment by ProLoser** [comment]
@pchen I just learned something new!

@michaelahlers, no worries, I was mostly joking in what I was saying to @joseym anyway.

**Comment by michaelahlers** [comment]
@ProLoser, yo dawg, I heard you like jQuery! So I used $(jQuery) to wrap your $($(jQuery)) in a $($($(jQuery))).

**Comment by Darkein** [comment]
Hi guys!
I had the same problem but with the "on" function (lines 152 and 158  in angular-ui.js). I fixed it by surrounding 'codeMirror' with angular.element().

**Comment by Darkein** [comment]
Nevermind. I corrected the problem by updating codemirror to the latest version
