### ISSUE TITLE
ui-virtualize directive

### ISSUE THREAD

**Issue by orneryd** [angular-ui/angular-ui-OLDREPO#306]
In working on ng-grid I am going to be writing a directive for virtualizing the scrolling for any element's children.

the general idea is that the ui-virtualize directive would be either a class or attribute and take all of the elements inside, get their measurements and coordinates, find out if they would be overflowing and keep the elements in memory until they would become visible due to scrolling. 

I believe this would be highly useful for applying to tables/grids or lists that have lots of potential elements.

Feel free to flame if I am just thinking silliness.

**Comment by petebacondarwin** [comment]
+1

**Comment by moperacz** [comment]
+1

**Comment by ajoslin** [comment]
+1:+1:

**Comment by mfeingold** [comment]
check this out https://github.com/Hill30/NGScroller
