### ISSUE TITLE
angular-ui breaks non-modal bootstrap dismiss

### ISSUE THREAD

**Issue by emkman** [angular-ui/angular-ui-OLDREPO#310]
We have a rails flash message that looks like this:

```
<div class="alert alert-success">
    <a class="close" data-dismiss="alert">×</a>
    <div id="flash_notice">Successfully authenticated from Facebook account.</div>
</div>
```

bootstrap.js allows this to automatically be dismissed by clicking the x, however including angular-ui.js breaks this functionality. Is there another attribute I can add to make this work? I only see examples in angular-ui relating to modal dialogs, which do still work for us.

**Comment by ProLoser** [comment]
There is no reason why this would be occurring. If you provide a simple fiddle or plunker demo demonstrating this issue it will make it easier for us to address this issue.

**Comment by rogeralsing** [comment]
it also breaks modal data-dismiss in dialogs, close buttons with data-dismiss on will not close the dialog
