### ISSUE TITLE
Tabindex for Select2

### ISSUE THREAD

**Issue by rodem** [angular-ui/angular-ui-OLDREPO#311]
In example: http://plnkr.co/edit/2LGl9c9plI2YjRFU2m0m?p=preview
If only keyboard navigated do follow:
1. select with mouse "input1"
2. hit "tab" - focus jumps to select2.
3. press "down arrow" and select any value in list, hit tab to "input2"
4. pressing "shift-tab" to go back to select2 skips it and goes to "input1", have to focus on select2
5. select2 becomes unaccesible from keyboard navigation

Problem dissapears if select2 has "tabindex" attribute even without value.

**Comment by ProLoser** [comment]
Is this a bug with angular ui or with select2 itself? If it's the latter then you should close this ticket and instead open one on that project.

**Comment by rodem** [comment]
Sorry seems Select2 3.2 bug.
