### ISSUE TITLE
CodeMirror support broken with version 3.0

### ISSUE THREAD

**Issue by prasad83** [angular-ui/angular-ui-OLDREPO#312]
onChange handler is not getting triggered with codemirror 3.0 which breaks ui-codemirror model update.

The fix below worked:

``` js
codemirror = CodeMirror.fromTextArea(elm[0], options);
// Bug fix - for codemirror 3
if (typeof codemirror.on == 'function') {
    codemirror.on('change', onChangeHandler);
}
```

**Comment by ProLoser** [comment]
So definitely seems that there was a breaking API change with CodeMirror.

My question is should we reflect this by breaking support for v2 with this change?

**Comment by ProLoser** [comment]
Nevermind looks like your proposed fix is non-destructive. Have you thought of opening a PullRequest with the fix in the future?

**Comment by douglasduteil** [comment]
Yep I had the same problem. Here is how I solved it...
Demo : http://jsbin.com/aqecex/2/
Code : https://gist.github.com/2a00bea5db6293b6f4b3

**Comment by ProLoser** [comment]
@douglasduteil want to open a PR with the fix?

**Comment by douglasduteil** [comment]
Sure, why not :)
But it's not really fixed...
It seems like after the connection is done the compiler just don't care about the rest... 

Demo : http://jsbin.com/aqecex/5/

**Comment by douglasduteil** [comment]
K !
This only occurs in the parent node !
Demo : http://jsbin.com/aqecex/6/
