### ISSUE TITLE
New code editor : ACE 

### ISSUE THREAD

**Issue by douglasduteil** [angular-ui/angular-ui-OLDREPO#317]
### I started working on adding [ACE](http://ace.ajax.org/) to AngularUI.

[Demo (broken)](http://jsbin.com/eperos/1)
It's doing great but I still question myself about the _good_ way to inline the options in the HTML.
- CodeMirror have a syntax like :  

``` html
<textarea ui-codemirror="{lineWrapping : true, theme:'ambiance', onChange:work}" ng-model="input"></textarea>
```
- I'm proposing that for ACE : 

``` html
<ui-ace  ng-model="input" mode="css "  onchange="changeInfo" show-gutter use-wrap-mode></ui-ace>
and
<div ui-ace  ng-model="input" mode="css" [...] ></div>
```

What you think ?

**Comment by petebacondarwin** [comment]
I think for options that are required or used all the time it is helpful
and clearer to have them in their own attribute.
For all other options, especially rarely used one, then it is nice to have
them in a config object like ui-codemirror.  This also makes it easier to
pass in and modify the config programmatically.

**Comment by ProLoser** [comment]
@douglasduteil did you drop this in support of codemirror? If so should we close this?

**Comment by douglasduteil** [comment]
@ProLoser Yes. Sorry. I just did a pull request with what I did. #435
