### ISSUE TITLE
Select2 - Upgrading to v3

### ISSUE THREAD

**Issue by RobertLowe** [angular-ui/angular-ui-OLDREPO#32]
Hey,

The latest HEAD of select2 (v3?) supports optgroups and seems to work fine with angular-ui.

Cheers

**Comment by ProLoser** [comment]
So... you want to update the version on the demo page? You are already free to use whatever version you wish, but if you want to update the demo page then fork and send a pull request. You can even do it [in-browser on github](https://github.com/angular-ui/angular-ui.github.com/edit/master/index.html)!

**Comment by ProLoser** [comment]
I think I always use the master branch (he's been pretty good about keeping it stable) so we're already showing v3. I'm gonna go ahead and close this.
