### ISSUE TITLE
DatePicker README incorrect

### ISSUE THREAD

**Issue by bdefore** [angular-ui/angular-ui-OLDREPO#320]
Note that adding ui.directives.date to the angular.module call causes an error, but adding ui.directives does not:

http://jsfiddle.net/pkozlowski_opensource/aGpNf/6/

**Comment by petebacondarwin** [comment]
Good point.  This was from the days when I was putting all my directives
into their own modules :-)

**Comment by petebacondarwin** [comment]
Fixed in 67d10aee5d70da7b8b142e3056fdf83d4faaca98
