### ISSUE TITLE
Integrate prettyCheckable

### ISSUE THREAD

**Issue by nilskp** [angular-ui/angular-ui-OLDREPO#321]
Integrate the good lookin' checkbox plugin http://arthurgouveia.com/prettyCheckable/

**Comment by petebacondarwin** [comment]
If you take their images and css it would not be hard to do this in pure
angular using ng-click.

... sent from my tablet

**Comment by ProLoser** [comment]
Any reason this won't work with `ui-jq`?

**Comment by nilskp** [comment]
Haven't tried using ui-jq, but it seemed like a good component to integrate. If not, just close this issue.

**Comment by nilskp** [comment]
Wow, that was easy :-)

Thanks.

**Comment by nilskp** [comment]
I guess I was too quick, because ng:change is no longer triggered, presumably because these types of ui mods changes the underlaying DOM. In this case the checkbox is hidden and the graphical checkbox is overlayed. It does programmatically set the "checked" attribute, but somehow Angular isn't picking that up to trigger ng:change.

**Comment by nilskp** [comment]
I'm reopening, even though I'm not sure if this is a problem with angular-ui or not. The code does invoke the JQuery change() method, which presumably ought to trigger the ng:change method, but does not.

**Comment by arthurgouveia** [comment]
Hello, @nilskp! 

I'd love to help on integrating the plugin on angular-ui, but as I've never worked with it, I'm not sure where or how I could be of any help.

Maybe if you can give a working example of the problem, I might be able to help either by modifying the JS that would be inserted on the project for the prettyCheckable implementation or giving you a workaround to do what you need.

Let me know what you think. Thanks!

**Comment by nilskp** [comment]
I'm not sure I know enough about Angular and/or prettyCheckable, nor do I have the time, to be of much help. 

From looking at the source code, prettyCheckable hides the real checkbox and displays a nicer looking one. When clicked it delegates the call to the real checkbox and calls jQuery `change()` method, which ought to trigger a change event that is picked up by Angular. Why that doesn't happen, I'm not sure.

HTH.

**Comment by ProLoser** [comment]
This project is discontinued. Please reopen on angular-ui/ui-utils if it's still relevant.
