### ISSUE TITLE
ui-sortable update function is never called

### ISSUE THREAD

**Issue by jilljenn** [angular-ui/angular-ui-OLDREPO#322]
I can't make the update function work.
http://jsfiddle.net/Le_Sphinx/YcwWW/

This implementation seems to work though:
http://jsfiddle.net/7eTMV/20/

Am I doing something wrong?

**Comment by ProLoser** [comment]
If you look at the source code (instead of working with a minified version) you will find that `ui-sortable="whatever"` is completely ignored (oddly) and instead `ui-options` is used instead.

Really need to touchup this directive and add docs.

**Comment by jilljenn** [comment]
Sorry, I actually looked at the code but didn't notice it. Thanks.
