### ISSUE TITLE
Integration with x-editable

### ISSUE THREAD

**Issue by sarbogast** [angular-ui/angular-ui-OLDREPO#324]
It would really be magical if angular-ui could integrate x-editable (http://vitalets.github.com/x-editable/index.html) with angularjs in a standard way. I've been tinkering with that for a few days but I don't understand enough of how directives work to get it rolling as it should. I would really love to have a directive that makes any text element editable and allows me to call a controller function when the change is committed.

**Comment by ProLoser** [comment]
This looks like it should work pretty easily with the pass through
directive. You should try testing it with that first. It's the first
directive on the demo page.

**Comment by sarbogast** [comment]
I'm trying it out here: http://jsfiddle.net/sarbogast/b2dZ6/

But as you can see, it doesn't quite work as expected when the editable value is data-bound. Is there a way to make it work or is it a case of "requires a directive"?

**Comment by ProLoser** [comment]
Actually I tried slapping together a directive and I can't seem to figure out why the model is not reflecting the changes: http://jsfiddle.net/b2dZ6/2/

Feel free to play around with it.

**Comment by moperacz** [comment]
scope.apply made it work...

http://jsfiddle.net/n8K39/

**Comment by ProLoser** [comment]
/me facepalms.  

Duh. Completely forgot.

Now the question becomes should we merge this into the core, come up with some super versatile directive that can tackle editable, or just let you use your own implementation?

I guess it can't hurt for you to create a branch on your own fork and open a pull request with this code, but it will have to abide by our coding requirements and try to put together some unit tests and a dependencies.json.

It should also be compatible with uiConfig like all our other directives are and rename it to uiEditable or something under the proper namespace.  

## 

Dean Sofer
DeanSofer.com
714.900.2254

**Comment by sarbogast** [comment]
Thanks a lot dudes. I'll play with it for a while to see how it integrates with my real use case and try to open a pull request afterwards.

**Comment by sarbogast** [comment]
I'm currently playing with this directive and I've come to realize that I need to plugin into the save event in order to send the modified data to the server right away. How can I modify this directive (http://jsfiddle.net/n8K39/) so that I can write something like this?

``` html
<span editable="{emptytext:''}" ng-model="action.startTime" save="sendToServer(action, 'startTime')"></span>
```

**Comment by ProLoser** [comment]
Don't bother. Just do $scope.$watch() if you REALLY want to do immediate AJAX.  

## 

Dean Sofer
DeanSofer.com
714.900.2254

**Comment by ProLoser** [comment]
@shantanuw You'll have to provide a demo of your problem since this isn't officially in AngularUI right now. It also may be more relevant to relocate this discussion to the google group.

**Comment by shantanuw** [comment]
Did you get it working with the "select" option? I am trying to get this working:
    `<span editable ng-model="team.name" data-source="team/values" data-value="team.name"></span>`
The select shows up but the value shows as "Empty"

**Comment by shantanuw** [comment]
Sorry could not get the code in the first time

**Comment by sarbogast** [comment]
I did not test it with the select option because I don't like it anyway. But I spoke with the developer of x-editable and he says he might implement a Select2 integration in a future version: https://github.com/vitalets/x-editable/issues/59

**Comment by ProLoser** [comment]
I feel like it's a bigger waste of time trying to hack this plugin to work than it would have taken for you to reproduce the plugins functionality from scratch in pure angular as a DSL directive.

```
<a ng-click="edit=true">{{value}}</a>
<div class="floating">
  <input ng-model="value" ui-keypress="{enter:'edit=false'}">
</div>
```

## 

Dean Sofer
DeanSofer.com
714.900.2254

**Comment by ghost** [comment]
I added a simple fix to bootstrap-editable.js render function. That also fixes "Empty" value.

```
    render: function(response) {
        //do not display anything
        if(this.options.display === false) {
            return;
        }

        //if input has `value2htmlFinal` method, we pass callback in third param to be called when source is loaded
        if(this.input.value2htmlFinal) {
            return this.input.value2html(this.value, this.$element[0], this.options.display, response); 
        //if display method defined --> use it    
        } else if(typeof this.options.display === 'function') {
            //HERE: SET VALUE WITH DISPLAY CALLBACK RESULT
            var result = this.options.display.call(this.$element[0], this.value, response);
            return this.input.value2html(result, this.$element[0]);
            //return this.options.display.call(this.$element[0], this.value, response);
        //else use input's original value2html() method    
        } else {
            return this.input.value2html(this.value, this.$element[0]); 
        }
    },
```

**Comment by zzal** [comment]
Maybe it's a good thing to point out that x-editable is not only about “Click-to-edit” text fields, but does a lot more very elegantly.

**Comment by mranosa** [comment]
bump! so did someone create a directive for this already? :)

**Comment by ghost** [comment]
Just found someones working example http://jsfiddle.net/mahbub/XRL4U/

**Comment by eoliphan** [comment]
Any word on this getting perhaps an 'official' integration? or a native implementation (though x-editable is already awesome sauce). I've tried some of the jsFiddles.  THis one is cool http://jsfiddle.net/mahbub/XRL4U/, but it appears that x-editable doesn't understand/handle nested properties.  It wasn't working for me.  So I just replaced the "person_name" in the example with a new scope var "$scope.person = {name:"blah"}, and changed the refs to person.name and it breaks the same way.

**Comment by BirdInTheCity** [comment]
I'm also interested in seeing an Angular UI official integration.  I've been playing around with this JSFiddle and while it's somewhat functional, I'm still running into a bunch of problems that I've tried and failed to solve.

This seems to be the best one yet:  http://jsfiddle.net/XRL4U/8/

**Comment by edjafarov** [comment]
I had created click to edit directive. http://jsfiddle.net/djkojb/b4LVK/ You can just click on text and edit it - without popups. The text will be just editable without any design changes.

**Comment by wesleycho** [comment]
This repository is discontinued.

As a note, this is something that is extremely easy to recreate in Angular while making use of a plugin like `angular-ui/bootstrap` with a far smaller footprint than integrating with this existing plugin.  This has the advantage of allowing you to customize your edit popover however you like.

**Comment by vitalets** [comment]
Official port of x-editable for angular:
http://vitalets.github.io/angular-xeditable/
feedback welcome.
