### ISSUE TITLE
modal dialog not working with Bootstrap 2.2.2

### ISSUE THREAD

**Issue by andyczerwonka** [angular-ui/angular-ui-OLDREPO#327]
I hope this isn't a false positive, but I can't see to get the modal dialog to work. I started with the raw bootstrap dialog. I then migrated it to the example of the demo page. The whole page goes modal, but I get no dialog. Is there a jsFiddle or some working example I can follow to make sure I have it right?

**Comment by pkozlowski-opensource** [comment]
@andyczerwonka Andy, we are migrating bootstrap-specific directives to a separate repository here: https://github.com/angular-ui/bootstrap

The directives in this repo don't have _any_ dependency on the bootstrap's JavaScript so should work with most of the versions without any issues. I'm just working on the demo page, you can see the preview of it here:
http://ci.angularjs.org/job/angularui-bootstrap/ws/dist/index.html

**Comment by andyczerwonka** [comment]
Cool! Should I just grab

https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js

and go from there?

**Comment by pkozlowski-opensource** [comment]
yep, this is all what you should need (2.15kB, no-minified) :-)

**Comment by andyczerwonka** [comment]
Hmnnn.. strange. It's not working. I removed the bootstrap.js, added modal.js and copy & paste your example from http://ci.angularjs.org/job/angularui-bootstrap/ws/dist/index.html

The div contents are rendering right on the page.

**Comment by pkozlowski-opensource** [comment]
I presume that you didn't add dependency on a module:

`var app = angular.module('yourModule', ['ui.bootstrap.modal']);`

Anyway, here is a working plunk: http://plnkr.co/edit/a0kIUDEpkOofGkAG6xid?p=preview

**Comment by andyczerwonka** [comment]
Oops... still new to Angular... sorry to waste your time. Once I added the module dependency, all it working just fine.

**Comment by pkozlowski-opensource** [comment]
Cool, glad that it worked :-) 

It just shows that we need to add info about this module dependency!

**Comment by danielzzz** [comment]
hi, I have the same problem with angular (angular, angular-mobile) 1.1.5 and bootstrap 2.3.2
I have checked the solutions proposed above, but they did not work for me.
I am getting the modal fade, but no dialog...
what else could cause the problem?

moreover, this plunk from above is no longer working:
http://plnkr.co/edit/a0kIUDEpkOofGkAG6xid?p=preview

**Comment by danielzzz** [comment]
I have opened a new issue with this one.
