### ISSUE TITLE
ui-date-format not working?

### ISSUE THREAD

**Issue by h0ru5** [angular-ui/angular-ui-OLDREPO#329]
Hi,

When trying to use ui-date with iso-format by using ui-date-format no effect is noticable. seems broken.

see also http://jsfiddle.net/zv2n8/24/

**Comment by petebacondarwin** [comment]
If you use ui-date-format then you must pass a string in the model.

Pete
...from my mobile.

**Comment by h0ru5** [comment]
Tried around with passing strings as format as well as strings instead of date, but no success.
see also: http://jsfiddle.net/zv2n8/34/

but i did get a working solution by passing it like that: ui-date="{'dateFormat' : 'yy-mm-dd'}", of course i could also use ui.conf.

**Comment by petebacondarwin** [comment]
If you don't use ui-date-format then ui-date accepts a Date object in the
model. The ui-date-format is purely about shaving a string in the model.
The config you have used is only for configuring the jquery date picker. In
particular the format in which the date is displayed in the input box.

Pete
...from my mobile.

**Comment by ProLoser** [comment]
ui-date-format does not currently accept a variable, it takes plaintext and expressions: `ui-date-format="{{fmt}}"`

You are also setting the value to an object, and as pete stated, you can't set the value to an object with ui-date-format active.
