### ISSUE TITLE
Potential bug in date.js

### ISSUE THREAD

**Issue by fingermark** [angular-ui/angular-ui-OLDREPO#330]
I was looking at the code in [date.js](https://github.com/angular-ui/angular-ui/blob/master/modules/directives/date/date.js) and noticed on line 27 that it checks if `controller` exists.  then on line 65 it calls a method of `controller`, regardless if `controller` exists or not.  so, if `controller` may not exist, shouldn't there be a check?  furthermore, the method it calls, `$render`, seems to be defined in the if block, started on line 27.

**Comment by petebacondarwin** [comment]
Thanks @fingermark, this is incorrect but doesn't show up as it is the last line in the function and the $watch swallows the exception that it causes.  Seems it this bug appeared when the directive was converted from coffeescript.

I have fixed and landed in e67bbce5ad3b3e924391530d3142ef7e8c83f1d9
Thanks for noticing.
