### ISSUE TITLE
Inflector example seems to be broken

### ISSUE THREAD

**Issue by scottromack** [angular-ui/angular-ui-OLDREPO#332]
in the app.js

function InflectorCtrl($scope) {
    $scope.inflectorText = 'Here Is my_phoneNumber';
    $scope.inflectorType = 'humanize';
}

in the demo page there are options for
     Humanize (Default)
     Underscore
     Variable

but nothing happens, no errors are thrown that I can see.

**Comment by scottromack** [comment]
Oh, the paragraph was commented out for some reason..

around line 938

<p>{{inflectorText|inflector:inflectorType}}</p>

**Comment by ProLoser** [comment]
Fixed angular-ui/angular-ui.github.com#28
