### ISSUE TITLE
Please consider a directive for Galleria

### ISSUE THREAD

**Issue by robertjchristian** [angular-ui/angular-ui-OLDREPO#334]
It would be great to have built-in support for galleria (http://galleria.io/), particularly (a) multiple themes, and (B) the ability to update (bind) galleries when the model changes.  Also appears to be a little bit of chicken and egg due to the fact that ng hides divs (ways around this but not completely intuitive).

**Comment by dandoyon** [comment]
Nice library, the team has been focusing on bootstrap, carousel was committed a few days back. 

https://github.com/angular-ui/bootstrap/tree/master/src/carousel

This does look a lot nicer and more feature rich.

**Comment by wesleycho** [comment]
This repository is discontinued, I recommend opening a new issue in the `angular-ui/bootstrap` repository if you still would like to make this feature request.
