### ISSUE TITLE
ui-keypress demo fails in every browser except recent Firefox

### ISSUE THREAD

**Issue by jbeard4** [angular-ui/angular-ui-OLDREPO#335]
Steps to reproduce:
1. Navigate to angular-ui keypress demo in recent Chrome, Safari, Opera or IE9 on Windows 7: http://angular-ui.github.com/#directives-keypress
2. Press Enter in any of the three text areas.

Expected behavior: An alert box should open.

Actual behavior: An alert box does not appear.

**Comment by ProLoser** [comment]
Works for me. Maybe clear your cache?

## 

Dean Sofer
DeanSofer.com
714.900.2254

**Comment by jbeard4** [comment]
It was our corporate firewall blocking some scripts. Firefox was the only browser using a proxy.
