### ISSUE TITLE
ui-revert not working in IE8

### ISSUE THREAD

**Issue by pc-dedelhart** [angular-ui/angular-ui-OLDREPO#337]
Works in ie9, not in ie8

tested on paralllels / ie9 in 8 emulation

**Comment by ProLoser** [comment]
Do you mean ui-reset? I'm not familiar with a revert directive.

If so, you'll need to give more context. Is the extra HTML generated and the CSS just broken? Or what?

**Comment by pc-dedelhart** [comment]
Yes - but it is my bad - my link to the ie8 shim was badly formed
