### ISSUE TITLE
Request: can reset not show the "X" if there is nothing to reset?

### ISSUE THREAD

**Issue by pc-dedelhart** [angular-ui/angular-ui-OLDREPO#338]
Optionally perhaps, but I'd like to be able to hide the "X" when the content is already "as it would be if you clicked 'X'".

In the normal case this would be, if the model is blank. In the case of a value'd "reset" the x should be visible only if the content != the value of ui-reset. 

I realize you can do this with your own ng-css directive etc. but it seems a pretty common use case.

**Comment by ProLoser** [comment]
Feel free to open a pull request with the change, it should be fairly easy.

**Comment by pkozlowski-opensource** [comment]
@ProLoser I was just typing exactly the same message :-)

@pc-dedelhart Dave, it is a good directive to start contributing to angular-ui :-)
