### ISSUE TITLE
Directive for Pagination 

### ISSUE THREAD

**Issue by ramandv** [angular-ui/angular-ui-OLDREPO#339]
A directive for pagination might be useful for many angular-ui users. I have developed some simple plnkr for it. [Code is just functional, yet to be refactored]

``` javascript
 <div ui-pagination 
             total-pages="{{pagination.totalPages}}"  
             max-page-numbers-to-display="{{pagination.maxPageNumbersToDisplay}}"  
             current-page="pagination.currentPage"></div>
```

http://plnkr.co/edit/uUggX3O0sB9x7e6Xy97P?p=preview

Any suggestions on this feature?

**Comment by pkozlowski-opensource** [comment]
@ramandv We've got already a pagination directive in the bootstrap repository. Demo is here:
http://angular-ui.github.com/bootstrap/#/pagination

and the source code:
https://github.com/angular-ui/bootstrap/tree/master/src/pagination

This directive, although in the bootstrap-specific repository, can be fully customized (see its template here: https://github.com/angular-ui/bootstrap/blob/master/template/pagination/pagination.html
which means that you could prepare a custom template for this directive to suit your particular needs.

Have a look and open an issue (or better yet - a pull request!) if you feel like anything is missing.
