### ISSUE TITLE
Error: Cannot find module 'testacular'

### ISSUE THREAD

**Issue by KevinOrtman** [angular-ui/angular-ui-OLDREPO#342]
require('testacular'); in grunt.js is generating the following error.  
I can repro this in both linux (oel 6) and windows 7.   I have confirmed that testacular is working if I run it in stand-alone (testacular init/testacular server rather than grunt server).
### output

 [kevin]$ grunt
 Loading "grunt.js" tasks and helpers...ERROR
 Error: Cannot find module 'testacular'
 <WARN> Task "default" not found. Use --force to continue. </WARN>

Aborted due to warnings.
### module versions

testacular@0.4.0 
grunt@0.3.17
coffee-script@1.4.0

**Comment by KevinOrtman** [comment]
Verbose output:

Reading "grunt.js" config file...OK
Loading "grunt.js" tasks and helpers...ERROR
Error: Cannot find module 'testacular'
     at Function.Module._resolveFilename (module.js:338:15)
     at Function.Module._load (module.js:280:25)
     at Module.require (module.js:362:17)
     at require (module.js:378:17)
     at Object.<anonymous> (/home/kevin/src/angular-ui/grunt.js:1:80)
     at Module._compile (module.js:449:26)
     at Object.Module._extensions..js (module.js:467:10)
     at Module.load (module.js:356:32)
     at Function.Module._load (module.js:312:12)
     at Module.require (module.js:362:17)

**Comment by pkozlowski-opensource** [comment]
@KevinOrtman did you install testacular as a local npm module?

**Comment by KevinOrtman** [comment]
Good question.  No, installed globally.

sudo /usr/local/bin/npm install -g testacular coffee-script grunt

**Comment by ProLoser** [comment]
Run `npm install` too.

**Comment by pkozlowski-opensource** [comment]
@KevinOrtman yeh, as it stands today you need to install it locally as well as described in https://github.com/angular-ui/angular-ui:

`npm install`

We could eventually to change this to follow the same pattern as in the boostrap repo: https://github.com/angular-ui/bootstrap/blob/master/grunt.js#L172

**Comment by KevinOrtman** [comment]
_blush_  total RTFM moment there.  Thanks guys!

**Comment by mirontoli** [comment]
Thank you @KevinOrtman! It helped, too. So not really blush total.  Maybe it should stand in the README: run `npm install` as well
