### ISSUE TITLE
CodeMirror onChange event not fired

### ISSUE THREAD

**Issue by AlanFoster** [angular-ui/angular-ui-OLDREPO#343]
Using CodeMirror 3.0+ with the current version of AngularUi from the build directory doesn't trigger onChange events for some reason.

Because of this the model binding/$apply() doesn't seem to occur when the textArea is changed either.
Has the CodeMirror API changed perhaps?

**Comment by AlanFoster** [comment]
After checking out CodeMirror 3.0+ examples, I see you now need to bind events like:

```
  editor.on("change", function() {
    ...
  });
```

Am I right in saying this? If so, I wonder what the best way to fix this problem is? Either abstracting this change and wiring up the events ourselves or break backwards compatibility and change how these events should be registered.
Or potentially CodeMirror is supposed to support this and it's just a small bug..

**Comment by AlanFoster** [comment]
I've investigated this further, and I notice that all of the versions seem to be different for CodeMirror?
The [AngularUi](http://angular-ui.github.com/) site seems to have

```
CodeMirror.version = "2.34 +";
```

But the [dependencies file](https://github.com/angular-ui/angular-ui/blob/master/modules/directives/codemirror/dependencies.json) seems to point to the newest CodeMirror 

``` javascript
    {
        "core": [ "jquery" ],
        "internal": [],
        "external": [
            "http://codemirror.net/lib/codemirror.js",
            "http://codemirror.net/lib/codemirror.css",
        ]
    }
```

What version is used when running against tests?

**Comment by ProLoser** [comment]
We _should_ be doing everything against the latest version ideally.

**Comment by AlanFoster** [comment]
Thanks for your reply @ProLoser!
I looked around a bit more and noticed that the ['build' folder's code](https://github.com/angular-ui/angular-ui/blob/master/build/angular-ui.js#L673) is completely different to the [individual CodeMirror Module's code](https://github.com/angular-ui/angular-ui/blob/master/modules/directives/codemirror/codemirror.js). 

I wonder if that's intentional or not, does the build folder only get commited to on major releases perhaps?

**Comment by ProLoser** [comment]
#412
