### ISSUE TITLE
draggable markers for google map?

### ISSUE THREAD

**Issue by coffee-tech** [angular-ui/angular-ui-OLDREPO#344]
Can someone tell me how to create draggable markers in gmap?

**Comment by revolunet** [comment]
Google MarkerOptions objects has a `draggable` property, see https://developers.google.com/maps/documentation/javascript/reference?hl=fr#MarkerOptions

Se just add this property when initialising the marker, eg :

``` js
$scope.myMarkers.push(new google.maps.Marker({
    map: $scope.myMap,
    position: $event.latLng,
    draggable: true
}));
```

**Comment by coffee-tech** [comment]
well, the problem is that the dragging event is not handled

**Comment by revolunet** [comment]
If you look the google docs, there's no dragging event at all : only drag, dragend, dragstart.

**Comment by coffee-tech** [comment]
I didn't know that. I'll see more. Thanks a lot
