### ISSUE TITLE
Anchors no longer dismiss bootstrap modals following upgrade to 1.0.3/0.3.2.

### ISSUE THREAD

**Issue by adam77** [angular-ui/angular-ui-OLDREPO#345]
Interestingly, button elements work fine.
(if you point me at an example fiddle with angularui in it, i will attempt to modify it to demonstrate).

**Comment by adam77** [comment]
Tracked the problem down to this:

https://github.com/angular/angular.js/commit/c81d8176cc55cd15acae05259ead73f90a01f0b7

So angular 1.0.3 is the problem not angular-ui, apologies.

**Comment by pkozlowski-opensource** [comment]
@adam77 yes, this is regression in AngularJS 1.0.3. This commit was already reverted in master, should be fixed in 1.0.4.
