### ISSUE TITLE
Add uiDateFormat to ui.config

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#349]
Should let people do something like:

```
module().value('ui.config', {
  date: {
    dateFormat: 'yy/mm/dd' // for ui-date which formats the input box (view)
  },
  dateFormat: 'yy/mm/dd' // for ui-date-format which formats the model
});
```

**Comment by petebacondarwin** [comment]
Good idea.

**Comment by ProLoser** [comment]
So I was about to tackle this as I considered it fairly trivial and then I realized a few major questions arise:
- When ui-date-format="" you default to ISO.
  - Conflicts with doing `<input ui-date ui-date-format>` as a way to trigger the uiConfig value
  - If requiring `ui-date-format` to use uiConfig value, this allows you to still fall back to using an object by default
- Should I ONLY use uiConfig if you don't specify uiDateFormat?
  - How then do you override it and use an object? (opt-out)

**Comment by petebacondarwin** [comment]
So `ui-date-format` is a completely separate directive to `ui-date` so we don't need worry about `ui-date` (in case you were).  It doesn't have any of these issues.

I would suggest that if you specify a `uiConfig.dateFormat` value then this is what is used when the `ui-date-format` attribute has no value.  So the check would simply be:

```
var dateFormat = attrs.uiDateFormat || uiConfig.dateFormat;
if ( dateFormat ) {
  // Use it
} else {
  // Use ISO date format
}
```

If the developer wants to use `uiConfig.dateFormat` generally but then override this to be ISO for just one input then they would have to enter the format string manually.

**Comment by ProLoser** [comment]
I added the code as you described, however I kept running into difficulty trying to write a unit test for it. How can I override ui.config in just 1 test?

**Comment by petebacondarwin** [comment]
Will take a look now.  A new injector is created for each unit test so we should be able to provide a different uiConfig for a specific test

**Comment by ProLoser** [comment]
Danke with the help. I realize I have not been on top of keeping the commits and logs squashed. I've been so tired and backed up with trying to get v0.4.0 that I haven't really been worrying about it. I figured it was more important to keep this project moving along.
