### ISSUE TITLE
Problem with ng-class and Select2

### ISSUE THREAD

**Issue by murilobr** [angular-ui/angular-ui-OLDREPO#352]
There is a problem with Select2 and ng-class, because ng-class is changed just inside select and not on the div created to emulate a select box.

Add to directive uiSelect2 the following code:

scope.$watch(attrs.ngClass, function(newVal, oldVal) {
          elm.prev().addClass(newVal);
          elm.prev().removeClass(oldVal);
        });

I will create a pull request.

**Comment by ProLoser** [comment]
Unless you can provide an explicit use-case in which this would be necessary instead of simply putting the class on the container, I'm going to close this issue
