### ISSUE TITLE
Make Google Maps Responsive

### ISSUE THREAD

**Issue by saden1** [angular-ui/angular-ui-OLDREPO#354]
I would like to put the canvas inside a span4 div and have it fill out the div and be responsive as the window is re-sized. I have tried quite a few things and I'm not even sure if it's possible to make the Google Maps canvas responsive.

**Comment by ProLoser** [comment]
Why not put `span4` on the canvas? I don't see any reason why you can't set the dimensions explicitly on the map element.

**Comment by ProLoser** [comment]
You will need to supply a demo as it works fine for me.

**Comment by scottromack** [comment]
You can make the map 100%.
see the simple example.

https://developers.google.com/maps/documentation/javascript/tutorial
