### ISSUE TITLE
Select2 and values other than strings

### ISSUE THREAD

**Issue by pablocaselas** [angular-ui/angular-ui-OLDREPO#355]
Hello,

Select2 directive it's not supporting boolean values as options which I think is quite common.

We fixed this for our project by using parsers and formatters inside the directive like this...

I think at least true or false should be included, and maybe the same for numbers.

<pre>
....
 if (controller) {
        controller.$parsers.push(function(value){
                if("true"===value) return true;
                if("false"===value) return false;
                return value;
        });
        controller.$formatters.push(function(value){
                if(true===value) return "true";
                if(false===value) return "false";
                return value;
        });
     ....
}
</pre>

**Comment by ProLoser** [comment]
What about working with a true or false string and just converting it in
your controller? I don't really agree that boolean values need explicitly
be supported because that is what a check box is for while selects are
about multiple values.

Also, numbers are already supported so theoretically you can do 0 and 1.

**Comment by pablocaselas** [comment]
I agree with you that it should be done with a checkbox but sometimes clients want it that way.

Of course you could do it on the controller, but I believe frameworks and architectures are for those kinds of things. Abstracting the user (developer)  from the implementation of the component. The fact is, angular is already supporting this behavior and I believe angular-ui should too.

**Comment by ProLoser** [comment]
How do you do it in angular?

**Comment by ProLoser** [comment]
Or are you referring to the parsers.

Anyway, open a pull request.

**Comment by pablocaselas** [comment]
In angular it could be done like this...

http://plnkr.co/edit/q98eerF4VCS600MAtm3o?p=preview

**Comment by devesh** [comment]
When you make a fix, please make sure it supports Numbers too. I have a large list of options with numerical ids that I want the user to select from. AngularJS supports this with ngOptions, but I'd like to use Select2 to provide a nicer filtering UI.

Edit: I just saw @ProLoser said that numbers are already supported. I can't find the documentation for this. Can you point me in the right direction?

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-select2 (after confirming it's still necessary with the latest code)?

**Comment by pablocaselas** [comment]
I will try to check it today and post whatever I've found out.

Thanks Dean!

El 03/05/2013, a las 11:09, Dean Sofer notifications@github.com escribió:

AngularUI is currently undergoing a restructure. This project will no
longer hold the codebase, can you please relocate this to
https://github.com/angular-ui/ui-select2 (after confirming it's still
necessary with the latest code)?

—
Reply to this email directly or view it on
GitHubhttps://github.com/angular-ui/angular-ui/issues/355#issuecomment-17385011
.

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-select2

Please reopen this issue there if it is still relevant.
