### ISSUE TITLE
TinyMCE fails to show contents after form saving

### ISSUE THREAD

**Issue by philjones88** [angular-ui/angular-ui-OLDREPO#359]
As per title, sometimes in my AngularJS SPA TinyMCE fails to show content, if you refresh the page or revisit the same part of the application it works that time.

It appears to happen after the user has submitted/saved the form and the SPA uses $location to redirect them to the "list", if they click edit again the tiny mce instance is empty but refreshing the whole page shows the proper contents.

I do not want users to experience this because if they press save it overwrites content with nothing.

I have it configured with:

```
app.value('ui.config', {
    tinymce: {
        // General options
        mode: "textareas",
        theme: "advanced",
        plugins: "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advlink,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",

        // Theme options
        theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2: "cut,copy,paste,pasteword,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,cleanup,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_toolbar_location: "top",
        theme_advanced_toolbar_align: "left",
        theme_advanced_statusbar_location: "bottom",
        theme_advanced_resizing: true,

        // Skin options
        skin: "o2k7",
        skin_variant: "silver",

        cleanup: true,
        cleanup_on_startup: true
    }
});
```

And I create it via this directive:

```
app.directive('formWysiwyg', function () {
    return {
        restrict: 'E', compile: function (element, attrs) {

            var htmlText = '<div class="control-group">' +
                '<label class="control-label" for="' + attrs.formId + '">' + attrs.label + '</label>' +
                '<div class="controls">' +
                    '<textarea ui-tinymce ng-model="' + attrs.bindField + '" id="' + attrs.formId + '" name="' + attrs.formId + '" class="' + attrs.class + '"></textarea>' +
                '</div>' +
                '</div>';

            element.replaceWith(htmlText);
        }
    };
});
```

And in my HTML it is used like:

```
<form-wysiwyg label="Description" form-id="description" form-name="description" bind-field="item.description" class="span9"></form-wysiwyg>
```

**Comment by ProLoser** [comment]
So you are saying it fails to load on Route change from within an ngView?

**Comment by philjones88** [comment]
Yes, but only after saving the form

**Comment by ProLoser** [comment]
Can you create a fiddle or plunker that reproduces this problem?  

## 

Dean Sofer
DeanSofer.com
714.900.2254

**Comment by joshkurz** [comment]
I have seen this too. It's caused by the tinymce code not being loaded fully by the time the directive is fired. It's kinda spastic.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-tinymce (after confirming it's still necessary with the latest code)?
