### ISSUE TITLE
ui-mask returns null object instead of empty string

### ISSUE THREAD

**Issue by shaungrady** [angular-ui/angular-ui-OLDREPO#360]
When an HTML INPUT element is empty, the value is an empty string. It seems to me that, when the mask is invalid, it should return an empty string instead of the null object—it doesn't make sense to be putting a JS object into the model when that field was certainly intended to be a string.

**Comment by petebacondarwin** [comment]
This is not strictly true.  If you look at an input with a required
validator on it, then when the value is empty, the model is set to
undefined.
http://plnkr.co/edit/dksfq8T0zKYLcJTa7oPY?p=preview

**Comment by shaungrady** [comment]
Would not the required validator take precedent and modify the empty string returned by uiMask to undefined?

**Comment by petebacondarwin** [comment]
Not necessarily but the point is that the convention with radiators is if
the value is not valid then don't pass it along.

Pete
...from my mobile.

**Comment by ProLoser** [comment]
Seems off scope. I'm closing this but feel free to provide a use-case in which this would be worth addressing.
