### ISSUE TITLE
ui-mask returns value without punctuation. Please make optional.

### ISSUE THREAD

**Issue by shaungrady** [angular-ui/angular-ui-OLDREPO#361]
It makes sense for uiMask to strip the mask pattern from the field value in cases like phone numbers. However, in the case of dates, where the model might already have a specific formatting such as "MM-DD-YYYY", having uiMask strip the mask punctuation creates a bit of a headache.

It would be nice if there were a configuration option to leave the mask punctuation intact when updating the model.

**Comment by petebacondarwin** [comment]
Yes, that is a good point.  The mask widget needs a thorough overhaul.
 Fancy having a go?

**Comment by shaungrady** [comment]
I'm in the process of writing a simpler, more robust jQuery input masking plugin.
I've only had a couple weeks of experience with Angular, but I can give that a shot after I've completed the new masking plugin. It looks straightforward enough.

**Comment by shaungrady** [comment]
I'd love to have another set of eyes look at this new jQuery Input Mask plugin I wrote:
https://github.com/shaungrady/jquery-mask-input

The patched uiMask code to utilize it looks like this, pretty simple, though there isn't yet an option to specify whether to use the masked or unmasked value for the model.

```
angular.module('ui.directives').directive('uiMask', [
  function () {
    return {
      require:'ngModel',
      link:function ($scope, element, attrs, controller) {

        /* We override the render method to run the jQuery mask plugin
         */
        controller.$render = function () {
          var value = controller.$viewValue || '';
          element.val(value);
          element.maskInput($scope.$eval(attrs.uiMask));
        };

        /* Add a parser that extracts the masked value into the model but only if the mask is valid
         */
        controller.$parsers.push(function (value) {
          var isValid = element.data('isUnmaskedValueValid');
          controller.$setValidity('mask', isValid);
          return isValid ? value : undefined;
        });

        /* When keyup, update the view value
         */
        element.bind('keyup', function () {
          $scope.$apply(function () {
            controller.$setViewValue(element.val());
          });
        });
      }
    };
  }
]);
```

**Comment by ProLoser** [comment]
Pinging @petebacondarwin about this one.

**Comment by petebacondarwin** [comment]
@shaungrady - This looks great!  I think we should move away from the unsupported mess that is the current plugin.  What would be even better than wrapping your jQuery plugin is if we could extract the logic and make a pure AngularJS directive from it.  I had a quick look at your code and I don't think this would be a great effort.  I could have a go later this month but it would be an excellent exercise for you if you wanted to try.

**Comment by shaungrady** [comment]
Yeah, I'd love to give it a shot. I'll have time to work on it at the start of March if that's OK.

**Comment by petebacondarwin** [comment]
Great.

Pete
...from my mobile.

**Comment by shaungrady** [comment]
I've issued a pull request, all the details are in the pull message:
https://github.com/angular-ui/angular-ui/pull/479
