### ISSUE TITLE
Refactor uiCurrency to use toggleClass() instead of addClass and removeClass()

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#362]
Just for the sake of efficiency. I noticed this while looking at the code.

`toggleClass()` takes a second (optional) boolean parameter that specifies if the class should be added or removed. This would remove the need for the verbose if-statements.

**Comment by dandoyon** [comment]
worthy optimization

**Comment by joshkurz** [comment]
I like to call it the big O. Optimization is always worthy. Ill take this
one.

On Fri, Jan 18, 2013 at 11:45 AM, Dan Doyon notifications@github.comwrote:

> worthy optimization
> On Jan 17, 2013, at 5:41 PM, Dean Sofer wrote:
> 
> > Just for the sake of efficiency. I noticed this while looking at the
> > code.
> > 
> > toggleClass() takes a second (optional) boolean parameter that specifies
> > if the class should be added or removed. This would remove the need for the
> > verbose if-statements.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/362#issuecomment-12430376.

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by ProLoser** [comment]
@joshkurz what happened with this one?
