### ISSUE TITLE
new directive proposal Highcharts

### ISSUE THREAD

**Issue by moperacz** [angular-ui/angular-ui-OLDREPO#363]
For my current project I needed nice looking charts... I was unable to find something tailored for my needs which uses angular... So I wrote some for my own needs...

You can check it on: http://embed.plnkr.co/gahfIWNEfCd8yEXBdFtZ/preview

If you like it give some feedback... So i write some tests, fix some obvious issues and create pull request :smile: 

Currently it only supports datetime format, you can update data and add new...

It's support setting default highcharts options (via ui.config (highchart: default: {})) so you can customize look and feel on all charts...

**Comment by ProLoser** [comment]
Have you thought about using ngModel instead of chartData?

Will the chart change accordingly if I directly modify chartData via angular (instead of doing it through highchart)?

Why do you have to do `highchart: default: {}`? Is this how Highchart expects you to define defaults? Otherwise, anything inside of ui.config is already assumed to be defaults so adding an extra level doesn't help.

You appear to have hard-coded some defaults ("spline" and height=300) I'm assuming this is just for demonstrative purposes? We try not to hard code our own opinion of what should be defaults. Either you must explicitly set defaults, pass the parameters, or let the plugin use its own defaults.

**Comment by moperacz** [comment]
wow.. speedy answer :wink: 
1. i thought about ngModel... don't remember why didn't use it... probably forgot about existence of ngModel... i don't see any problem with using ngModel for that
2. yes it will change... as in example provided... i modify data thru angular.. 
3. i have some plans about using other settings just for directive, `highchart: default: {}` is merged and passed to Highcharts.js... and i will need some options just for directive itself not for Highcharts (e.g. default behavior for adding datapoints ? to shift or not to shift graph etc)
4. this kind are "obvious issues"..

**Comment by ProLoser** [comment]
What do you mean shift or not to shift? What is the directive doing differently from normal?

**Comment by moperacz** [comment]
it was example... highcharts are very feature rich...

as for "to shift or not to shift":
when you are adding data to existing chart you are using addPoint function, witch takes three arguments
1. data to add
2. redraw chart immediately
3. shift chart(drop old data) or squeeze it (show old data and new)

and 3-rd parameter should be configurable in universal directive (i think)...

there are lots of nuances as this in highcharts

and to be explicit, there are no options for directive right now... i'm thinking about it :wink:

**Comment by joshkurz** [comment]
This is nice. If you could open up a PR for this that would be great. I was just about to start working with high charts for our current site. Great Timing. :+1:

**Comment by moperacz** [comment]
Ok, so I will change some things (as for @ProLoser comments + some obvious fixes + basic tests) and open PR...
I work on it tomorrow evening..

Do you have any proposal as for directive params name, or other features that should be included first?

**Comment by joshkurz** [comment]
As long as we can change the data live from angular (which you already have
done) and hook any api callback event to the scope I believe that we will
be ok. I can also see that there are some hardcoded values in _chartConfig.
these should be squashed. There is also allot of logic inside of the watch
function. Maybe we should pass in a function through the config that gets
triggered while watching chartData. This way we can do whatever we want
when the data changes.

As we move forward Im sure there will be some tweeks here and there, but
this is the natural progression of things.

On Tue, Jan 22, 2013 at 12:17 PM, moperacz notifications@github.com wrote:

> Ok, so I will change some things (as for @ProLoserhttps://github.com/ProLosercomments + some obvious fixes + basic tests) and open PR...
> I work on it tomorrow evening..
> 
> Do you have any proposal as for directive params name, or other features
> that should be included first?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/363#issuecomment-12555026.

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by ProLoser** [comment]
@moperacz the sooner you open a Pull Request the sooner we can merge this in! Your PR doesn't have to be completed, it can provide us a location for us to help you refine and comment on your code.

**Comment by aaronleesmith** [comment]
This seems to have been dropped. Is there a PR open? Highcharts integration would be a killer feature.

**Comment by ProLoser** [comment]
If anyone wants to take this on I can create a new repo and add them so that they can start this.

**Comment by ProLoser** [comment]
This project is discontinued. Checkout https://github.com/angular-ui/ui-chart

**Comment by gevgeny** [comment]
I am developing such directive now. Check https://github.com/gevgeny/ui-highcharts
