### ISSUE TITLE
Calendar directive options are undefined

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#366]
If you do `<div ui-calendar="{someOption: someVariable}">` and `someVariable` is defined on the parent scope, it is `undefined` on the calendar scope.

This is because the calendar is an isolated scope, but only the `ngModel` property was ported from the parent scope.

Need to add `options: 'uiCalendar='` (or whatever the 1-way version is) to the scope definition.

Example: http://plnkr.co/edit/rllEOfIx708Uz6fTawnO?s=bc&p=preview

**Comment by joshkurz** [comment]
I dont think it needs a scope definition at all. 
Here is a version that I plan on committing soon. http://jsfiddle.net/joshkurz/Ljq26/1/ No isolated scope and uses ui-config for all extendable actions/options. I think the only thing it needs is a way to overwrite the default header,left,center,right options and it will be 100% extendable.

**Comment by ProLoser** [comment]
@joshkurz what's the story with this one again?

**Comment by joshkurz** [comment]
all the tests are passing on my localhost. Ill open a new PR.

On Fri, Feb 1, 2013 at 7:29 AM, Dean Sofer notifications@github.com wrote:

> @joshkurz https://github.com/joshkurz what's the story with this one
> again?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/366#issuecomment-12992122.

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by ProLoser** [comment]
@joshkurz I would open a PR myself from your fork but I don't know which branch this commit is sitting in.

**Comment by joshkurz** [comment]
This issue has been solved with the new branch https://github.com/joshkurz/angular-ui/tree/calendar that has been merged.

**Comment by ProLoser** [comment]
Cool. I'm going to close this.
