### ISSUE TITLE
Calendar directive hard-codes eventMouseover callback

### ISSUE THREAD

**Issue by oevna** [angular-ui/angular-ui-OLDREPO#367]
As specified here: http://arshaw.com/fullcalendar/docs/mouse/eventMouseover/

Should be configurable via uiCalendar or uiConfig.uiCalendar objects instead.

**Comment by joshkurz** [comment]
You are correct sir. This calendar will fix the issue. It is set for the 0.4.0 release.  http://jsfiddle.net/joshkurz/Ljq26/1/

**Comment by ProLoser** [comment]
Do you have a pull request open already?

**Comment by joshkurz** [comment]
No not at the moment.

**Comment by ProLoser** [comment]
Pull request baby, even if it isn't finished.

**Comment by joshkurz** [comment]
ok I wIll send one tonight.

**Comment by ProLoser** [comment]
@joshkurz closing this, if i'm wrong feel free to reopen and slate for v0.4.1
