### ISSUE TITLE
Customizing ui-date to do something a little out of the ordinary

### ISSUE THREAD

**Issue by sarbogast** [angular-ui/angular-ui-OLDREPO#368]
I have a link in my UI. When the user clicks that link, I would like a calendar to appear beneath the link, and when he selects a date, the calendar should disappear and a controller function should be called to do something with the date the user selected. Here is what I've tried so far:

``` html
<a ui-date="{onSelect:addDay}" ui-date-format="dd/MM/YYYY" ng-model="dateToAdd">Add a day</a>
```

``` javascript
$scope.addDay = function(value, picker) {
        console.log("Yay!");
    }
```

The displaying a calendar part works, but when the user selects a date, nothing happens, my controller function is not called and I get no error. Obviously I'm forgetting something here but I don't know what. I tried to figure out the onSelect behavior by looking and angular-ui source code but obviously I didn't get it.

**Comment by petebacondarwin** [comment]
Can you debug into the line in the date directive that handles the onSelect and see what is happening?
https://github.com/angular-ui/angular-ui/blob/master/modules/directives/date/date.js#L40

**Comment by sarbogast** [comment]
First of all, I don't know if it's connected, but I'm getting a javascript error when the page is loaded:

```
TypeError: Cannot call method 'getTime' of undefined
    at Datepicker.setDate (http://localhost:8080/chapter4/static/bundle-bundle_editable_defer.js:3078:31)
    at HTMLAnchorElement.<anonymous> (http://localhost:8080/chapter4/static/bundle-bundle_editable_defer.js:3576:18)
    at Function.e.extend.each (http://localhost:8080/chapter4/static/plugins/jquery-1.7.1/js/jquery/jquery-1.7.1.min.js:2:11937)
    at e.fn.e.each (http://localhost:8080/chapter4/static/plugins/jquery-1.7.1/js/jquery/jquery-1.7.1.min.js:2:8483)
    at $.fn.datepicker (http://localhost:8080/chapter4/static/bundle-bundle_editable_defer.js:3568:15)
    at controller.$render (http://localhost:8080/chapter4/static/bundle-bundle_angular-ui_defer.js:1118:21)
    at Object.initDateWidget [as fn] (http://localhost:8080/chapter4/static/bundle-bundle_angular-ui_defer.js:1126:20)
    at Object.e.$digest (http://localhost:8080/chapter4/static/bundle-angular_defer.js:84:409)
    at Object.e.$apply (http://localhost:8080/chapter4/static/bundle-angular_defer.js:86:379)
    at e (http://localhost:8080/chapter4/static/bundle-angular_defer.js:92:330) 
```

And I've set up a breakpoint on the line you pointed to but execution never gets there. Plus, I don't have the same code as the one in the repository. My code looks like the following:

``` javascript
if (opts.onSelect) {
            // Caller has specified onSelect, so call this as well as updating the model
            var userHandler = opts.onSelect;
            opts.onSelect = function (value, picker) {
              updateModel();
              return userHandler(value, picker);
            };
          } else {
            // No onSelect already specified so just update the model
            opts.onSelect = updateModel;
          }
```

Note that I am using the latest stable release, version 0.3.2.

**Comment by petebacondarwin** [comment]
Can you try using the latest on the master branch?  There have been some
fixes to date recently.

**Comment by sarbogast** [comment]
OK. I tried with the latest version from the master branch, re-built everything to get the latest version of angular-ui.js and now I have the same code as you but the result is still the same: execution never reaches my breakpoint. onSelect is never called.

**Comment by petebacondarwin** [comment]
Can you provide a plnkr to demo this issue?

**Comment by sarbogast** [comment]
I'm still a noob with Plunker but I've tried to set up one here: http://plnkr.co/edit/fXn2DMiH39VeVSnmB17K
But this time I haven't even managed to get the calendar to be displayed when I click the button.

**Comment by kapusta** [comment]
Just a quick note for @sarbogast re: the getTime error you mentioned, I suspect you're falling into the same trap mentioned in #490

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-date (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-date

Please reopen this issue there if it is still relevant.
