### ISSUE TITLE
Conflict between Select2 and TinyMCE on the same page

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#37]
When I test both standalone they behave perfectly fine, however on the demo page there appears to be a conflict.

This may not necessarily be the fault of angular, and I somehow doubt TinyMCE would honestly be the culprit, but I have had both running on the same page before and this did not happen so I would like to look into it and see if I can at least return some feedback to the respective sources.

Hopefully this doesn't break anything else on the demo page.

This appears to only happen with the AngularUI directives, so more reason for us to look into it: http://jsfiddle.net/9tM5Z/ (non-angular demo works fine)

**Comment by dreadeddev** [comment]
Hey @ProLoser , I am struggling with this too! The fiddle doesn't work even without angular, how did you resolve this in the end?

Thanks

Ian
