### ISSUE TITLE
Calendar Testing Focus Bug

### ISSUE THREAD

**Issue by joshkurz** [angular-ui/angular-ui-OLDREPO#375]
Why does the client window have to be focused on during testing because of ui-calendar?

**Comment by petebacondarwin** [comment]
It is actually something funny with Chrome.  If the tests are running in a
tab that is not at the front of the tab list then it can hang tests that
interact with the DOM in certain ways.  The easiest solution is to always
have your test browser open in a window on its own without any other tabs.

**Comment by joshkurz** [comment]
Just confirmed this. Thanks @petebacondarwin
