### ISSUE TITLE
Date.prototype.toISOString not supported in IE8 and below

### ISSUE THREAD

**Issue by chrisjaure** [angular-ui/angular-ui-OLDREPO#383]
There's a call to Date.prototype.toISOString in the date directive that breaks in IE8 and below: https://github.com/angular-ui/angular-ui/blob/master/modules/directives/date/date.js#L90

This should either be replaced with a comparable function or a polyfill should be provided.

You can find a polyfill here: https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/Date/toISOString

**Comment by petebacondarwin** [comment]
I kind of agree with Dean here.  If you are going to support IE8 then you
are going to need a shim in there anyway.  If not then we shouldn't burden
people by bundling it in to our library.
Pete

**Comment by chrisjaure** [comment]
At the very least, could you document browser support? Especially if it's not the same as angularjs.

**Comment by petebacondarwin** [comment]
Fair enough!  Will do.

**Comment by chrisjaure** [comment]
I have a quick question about this behavior now that I've looked at it a little more. Why default to ISO format? Wouldn't a better default be the jQuery UI datepicker widget default which is mm/dd/yy?

Relevant docs: http://api.jqueryui.com/datepicker/#option-dateFormat

**Comment by ProLoser** [comment]
@chrisjaure that may not be a bad thought, but do you mind creating a new issue for it?

**Comment by petebacondarwin** [comment]
It was what was requested when I wrote it!  I guess, also it is a standard
way for servers to provide date?
Now we have uiConfig.dateFormat it is easy enough to configure this
application wide so I would rather not change it - especially as it would
be a breaking change.
Pete
