### ISSUE TITLE
ui-if isn't removing/adding elements in the DOM

### ISSUE THREAD

**Issue by JakobJingleheimer** [angular-ui/angular-ui-OLDREPO#385]
I have encased a div within a `ui-if`, and the child is not displayed, however it still exists in the DOM: http://plnkr.co/edit/t2Nq57

The areas in the plunkr that concern this issue are in the `GoogleMaps` controller in `controllers.js` and the child of body's 2nd child:

``` html
<body>
  <div ng-view></div>
  <div id="map_container">
    <div ui-if="mapReady">
      <!-- this still exists in the DOM when mapReady is false --> 
    </div>
  </div>
</body>
```

And subsequently, directives from elements within the `ui-if` run before `mapReady` is true, which causes errors.

**Comment by ProLoser** [comment]
I am unable to test the case you describe. The ui-if is true when the page loads. Is there somewhere I should place a breakpoint?

**Comment by JakobJingleheimer** [comment]
Hmm, on line 13 of controllers.js I set `$scope.mapReady = false`, so it should start out false. I re-arranged some divs to make it more obvious, and now it started working. It might have been caused by putting `ui-if` in the same div that specified the controller from which its condition is defined (causing the condition to be in a different scope)?

**Comment by ProLoser** [comment]
Oh yeah, keep in mind ui-if is terminal and high priority, so there are 0 gaurentees about other directives on the same DOM element. You're just safe isolating it from complex directives (simple directives like ng-class, etc, won't be affected). Feel free to close this if that was the only problem.

**Comment by JakobJingleheimer** [comment]
I expect `ui-if` to cause the execution directives of child elements to be delayed until `ui-if`'s condition is met (and its children are returned to the DOM); is that not how this should function? (if not, then that answers my issue)

**Comment by ProLoser** [comment]
Your original code paste was incomplete. Did you put NG- controller on the
same element as ui-If?

**Comment by JakobJingleheimer** [comment]
Oh sorry I updated the plunker:

``` html
<body>

    <div ng-view></div>

    <div
      id="map_container"
      ng-controller="GoogleMaps">

      <div ui-if="mapReady">

        <p>mapReady: {{mapReady}}</p>
        <p>maprkers: {{markers}}</p>
        <div ng-include src="map.html"></div>

      </div>

    </div>

  </body>
```

**Comment by JakobJingleheimer** [comment]
btw I'm seeing a TypeError bubble up from the `$scope.$watch` in the `uiIf` directive:

`TypeError: Object [object Object] has no method 'trigger'` `angular.js 5582`
originating from `ui-if.js 36`

**Comment by petebacondarwin** [comment]
Have you tried the latest version of ui-if?

https://github.com/angular-ui/angular-ui/blob/master/modules/directives/if/if.js

http://plnkr.co/edit/gxnCNd?p=preview

**Comment by JakobJingleheimer** [comment]
Oh! that would be it. About a week ago I downloaded v0.3.2 from https://github.com/angular-ui/angular-ui/tags so I didn't think to check for an update.

Thanks! (and sorry for inquiring about an issue that was already fixed)
