### ISSUE TITLE
uiMap TypeError: Object [[object HTMLDivElement]] has no method 'trigger'

### ISSUE THREAD

**Issue by JakobJingleheimer** [angular-ui/angular-ui-OLDREPO#386]
I'm receiving a TypeError within the uiMap directive on line 12. (Chrome on Windows reports `Object [[object HTMLDivElement]]` but Chrome on OSX reports the less helpful `Object [[object Object]]`)

I set a breakpoint on line 12, and evaluated `element`, and got (line-breaks added):

``` html
<div
  id="map_canvas"
  ui-map="myMap"
  ui-options="mapOptions"
></div>
```

This value is consistent with the html within my code.

Next I set breakpoints on 12 & 16 and checked the values of `$event` and got:

``` javascript
Object {type: "map-bounds_changed"}
```

But `evt` is `undefined`.

Also, when I stepped into `trigger()` I noticed `angular.extend( {} , $event , evt )` is passed into `trigger`, but `angular.extend()` accepts only 1 parameter (line 195 of angular.js v1.0.3):

``` javascript
function extend(dst) {
  forEach(arguments, function(obj){
    if (obj !== dst) {
      forEach(obj, function(value, key){
        dst[key] = value;
      });
    }
  });
  return dst;
}
```

P.S. Possibly related to #210.
P.P.S. I grabbed the latest from github this morning.

**Comment by JakobJingleheimer** [comment]
jQuery must be included before angularjs

But I still don't understand how the above code functions.

**Comment by ProLoser** [comment]
@ajoslin if you have a chance can you review this issue?

**Comment by ProLoser** [comment]
@jshado1 `arguments` is a javascript primitive variable that lets you refer to the arguments passed to the current function like a [splay](http://stackoverflow.com/questions/6201657/what-does-splats-mean-in-the-coffeescript-tutorial).

Also, `.trigger()` is only in jQuery, however it seems we removed this from v0.4.0

Can you pull the latest and see if this is still relevant?

**Comment by JakobJingleheimer** [comment]
Fixed. thanks!
