### ISSUE TITLE
ui-if calling trigger on parent element

### ISSUE THREAD

**Issue by geddski** [angular-ui/angular-ui-OLDREPO#387]
With angular 1.1.2 `ui-if` breaks on line 37:
`iterStartElement.parent().trigger("$childrenChanged");`
with this error:
`Object [[object HTMLUListElement]] has no method 'trigger'`

Full example:
http://plnkr.co/edit/k8kQPxmrJp48OOQeznSz

**Comment by petebacondarwin** [comment]
Try the version on master: https://github.com/angular-ui/angular-ui/blob/master/modules/directives/if/if.js

**Comment by geddski** [comment]
Fixed in master. Thanks.
