### ISSUE TITLE
pluralization support with format filter

### ISSUE THREAD

**Issue by lanterndev** [angular-ui/angular-ui-OLDREPO#388]
http://angular-ui.github.com/#filters-format says "Most commonly, this filter is helpful for internationalization", but it doesn't mention how you would use it with different plural forms, which is a basic part of i18n. If format supports pluralization already, could you give an example, and if not, would implementing it be of interest?

**Comment by ProLoser** [comment]
So... it wasn't developed as an end-all solution. If you want something heavy-duty there are lots of more focused libraries out there.

My thinking (towards pluralization) would be to use this alongside `<ng-pluralize>`. The only thing this really focuses on is token replacement, which is a way to _assist_ internationalization, not tackle it completely.

If you look at the ngPluralize demos, you'll see they demo ways of doing internationalization which are essentially just a way to switch what message strings you're using.

Although... after re-reading the docs I was unaware you could use `{{}}` in ngPluralize so perhaps this filter should be folded.

**Comment by lanterndev** [comment]
Thanks for the response, @ProLoser. What do you mean by "folded"?

**Comment by ProLoser** [comment]
Removed

**Comment by ProLoser** [comment]
@skivvies I'm closing this but feel free to reopen if it's still relevant to you.
