### ISSUE TITLE
Open Modal with data-toggle="modal" broken

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#39]
Doesn't do anything for some reason on the demo page. Not sure why.

**Comment by ProLoser** [comment]
Guess it's working in the latest version. Closing this

**Comment by ajoslin** [comment]
Sorry, didn't see this earlier. It's stll not working for me on the main page... I can't look at it today, though.

**Comment by ProLoser** [comment]
Ya it's acting buggy on the live site.
