### ISSUE TITLE
Ui-mask issue in IE8

### ISSUE THREAD

**Issue by DiegoPires** [angular-ui/angular-ui-OLDREPO#393]
Hey guys,

I've noticed that the feature of AngularUI for mask is behaving different in IE8, even in the main site (http://angular-ui.github.com).

In IE8, if you delete the value of the field mask and retype anything, the "Mask model value" shows with the mask. 

Ex: "11-11-1111" instead of "11111111".

And the same happens in the controller of angular.

Is that an issue for the AngularUI or the Jquery Mask?

**Comment by ProLoser** [comment]
Try creating a stand alone demo outside of angular. If you help us out
would be much appreciated.

**Comment by shaungrady** [comment]
uiMask has since been refactored, this issue is no long applicable.
