### ISSUE TITLE
Problems with item being duplicated when using ui-sortable with connected nested lists

### ISSUE THREAD

**Issue by aravinda0** [angular-ui/angular-ui-OLDREPO#394]
I've been trying to use this commit for ui-sortable: 
https://github.com/angular-ui/angular-ui/commit/0d86357afaa3da22ffdc244c892112c640a85802

Take this plunker: http://plnkr.co/edit/58O5JW?p=preview
When you move the item titled 'Samsung to release...' into the list titled 'Top News', the item gets duplicated.

Using a newer version of jquery-ui (I used 1.10.0) solves that issue. 

But just upgrading to a newer jquery-ui version doesn't fix everything.
http://plnkr.co/edit/lSErMO?p=preview

In the above plunker, if you move the 'New Phone Releases' sublist to the END of the list titled 'Top News', the move takes place, but an empty element also gets appended to the latter.

I'm quite new to javascript and angular, but the following crude modification in the ui-sortable directive seems to address the above issue. The changes are in the sortable.js file.
http://plnkr.co/edit/VKjbhV?p=preview

Please review the code.

**Comment by ProLoser** [comment]
You're using `connectWith: '.target'` but `class="target"` is on both the parents AND the children. You must use a separate class or selector to differentiate between the two levels.

I feel like I have de-ja-vu. I know I answered this exact question at least once before.

**Comment by ProLoser** [comment]
You saved over the middle link when you posted the third link (same url). I am unable to see a 'samsung' item in all of your links provided.

**Comment by aravinda0** [comment]
Damn. Sorry about the duplicate link. I've updated the middle link.

The 'samsung..' item is in the first plnkr link. The list is a bit long due to margins and all, so if you're on a smaller screen, try clicking on 'launch preview in a separate window' button at the top right of the preview section.

And yes, the deja-vu is because you told me on IRC about the reason that there is the same class on both the parent list and child list.
I'm trying to make modifications to the code to allow items in the parent list to be moved into a child list.

**Comment by ProLoser** [comment]
I think I was noticing this bug too when I was putting the demo together. I haven't been able to thoroughly review the new source for the error, but I will try to do this before v0.4.0

If you want to help me out, you can try inspecting the source code yourself and help me out by helping me identify the problem code. Keep in mind all that is really being done is that the index of the li you are dragging is mapped to the ng-model array, and when you drop, the source array gets the item spliced out and the target array gets the item spliced in.

**Comment by aravinda0** [comment]
From what I saw, the problem is that the code in the 'update' handler splices the source ngModel array in both the following cases:
1) Item is reordered _within_ a list. (We want this)
2) Item is moved to another list. (We don't want this, since in this case, the splicing is handled by the 'remove' handler)

This is what I try to address in my fix applied in the 3rd link that I posted, but as it now turns out, there are still issues with it. I'm trying to replicate the problem.

**Comment by ProLoser** [comment]
Feel free to open up a Pull Request (even if it's unfinished) so that we can do some inline code-commenting until we resolve this issue.

**Comment by ProLoser** [comment]
So I'm wondering if what's happening is that both AngularJS AND sortable are both trying to relocate the DOM node to the new list.

**Comment by ProLoser** [comment]
I'm very very close but it's 6:20am and I've been working for 6 hours straight and need to sleep.

I need someone to play with the demo and review my onStop logic because my eyeballs are turning to mush.

There is something wrong with my splicing start and end positions, but I can't quite put my finger on it.

Also there's this weird (read: stupid) behavior where the onStop is being fired in the wrong linking function? The ngModel is wrong and the element is completely undefined, which is why I'm forced to store a reference in onUpdate which seems to be the last place it's still correct.

I would appreciate anyone who could give this another pair of eyes.
