### ISSUE TITLE
ui-mask

### ISSUE THREAD

**Issue by johntom** [angular-ui/angular-ui-OLDREPO#399]
Hi,
I'm trying to use u-mask, included   script(src='js/jquerymask.js') and get the following error.
TypeError: Object [object Object] has no method 'mask'
    at controller.$render (https://john-pc:8001/js/angular-ui.js:158:29)
    at Object.ngModelWatch (https://john-pc:8001/js/angular.js:11938:30)
    at Object.Scope.$digest (https://john-pc:8001/js/angular.js:7783:64)
    at Object.Scope.$apply (https://john-pc:8001/js/angular.js:7991:44)
    at HTMLHtmlElement.<anonymous> (https://john-pc:8001/js/angular.js:5444:36)
    at HTMLHtmlElement.jQuery.event.dispatch (https://john-pc:8001/js/jquery.js:3045:30)
    at HTMLHtmlElement.elemData.handle (https://john-pc:8001/js/jquery.js:2721:47) angular.js:5601

TIA
John

Chrome:Version 24.0.1312.57 m
Angular: 1.0.4
query-ui: 1.10.0
jquery: 1.9.0 
jquery_css  v1.10.0
Bootstrap f: 2.2.2 (combined min)
bootstrapui AngularUI: 0.3.2

**Comment by pkozlowski-opensource** [comment]
It looks like you didn't include jQuery _before_ AngularJS scripts. Make sure to go over the "Getting started" section from http://angular-ui.github.com/

**Comment by johntom** [comment]
HI,
I was just including the version of the libs and not the order. The following is the load order and I use the calendar and other ui directives without issue.
Any Ideas?
Thanks John
        script(src='js/jquery.js')
        script(src='js/jquery-ui.js')
        script(src='js/angular.js')
        script(src='js/bootstrapui.js')
        script(src='js/angular-ui.js')
        script(src='js/jquerymask.js')
        script(src='js/fullcalendar.js')

**Comment by petebacondarwin** [comment]
@johntom: Hmm.  Can you demonstrate this in a Plnkr?  Have you tried loading the jquerymask.js before angular.js?

**Comment by johntom** [comment]
Hi,
1)The order did not fix it.
2) I forgot to include the migrate script with version 1.9.0. It did work with 1.8.3

<script src="http://code.jquery.com/jquery-1.9.0.min.js"></script>

<script src="http://code.jquery.com/jquery-migrate-1.1.0.min.js"></script>

3) I wrote a plunker http://plnkr.co/edit/rsftsQ?p=preview for others who might run into same issue.
4) I knew I was doing something wrong!
Thanks,
John
