### ISSUE TITLE
Datepicker weird behavior

### ISSUE THREAD

**Issue by bekos** [angular-ui/angular-ui-OLDREPO#400]
Datepicker does not re-open if input element has not lost focus.

Details:
1) Click inside input of the datepicker in order for the calendar to display.
2) Click on desired date, and the datepicker closes.
3) Without losing focus from the input, click again inside the input... and nothing happens.
4) Lose focus and click again inside the input and calendar show up for you to change the date.

**Comment by petebacondarwin** [comment]
Are you using the version in master? I thought this had been fixed?

Pete
...from my mobile.

**Comment by bekos** [comment]
I use it in the official page. http://angular-ui.github.com/

**Comment by petebacondarwin** [comment]
This commit fixes the problem but it is not release yet:
https://github.com/angular-ui/angular-ui/commit/819fda12051979ff22a6430729495fd9ab61ddc3
Pete
