### ISSUE TITLE
Failing Tests?

### ISSUE THREAD

**Issue by joshkurz** [angular-ui/angular-ui-OLDREPO#403]
Currently their are six tests failing. If a new PR is opened, with these failing tests, would the build fail and therefore make the PR fail in the process?

**Comment by petebacondarwin** [comment]
Yes

**Comment by joshkurz** [comment]
thanks

**Comment by ProLoser** [comment]
The failing tests are my fault, I will fix them ASAP

**Comment by joshkurz** [comment]
Np

**Comment by ProLoser** [comment]
The build should be passing now (and says so on the README??) but when I go to travis it says it's failing and appears to be stuck on the previous build.

**Comment by joshkurz** [comment]
I just opened the PR to see what would happen and all is well and good. Thanks
