### ISSUE TITLE
Date (ui-date) Issue with IE8/IE9

### ISSUE THREAD

**Issue by Blakewell** [angular-ui/angular-ui-OLDREPO#404]
On Chrome the date selector disappears upon selection of a date.  However, in IE 8 and IE 9 the date selector pops back up upon selection of a date.  Chrome has a nicer UX IMHO.

**Comment by kcm** [comment]
We're seeing this too, any progress/details?

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-date (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-date

Please reopen this issue there if it is still relevant.
