### ISSUE TITLE
How to clear Select2 values in <input>?

### ISSUE THREAD

**Issue by davisford** [angular-ui/angular-ui-OLDREPO#408]
I've got something like this:

``` html
<select ng-model="selectedCommands" ui-select2="{allowClear: true, multiple: true}" ng-change="onCommandChange(selectedComands)">
  <option ng-repeat="command in commands" value="{{command.value}}>{{command.text}}</option>
```

Which ends up rendering like so:

``` html
<div class="select2-container select2-container-multi ng-pristine ng-valid select2-dropdown-open" id="s2id_autogen1" style="width: 100%">    
  <ul class="select2-choices">  
     <li class="select2-search-choice">   
         <div>FOO</div>    <a href="#" onclick="return false;" class="select2-search-choice-close" tabindex="-1"></a>
    </li>
    <li class="select2-search-choice">    
        <div>BAR</div>    <a href="#" onclick="return false;" class="select2-search-choice-close" tabindex="-1"></a>
    </li>
    <li class="select2-search-field">    
        <input type="text" autocomplete="off" class="select2-input" style="width: 10px;">                   
    </li>
  </ul>
</div>
```

In my controller:

``` javascript
$scope.commands = [
 { text: "FOO", value: "foo" },
 { text: "BAR", value: "bar" }
];

$scope.selectedCommands = [];

$scope.onCommandChange = function (selected) {
   // store this state on a different model
   $scope.device.commands = selected;
}
```

This all works just fine, but sometimes I want to clear the `<input>`.  Presumably I thought that I could do that by truncating the $scope.selectedCommands array since that is used as the `ng-model=selectedCommands` on the `<select>` item.  When I do that in my code, I can see the array is truncated, but the view still shows the items in the `<input>`.

How can I clear the view's `<input>` - and how come manipulating the bound model object is not updating the view ?

**Comment by ProLoser** [comment]
You're going to have to provide a fiddle as this should work.

How are you attempting to clear the value? Are you 100% positive your scopes are the same? (since you did `selectedCommands` instead of `data.selectedCommands`)

**Comment by davisford** [comment]
I did try to whip up a [plnkr](http://plnkr.co/edit/qGvd8rCsbp7cVoTp3KdM?p=preview) and it did seem to work -- although I couldn't figure out how to get the select2 .png resources to resolve -- they are hardcoded in the css, and so it didn't look pretty, but it did work.   If you click clear, it just truncates the array length, and it is cleared.

I'm not sure why it isn't work in my own project.  What do you mean "instead of data.selectedCommands" -- why `data`.  It was my understanding that any expression angular finds in HTML will try to resolve off its own $scope object.  Not sure what `data` refers to here?

I'll go ahead and close this as it seems to be something in my project in particular.

**Comment by ProLoser** [comment]
@davisford - watch this video: http://youtu.be/ZhfUv0spHCY?t=32m50s and my comments on it: http://youtu.be/ZhfUv0spHCY?t=45m40s
