### ISSUE TITLE
Two-way data binding with select2 (tags mode) + ng-model

### ISSUE THREAD

**Issue by fengtality** [angular-ui/angular-ui-OLDREPO#409]
Is there a way to correctly reflect both tags with initial values and altered values when using ui-select2 in tags mode?

The issue is that select2 looks for an array of strings in the ng-model to create the initial tags, but then changes it an array of objects when the user makes any changes.  If no changes are made, ng-model remains an array of strings.

Right now, this forces me to account for these 2 cases when displaying the tags correctly (and parsing the user inputs).  Example plunker below:
http://plnkr.co/edit/MNman2HWRXBJ2JDHKXjZ?p=preview

**Comment by ProLoser** [comment]
Does this sort of scenario ONLY occur with tagging mode and without initSelection? I have a fix ready but I need to know what scenarios need the fix.

**Comment by ProLoser** [comment]
Feel free to test out this version and see if it resolves your problem: https://github.com/ProLoser/angular-ui/blob/select2/modules/directives/select2/select2.js

However, I would still greatly appreciate it if you could help me identify the previous question I asked.

**Comment by fengtality** [comment]
Thanks - I believe it doesn't occur with select2-multiple since you can set what each option returns, but I haven't tried it.

I don't think initSelection is called when select2 is in tags mode: http://plnkr.co/edit/MNman2HWRXBJ2JDHKXjZ

**Comment by ProLoser** [comment]
I don't get why initSelection isn't called, it seems like it should be called, no? I mean if it makes sense to you too perhaps you can open a ticket on Select2 about this?

Anyway, if it ignores it (for now) I should remove [that check in the fix](https://github.com/ProLoser/angular-ui/commit/d391124292c7051d770d707b3cab0f1a1b3f18c5#L0R118)

**Comment by fengtality** [comment]
Did a couple of tests and confirmed that initSelection is called when select2 is in multiple mode, but NOT called in tags mode.

Multiple: http://plnkr.co/edit/4jUDh5SH8uilVGQIC72t?p=preview
Tags: http://plnkr.co/edit/L09fOWhNxxcMzP0OAMWQ?p=preview

I'll open a ticket in Select2.

**Comment by ProLoser** [comment]
This appears to be slated for Select2 v3.4 now: ivaynberg/select2#811

@mifeng - do you mind checking out [that commit from his repo](https://github.com/ivaynberg/select2/commit/270d4bad072b29f8536afcfb6032d37483e56642) and seeing if that closes this issue? If not, we can reopen this bug but for now I'd like to close as many bugs as possible.

**Comment by max-l** [comment]
FWIW, This jsFiddle : http://jsfiddle.net/maxl/hWXBv/14/
shows the bug as being fixed, but I am seeing it in an application with the exact version mix as in the jsFiddle,
in other words I am seeing the bug, but not able to reproduce it in a jsFiddle
