### ISSUE TITLE
Directives dont' seem to work within ng-include?

### ISSUE THREAD

**Issue by drewhamlett** [angular-ui/angular-ui-OLDREPO#410]
I've tried scrollspy and reset.  They don't seem to work if I'm applying them within an include.  They work fine otherwise.

```
<ng-include src="'partials/line/line-info.html'"></ng-include>
```

Then within that source file I apply this

```
    <input type="text" ng-model="line.name" placeholder="Line 1"  ui-reset/>
```

Nothing happens.   Take the same code and apply it outside a partial.  Works fine.

**Comment by ProLoser** [comment]
How are you doing scrollspy?

**Comment by drewhamlett** [comment]
I'm sorry, this seemed to be a caching issue with the reset(partial was cached).  The scrollspy was an iPad issue.  Doesn't work correctly I suppose.

**Comment by ProLoser** [comment]
I'm not sure how scrollspy works, it may not be knowledgable of async changes to the DOM.
