### ISSUE TITLE
Modal dialog - add optional modal ID attribute

### ISSUE THREAD

**Issue by matkokvesic** [angular-ui/angular-ui-OLDREPO#413]
Add in $dialogProvider.options possibility to set id attribute on modal div. In example:

```
$dialogProvider.options({
        modalId: 'uniqueModalId'
        backdrop: true,
        keyboard: true,
        backdropClick: true,
        backdropFade: true
    });
```

If we have many generic modals on one page it's useful to attach ID-s to each of them if some UI operations on child elements inside modal are needed.

The way i am doing that now is (with jquery): 

```
$(dialog.modalEl[0]).attr('id', 'uniqueModalId');
```

**Comment by pkozlowski-opensource** [comment]
I guess you wanted to open an issue in this repository: https://github.com/angular-ui/bootstrap where bootstrap-specific code resides. 

As for your request: could you elaborate on " some UI operations on child elements inside modal are needed". I tend to find that with AngularJS relaying on ids is seldom needed.Could you prepare a plunker with what you are trying to do?

**Comment by matkokvesic** [comment]
After some further analysis I would agree that id property on outermost modal div is really not needed in most of the cases. Please remove this "issue", my apologies I had to post this on stackoverflow first.
