### ISSUE TITLE
Promise tracker

### ISSUE THREAD

**Issue by ajoslin** [angular-ui/angular-ui-OLDREPO#415]
So I made this promise tracker thing, and made a whole github repo for it, and then I realized it would probably work great in angular-ui.

https://github.com/ajoslin/angular-promise-tracker

It's got unit tests and a readme and a demo and would be easy to pop in.

Should I go ahead and put it in?

**Comment by ProLoser** [comment]
Awesome. Do it.

**Comment by joseym** [comment]
Very cool, could have used this days ago (likely will use it regardless of my own solution). Well done.

**Comment by ajoslin** [comment]
OK, cool I'll pop it in. 

@joseym yeah, I got tired of trying to work with $scope.loading variables everywhere lol. thanks

**Comment by ajoslin** [comment]
I'll have to add a `services` folder, and then that will force me to update the builder (since that only excepts directives and filters atm).

**Comment by ProLoser** [comment]
Go ahead.

**Comment by geyang** [comment]
This looks great! How's the progress?

**Comment by ajoslin** [comment]
GitHub.com/ajoslin/angular-promise-tracker

I never ended up bringing it to angular-ui.

On Thursday, August 1, 2013, episodeyang wrote:

> This looks great! How's the progress?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/415#issuecomment-21969277
> .

## 

...sent from my iPhone
