### ISSUE TITLE
ui-validate not always popping up errors

### ISSUE THREAD

**Issue by end0** [angular-ui/angular-ui-OLDREPO#416]
Using Chrome on OSX, the ui-validate demo doesn't work for all cases:

blah - popup saying email is invalid
blah@ - popup saying email is invalid
blah@a - no popup
blah@b. - popup saying email is invalid
blah@b.c - no popup
blah@b.co - popup saying email is valid

Not sure why popup wouldn't show for case 3 and 5, which are both invalid email formats.

**Comment by ProLoser** [comment]
Can you test this if this occurs with vanilla AngularJS? The email validation SHOULD be the result of AngularJS.

Regardless, the validation code is also going to change in v0.4.0 and may very well fix this.

@joseym, again, if you don't mind, think you can see if the validation bug described is a symptom of AngularJS itself (and perhaps a bug should be filed for it). And also if the bug has been addressed in the latest snapshot of the code? Etc.

**Comment by joseym** [comment]
I'm on it.

**Comment by joseym** [comment]
Ok, i'm not sure what "popup" we're talking about.

Here's an email validation fiddle with just angular: http://jsfiddle.net/joseym/bjpNy/

Angular appears to be validation correctly (except for the form's init, where a blank field is considered a valid email).

As for the similar bug reported here: #418 

Angular is setting the appropriate valid/invalid classes, however the fields highlight state isn't changing appropriately - this may have something to do with how angular is setting the validity of the field (i have not investigated the core angular email validation yet).

The way I am able to work around this is by adding a class of `ng-invalid` to bootstraps `invalid` state styles: https://github.com/twitter/bootstrap/blob/master/less/forms.less#L367

I'll investigate the core validation to find out how it's working and see if a bug needs to be reported.

**Comment by joseym** [comment]
It may be premature but I opened an issue on the Angular project since this seems to be happening with AngularJS: [#1999](https://github.com/angular/angular.js/issues/1999)

**Comment by ProLoser** [comment]
Closing this, but we can reopen it if it turns out to be our fault.
