### ISSUE TITLE
ui-sortable doesn't respect {helper:'clone'} configuration

### ISSUE THREAD

**Issue by aaronwhite** [angular-ui/angular-ui-OLDREPO#417]
When configured with the clone helper, the directive doesn't properly allow a cloning drag-drop from one list to another (instead, it still functions as a move)

**Comment by ProLoser** [comment]
Does this occur with the latest code on master?

**Comment by aaronwhite** [comment]
Yes, I downloaded master, built, and was still able to reproduce it. I may produce some code to demonstrate it if I get a chance, I wasn't sure if this was a duplicate of another issue I saw you were working on. (BTW: thanks for the great work on angular-ui!)

**Comment by ProLoser** [comment]
I thought helper is just until you let go, and then it moves the original.
I'm not in front of a computer right now but I was wondering if you didn't
want the original to move during dragging or after releasing?

**Comment by ProLoser** [comment]
@aaronwhite If you re-read the sortable API, setting `helper:'clone'` is not the same as cloning the value from one list to another. It means that a copy of the original item is what you move around under the mouse, but once you let go, it will relocate the original. The _helper_ is a reference to what you're moving around using the mouse, but it is not a reference to the original node itself.

If you're asking that we support the ability to clone items from one set to another, then this seems like a new feature not originally supported by sortable. That being said, I'd be curious how they instruct people to do it with vanilla jQueryUI, then we can see if it's worth adding as an AngularUI-specific feature.

**Comment by ProLoser** [comment]
Feel free to reopen if you still need help
