### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#420]
Need codename suggestions:
- errmergad
- baconaise
- finalcountdown
- nananananana-BATMAN
- leeping-balderdash-batman
- zergrush
- barrelroll
- chocolaterain

**Comment by ajoslin** [comment]
+1 baconaise

**Comment by joseym** [comment]
baconaise || errmergad

**Comment by petebacondarwin** [comment]
"Oh Fortuna!"

Get it?

Pete
...from my mobile.

**Comment by joseym** [comment]
http://www.wimp.com/ofortuna/
