### ISSUE TITLE
How to extend angular-ui directive in a clean way?

### ISSUE THREAD

**Issue by ni-ka** [angular-ui/angular-ui-OLDREPO#421]
I would like to tweak my select2, which requires to add a bind on 'open' event, see http://jsbin.com/ebalik/1/embed?live. I could just add a directive that enhances the behavior,  and then use both the angular-ui directive and my extension, but it doesn't feel very clean.

Is there any best practice scheme to extend / reuse / customize angular-ui directives?

**Comment by ProLoser** [comment]
Have you tried leveraging ui-event?

**Comment by ni-ka** [comment]
Well, I could use ui-event and bind to the 'open' event, but I will need to access and call functions from the select2 component (the goal is to add filters to filter results displayed in the drop down - sorry should have explained). Thus this is not code that should go into the controller.

**Comment by ProLoser** [comment]
I would create a custom directive that simply inserts the select2 AND the ui-event and does whatever you need, etc.

In other words just wrap it.

**Comment by ProLoser** [comment]
Feel free to reopen or mention if you need this reopoened.
