### ISSUE TITLE
ui-if with non-boolean parameter

### ISSUE THREAD

**Issue by Wintermoose** [angular-ui/angular-ui-OLDREPO#422]
Because the directive simple watches for the parameter changes, doing something like

```
<div ui-if="comment">Current comment: {{comment}}</div>
```

Constantly re-creates the block whenever the comment changes.

This can be remedied by looking at the parameter converted to bool first, ie..

``` js
var childScope;
var last = null;  
scope.$watch(attr['uiIf'], function (newValue, oldvalue) {
  if (!!newValue === last) return;   //needs === to be sure first pass renders
  last = !!newValue;
  if ( childElement) { .....
```

Or, alternatively by pointing out the behaviour in the documentation, but I think the change above is cleaner

**Comment by petebacondarwin** [comment]
Or

```
<div ui-if="!!comment">
```

?

**Comment by Wintermoose** [comment]
Yes that solves the example, but using non-boolean expressions inside ifs is quite javascript-y way of coding. And if the current behaviour is desired, then it should be mentioned in the documentation (all IMHO of course)

**Comment by petebacondarwin** [comment]
I do agree actually :-)

Pete
...from my mobile.

**Comment by ProLoser** [comment]
@Wintermoose want to open a pull request with the necessary fix? And a test too of course :smile:

**Comment by ProLoser** [comment]
Need a better unit test for this one.

**Comment by Wintermoose** [comment]
Yeah I'll try to prepare pull with a test, when I manage to get some time
Br,
Robert

**Comment by ProLoser** [comment]
I have a commit referring to this issue but it does not have any tests yet
if you would like to work off of that.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-utils (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued, and this directive is no longer supported as it has been integrated into Angular core.
