### ISSUE TITLE
ui-modal doesn't work with ngRepeat

### ISSUE THREAD

**Issue by jseims** [angular-ui/angular-ui-OLDREPO#425]
This doesn't work

```
        <tr ng-repeat="item in list">
           <td><a ng-click="myModal=true">{{item.name}}</a></td>
        </tr>
```

But this does outside the ng-repeat

  &lt;a ng-click="myModal=true">blahblah&lt;/a>

**Comment by ProLoser** [comment]
`ng-repeat` creates a new child scope. You should do `$parent.myModal` OR make myModal a property of an object.

Also, `uiModal` has been removed from v0.4.0, although nothing's stopping you from continuing to use it :smile:
