### ISSUE TITLE
rename ui-if

### ISSUE THREAD

**Issue by Coder2012** [angular-ui/angular-ui-OLDREPO#429]
Given that the purpose of this directive is to remove an element from the dom, shouldn't it have a more descriptive name like ui-remove? ui-if doesn't tell us anything about what the directive does. Consider ng-repeat, ng-show for example.

**Comment by petebacondarwin** [comment]
The meaning being that the element is in the DOM "if" the expression is
true.

Pete
...from my mobile.

**Comment by Coder2012** [comment]
But ng-show works in a similar way, show element “if” the expression is true but that wasn’t named ng-if which it would have been using your explanation. I just think there might be a better name for it, but I don’t know what it is yet.

Neil

**Comment by ajoslin** [comment]
ng-add would be more appropriate if we were going in that direction.  Or ng-insert or ng-in-dom.

**Comment by petebacondarwin** [comment]
Actually ng-show works differently. It "shows" the DOM element if the
expression is true.

Pete
...from my mobile.

**Comment by Coder2012** [comment]
I did say:

show element “if” the expression is true in my previous statement.

What about ui-append which is similar to jQuery.

Neil

**Comment by ProLoser** [comment]
When AngularJS came out, the only flow controls that mapped to programmatic
flow control were repeat statements and switch statements.

Everyone asked why there did not exist an if-statement. That was part of
how this directive was designed. It used to be called ui-detach but was
renamed to be more concise and bring it in line with the basic flow control
statement.

I have never been confused by the name however and other Templating
languages have if statements so I personally vote to leave it as is.

**Comment by petebacondarwin** [comment]
Me too.

**Comment by pkozlowski-opensource** [comment]
+1 for leaving `ui-if`, as it is today.
