### ISSUE TITLE
Passing in Calendar settings ?

### ISSUE THREAD

**Issue by sgentile** [angular-ui/angular-ui-OLDREPO#432]
I'm curious the correct approach to passing parameters to the calendar directive to be used in the underlying fullcalendar control.

ie.  I'd like to disable dragging (to remove jquery ui dependency):
disableDragging : true

What is correct approach to passing this into the directive?

Thanks!
Steve

**Comment by joshkurz** [comment]
you can just do 

``` javascript
$scope.calendarOptions = {disableDragging: true} 
$scope.eventSources = [eventSource,eventSource,eventSource]
```

``` html
<div ui-calendar="calendarOptions" ng-model="eventSources">
```

**Comment by ProLoser** [comment]
Closing this, feel free to comment or reopen if it's still relevant
