### ISSUE TITLE
route directive fails to create scope

### ISSUE THREAD

**Issue by tisztamo** [angular-ui/angular-ui-OLDREPO#434]
It seems to me that the uiRoute directive doesn't create a new scope so if I use it on multiple tags the last $uiRoute wins.

This is not working:

``` html
<li data-ui-route="/public" ng-class="{active: $uiRoute}"><a href="#">Public</a></li>
<li data-ui-route="/private" ng-class="{active: $uiRoute}"><a href="#">Private</a></li>
```

But this is OK:

``` html
<li ng-repeat="btn in navbuttons" ui-route="{{btn.route}}" ng-class="{active: $uiRoute}"><a href="#">{{btn.label}}</a></li>
```

(The demo on the site uses ng-repeat which creates a new scope for every iterated tag so it is working correctly.)

**Comment by sudhakar** [comment]
I had the same problem too. After setting `scope: true` on the uiRoute solves the problem as new scope is created for it.

**Comment by ProLoser** [comment]
Man I never thought about that. Thanks for the tip, will change immediately.

**Comment by ProLoser** [comment]
Crap, how the fuck do you test child scopes.

**Comment by ProLoser** [comment]
If anyone wants to help fix the tests with `scope:true` it would help me out a lot

**Comment by ajoslin** [comment]
Did you try something like this?

``` js
var elm = $compile('<my-directive></my-directive>');
var childScope = elm.children().scope();
```

**Comment by ProLoser** [comment]
Is that the proper way to do it? I mean the element itself has the scope. Or maybe I should just do `elm.scope()`. I just sort of figured doing `scope()` was a hackish way to go about things.

**Comment by ProLoser** [comment]
Also, the dom element doesn't have children.

**Comment by leeola** [comment]
@sudhakar re:

> I had the same problem too. After setting scope: true on the uiRoute solves the problem as new scope is created for it.

How exactly would you do that?

I'm not familiar with Angular/AngularUI's method for providing options to modules, but when i tried to emulate the `ui-select2` example shown on the homepage, i couldn't seem to set `scope: true`.

I tried

```
myModule.value('ui.config', {
  uiRoute: {
    scope: true
  }
});
```

with the names `uiRoute`, `route`, and `'ui-route'` to no avail. Any advice?

**Comment by sudhakar** [comment]
Nope. For the time being, I have modified the uiRoute directive itself with `scope: true`, so that it creates a new scope for the element & will be available for its child DOM as well. As of now, it works for me, but I havent tested it in other scenarios.

**Comment by leeola** [comment]
Okay, thanks for replying!

**Comment by ProLoser** [comment]
@leeolayvar it's a bug with the directive that I forgot to address, and I can't merge the fix in until I have the tests passing :frowning:

**Comment by leeola** [comment]
@ProLoser Any idea when this fix will be published to bower? I'm not sure if it's intended for 0.5.0 or not. Either way, it's not shipped with 0.4.0

**Comment by ProLoser** [comment]
@leeolayvar this repo is no longer being actively developed. The latest version (which I believe includes the fix) can be found at [angular-ui/ui-utils](https://github.com/angular-ui/ui-utils)

**Comment by leeola** [comment]
Yea, i was using Route from ui-utils (it does indeed include the fix).

Sounds good though! My apologies for not knowing this repo is closed :)
