### ISSUE TITLE
Calendar: Wiring up underlying fullcalendar events, etc...

### ISSUE THREAD

**Issue by sgentile** [angular-ui/angular-ui-OLDREPO#436]
I've been trying different things to attempt to wire up the underlying fulcalendar events to the controller.

ie.
dayClick, defaultView, etc...

What is the expected way to do this?

Here was what I attempted based on sample:
$scope.eventSource = {
        weekends:false
    };

and

$scope.eventSource = {
        weekends: false,
        reportDayClick: function() {
            alert('here');
        }
    };

and

$scope.eventSource = {
        weekends: false,

```
    dayClick: function() {
        alert('here');
    }
};
```

$scope.eventSources = [$scope.events, $scope.eventSource];

I'm getting no results on this ?

**Comment by joshkurz** [comment]
You initialize the options in a sepereate object that is passed into uiCalendar.

``` javascript
var calendarOptions = {
  option: option
}
```

Then initialize the eventSources like so

``` javascript
$scope.eventSource = [event,event,event]
$scope.eventSource1 = [event,event,event]

$scope.eventSources[$scope.eventSource,$scope.eventSource1]
```

Then pass it all in the html like so

```
<div ui-calendar="calendarOptions" ng-model="eventSources">
```

**Comment by sgentile** [comment]
Thanks

**Comment by eibrahim** [comment]
I am not sure I understand...  How would I listen to the eventClick event?  I want to fire code in my controller when an event is clicked... thanks.

**Comment by joshkurz** [comment]
Just create a method on the scope and pass it into the options object as the eventClick object. 

Use the same parameters as the docs and you will have full access to the data.

**Comment by eibrahim** [comment]
I tried but I think I am doing something wrong. Can you show me a code
sample/example?

Sent from my iPhone

On Mar 28, 2013, at 8:35 PM, Josh Kurz notifications@github.com wrote:

Just create a method on the scope and pass it into the options object as
the eventClick object.

Use the same parameters as the docs and you will have full access to the
data.

Sent from my iPhone

On Mar 28, 2013, at 8:30 PM, eibrahim notifications@github.com wrote:

> I am not sure I understand... How would I listen to the eventClick event?
> I want to fire code in my controller when an event is clicked... thanks.
> 
> —
> Reply to this email directly or view it on GitHub.

—
Reply to this email directly or view it on
GitHubhttps://github.com/angular-ui/angular-ui/issues/436#issuecomment-15623437
.

**Comment by sgentile** [comment]
1. define a 'calendarOptions object that is attached to $scope with the 'eventClick' function
   $scope.calendarOptions = {
       //disableDragging: true,
       //weekends: false,
       height: 450,
       editable: true,
       eventClick: function (event, jsEvent, view) {  
           $scope.item = event;
           $scope.$apply();
       }
   };
   $scope.eventSources = [$scope.events, $scope.eventSource];//[$scope.events];
2. Then in your html - you bind that calendarOptions to the data-ui-calendar
   div data-ui-calendar="calendarOptions" class="span8 calendar" data-ng-model="eventSources"

**Comment by eibrahim** [comment]
Got it...  very helpful...  I am just curious why you call $scope.apply()...  I am not doing that and it is working just fine... thanks again.

**Comment by sgentile** [comment]
that bit of code was me in the the middle of exploring it - I think at one point it wasn't firing the update back and I put that in and it did - but I don't recall the details

**Comment by victormaiasarrasqueiro** [comment]
My friends.. I wrote the same code and it dont work for me,

can you give me the fullcalendar, angular and jquery versions you are  using?
