### ISSUE TITLE
ui-date not setting correct format

### ISSUE THREAD

**Issue by sgentile** [angular-ui/angular-ui-OLDREPO#439]
I have an input as follows:

input data-ng-model="item.start" data-ng-required="true" ui-date="dateOptions" type="text" class="input-medium" placeholder=""

I get a date such as '02/02/2013' displayed

But when I check the 'item.start' bound value is : 
$scope.item.start
Sat Feb 02 2013 00:00:00 GMT-0500 (Eastern Standard Time)

Which because of this, I'm unable to pass to a Date object - getting of course that it's a invalid date.

**Comment by sgentile** [comment]
To add to above, I forgot to put in the 'dateOptions' object:

$scope.dateOptions = {
            dateFormat: 'mm/dd/yy'
        };

**Comment by sgentile** [comment]
I see this was my problem - I need to have this set:

ui-date-format="mm/dd/yy"

**Comment by sgentile** [comment]
Is there a way to get this date back as a valid Date object vs. a string ?

**Comment by jrschumacher** [comment]
Not a sustainable solution but I use [moment](http://momentjs.com/) to convert to a workable date format.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-date (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-date

Please reopen this issue there if it is still relevant.
