### ISSUE TITLE
Add --bare to coffeescript compile?

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#44]
I was wondering if we should add the `--bare` parameter to the coffeescript compiler. There should not be bleeding of variable declarations and it is inconsistent to have closures around some modules but not others. It would perhaps make more sense to wrap the entire angular file in a closure (if this is really necessary) but perhaps this can be done by the minification tool if it's really a concern.

**Comment by petebacondarwin** [comment]
That sounds reasonable.  I try not to look at the generated js code :-)
I'll sort that out tomorrow.  Off to bed now.

On 10 July 2012 21:26, Dean Sofer <
reply@reply.github.com

**Comment by dandoyon** [comment]
agreed
