### ISSUE TITLE
ui-if breaks model binding of checkboxes

### ISSUE THREAD

**Issue by munchboyd** [angular-ui/angular-ui-OLDREPO#445]
``` javascript
// HTML
<input type="checkbox" ng-model="checked" ui-if="should_show()">
<p>{{checked}}</p>

// Controller
$scope.checked = true;
$scope.should_show = function() {return true;};
```

When the page renders, the checkbox is correctly checked and "true" is rendered in the 'p' tag.  However, when you click the checkbox the model will not be updated, so the 'p' tag will still render "true".  The same issue occurs in reverse, i.e. model changes in the controller do not make it to the checkbox.

This problem goes away if I replace "ui-if" with "ng-show"

I've tried angular-ui v0.3.2 and v0.4.0 with angular v1.0.4.

**Comment by ProLoser** [comment]
@joseym can you add an ALERT or NOTE or something to the docs that just says that this directive creates a new child scope.

**Comment by joseym** [comment]
yep.

**Comment by fabiankessler** [comment]
(i fell for this too)
