### ISSUE TITLE
Improve build process and repo organization

### ISSUE THREAD

**Issue by ajoslin** [angular-ui/angular-ui-OLDREPO#449]
Here are some things that I think would make development a lot easier and streamlined on angular-ui.  Some of them are my opinion, and some just need to be done. 
#### Short Term
- [x] Make default `grunt` task use testacular single-run option for tests, removing `grunt server` dependency for `grunt` task
- [x] Make all testacular tasks open Chrome for you by default
- [x] Make each directive's documentation be created with a `docs` folder similar to [https://github.com/angular-ui/bootstrap](bootstrap)
- [x] Make angular-ui.github.com auto-generated from these `docs` folders
#### Longer term
- [ ] Add built files to `gh-pages` branch (similar to [twitter bootstrap repo](https://github.com/twitter/bootstrap/tree/gh-pages/)), and add a link to them in README.
- [ ] Remove `build` folder from version control, and add it to `.gitignore`
#### Longer-er term - if we do this sooner than later we can skip a lot of the things above this
- [ ] Move each module into its own repository. [google groups discussion](https://groups.google.com/forum/#!category-topic/angular-ui/ui/4tEbsfqosDc%5B1-25-false%5D)

**Comment by ProLoser** [comment]
I agree with all the short term changes, and coffee should already be gone.

**Comment by pkozlowski-opensource** [comment]
@ajoslin +1 for all the short-term things and longer-term (from what I can see about 1/3 of PRs got build files checked-in...).

I must say that I'm pretty happy with the way bootstrap's build works and I can see further enhancements (automatic shiv generation, release scripts etc.). 

The only thing to watch out for is that with the current implementation we can't control order of directives on the demo page (say I would like to have $dialog close to modal, no way of doing this).

**Comment by ajoslin** [comment]
Oh you're right, coffee is already gone.  I still have some .coffee.js files leftover in my repo from back in the day.  I'll remove that.

@pkozlowski-opensource you're right.  Perhaps we need an array defining the order somewhere.

**Comment by ProLoser** [comment]
Do you guys think you can make the necessary refactors in a branch for v050?

**Comment by ajoslin** [comment]
I'll work on them this weekend and push them to a new branch.

The docs are going to take the longest - will probably have to be a team effort.
