### ISSUE TITLE
Sortable clobbers scope of other sortable instances

### ISSUE THREAD

**Issue by skahlert** [angular-ui/angular-ui-OLDREPO#450]
It looks like options passed to ui-sortable are overwritten by later instances of sortable. Especially the callbacks (stop for example) seem to reference the wrong scope, when called.
Here's an an example:
http://plnkr.co/edit/o4Sgr6NW0FJrYoigbFOX
Notice, no matter what you sort, it will alert the lower list.

**Comment by ProLoser** [comment]
I get that you wrapped these in closures, can you explain what's going on? Why does this fix it? You may have noted in my comment that I in fact noticed this bug also but I have no idea why there seems to be scope leakage since all variables are declared in the linking phase.
