### ISSUE TITLE
Possible bug > ui-select2 not working with Objects/Integers as values

### ISSUE THREAD

**Issue by saurabhnanda** [angular-ui/angular-ui-OLDREPO#452]
The following code snipped assigns `$scope.numberOfBeers` the value of `i` as a _String_ and not as an _Integer_. Not sure if this is a bug, or something that I'm doing wrong.

```
<select ui-select2 ng-model="numberOfBeers">
  <option ng-repeat="i in arrayWithIntegerValues" value="{{ i }}">{{ i }} beers</option>
</select>
```

**Comment by saurabhnanda** [comment]
Figured out how to use `ui-select` with Object data:

```
<input type="hidden" ui-select2="{'data' : [{'id': 1, 'text' : '1 beer'}, {'id' : 2, 'text' : '2 beers'}]}" ng-model="numberOfBeers" />
```

However, now the value of `$scope.numberOfBeers` is the complete object and not `object.id` as I'd expect. Is this on purpose?

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-select2 (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-select2

Please reopen this issue there if it is still relevant.
