### ISSUE TITLE
Select2 bug Race conditions

### ISSUE THREAD

**Issue by pablocaselas** [angular-ui/angular-ui-OLDREPO#453]
Hi,

I am having a racing condition problem with the select2 directive.

I have an object like this...

``` js
$scope.myModel={
  _id: 1,
   name: "bla bla",
   relation :{
      _id:3
    }
};
$scope.relations =[{_id:1,name:"aaaa"},{_id:3,name:"bbbb"}];
```

And I am using select2 like this...

``` html
<select ui-select2 ng-model="myModel">
<option></option>
<option ng-repeat="relation in relations" value="{{relation._id}}">{{relation.name}}</option>
</select>
```

For some reason, more often than not it will not select the option selected in the ng-model.

I tried this with the select directive from angular and it seems to work just fine.

Any ideas?

**Comment by pablocaselas** [comment]
I am trying to isolate this problem and I the problem seems to be when the model has the value and the select2 doesn't have the list yet.

I am guessing this code has something to do with it 

``` js
// Watch the options dataset for changes
          if (watch) {
            scope.$watch(watch, function (newVal, oldVal, scope) {
              if (!newVal) return;
              // Delayed so that the options have time to be rendered
              setTimeout(function () {
                elm.select2('val', controller.$viewValue);
                // Refresh angular to remove the superfluous option
                elm.trigger('change');
              });
            });
          }
```

Any thoughts on this, guys?

**Comment by ProLoser** [comment]
If you do `<select>` then your values must be primitives (just the id #).

If you want to have the model be an object, use `<input>`. I've been talking to @boneskull and we may refactor `select2` to do what you're thinking it should do.

Try instead:
`$scope.myModel = 1`

**Comment by pablocaselas** [comment]
ProLoser, the ng-model is binded to a value that's a primitive, it's an id. I use the select like this... 

``` html
<select ui-select2 ng-model="myModel.myRelation._id">
   <options ng-repeat="element in elements" value="{{element.id}}">{{element.label}}</option>
</select>
```

Any ideas on how to solve the problem?

**Comment by ProLoser** [comment]
Can you create a plunker?

**Comment by pablocaselas** [comment]
I will try to create a plunkr tomorrow but as I got back to this issue it seems to have something to do with the inicialization of the plugin with $timeout, I managed to get it working delaying the whole function 400 miliseconds, but I am not happy with this solution.

Is there any way we can avoid using timeouts to do the inicialization? I haven't done much research about how select2 works but I will in the next few days to see if I can help solve this problem.

**Comment by pablocaselas** [comment]
This is probably a silly question but, is there a reason why the initialization of the plugin is inside the linking function and not in a compile function?

**Comment by ProLoser** [comment]
You never initialize in compile. On a ngrepeat it would break. Check out
the readme.md in ui-jq.

**Comment by mchapman** [comment]
I am having similar (though less frequent) issues.  I posted about it in the [Google group](https://groups.google.com/forum/#!category-topic/angular-ui/ui/zhL2Y66uuP8).

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-select2 ?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-select2

Please reopen this issue there if it is still relevant.
