### ISSUE TITLE
open modal from iframe

### ISSUE THREAD

**Issue by ThomasDeutsch** [angular-ui/angular-ui-OLDREPO#454]
I would like to open a modal from my angular-app that is running in an iframe.
Right now, the modal shows in the iframe and i tried to make this change to the dialog.js:

I injected $window and replaced this line of code: 
var body = $document.find('body'); 
with
var body = $window.parent.document.find('body');

but i get the error:   window.parent.document is undefined.

Can anybody tell me how this can be achieved  ?

**Comment by ajoslin** [comment]
We should probably have an option for `bodyElement` or something similar, so you can just pass in an element. 

I made [a gist](https://gist.github.com/ajoslin/5008546#file-dialog-with-body-option-js-L69) of an example of how to edit it for your use for now.  Relevant changes are [line 18](https://gist.github.com/ajoslin/5008546#file-dialog-with-body-option-js-L18) and [line 69](https://gist.github.com/ajoslin/5008546#file-dialog-with-body-option-js-L69).
