### ISSUE TITLE
uiMapInfoWindow shared scope causes event misbehaviour

### ISSUE THREAD

**Issue by JakobJingleheimer** [angular-ui/angular-ui-OLDREPO#456]
Hello,

Sharing scope amoung InfoWindows causes misbehaviour of events triggered from within an InfoWindow: http://plnkr.co/edit/HYaBdd?p=preview

Open either MapMarker and click `users`. The aside slides out and slides back in immediately because the value of `newValue` erroneously changes during $watch's execution whilst the value of `aside_users` is correctly changed only once onclick.

To fix this, comment out line 87 of `my-map.js` and uncomment line 88 (line 88 appends `scope` with `.$new()`). My line 87/88 corresponds to line 76 of <a href="https://github.com/angular-ui/angular-ui/blob/master/modules/directives/map/map.js">map.js</a> in the master branch.

**Comment by cyang05** [comment]
Many thanks to you. I spent half day to correct this kind of problem. I went into the wrong direction. I think I need to dig into angular for better understanding in case another angular related problem occurred.

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-map

Please reopen this issue there if it is still relevant.
