### ISSUE TITLE
Bug creates error: undefined method 'version' for AngularUI::Rails:Module

### ISSUE THREAD

**Issue by nguyenannguyen** [angular-ui/angular-ui-OLDREPO#458]
I installed Angular-UI, which runs fine before. But today, when I kick-off rails server, I got the following error:

angular-ui-rails-0.4.0/lib/angular-ui-rails.rb:7:in `<class:Engine>': undefined method`version' for AngularUI::Rails:Module (NoMethodError)

In angular-ui-rails.rb:
`require "angular-ui-rails/version"

module AngularUI
     module Rails
        class Engine < ::Rails::Engine
           # Enabling assets precompiling under rails 3.1
           if Rails.version >= '3.1'
             initializer :assets do |config|
           Rails.application.config.assets.precompile += %w( angular-ui-ieshiv.js )
         end
       end
     end
   end
end`

It seems that there's a naming conflict around Rails used in this module. Please help me to fix this bug.

Thanks.

**Comment by ProLoser** [comment]
Please open this issue on the relevant project: https://github.com/mikepinde/angular-ui-rails
