### ISSUE TITLE
Isolated scope properties are not available in 'pre' link function when using 'templateUrl'

### ISSUE THREAD

**Issue by dana-shalev** [angular-ui/angular-ui-OLDREPO#459]
I have an isolated directive which initializes its scope properties in the `directive.scope` attribute. In the `pre` link function I'm using those scope attributes.
However, I discovered that if i used 'templateUrl' instead of 'template' in my directive suddenly things stop working.

Apparently **when I switched to use 'templateUrl' suddenly the 'pre' link function was called before the scope was initialized with the properties I defined in the `directive.scope` property**.

Take a look at this [plunker](http://plnkr.co/edit/4O8lkYFFmmvvWxvoEYNV?p=preview) for an example:
- The `message` directive defines an isolated scope which has a `message` property taken from the attribute.
- When I print to the console the value of `message` from the `pre` function I get undefined (while in the `post` function I get the actual value).
- If I comment the `templateUrl` property and use `template` instead the `pre` function will also print the actual value.

**Comment by ProLoser** [comment]
Are you sure this is on the correct project?

**Comment by dana-shalev** [comment]
You are right... my mistake... Moving to angular.
Thanks!

**Comment by petebacondarwin** [comment]
Although it is pleasantly reassuring that people are accidentally hitting us rather than the official repository!!
