### ISSUE TITLE
select2 - binding to an object property using ng-model="object['propertyName']" causes an error

### ISSUE THREAD

**Issue by ohana54** [angular-ui/angular-ui-OLDREPO#461]
When binding select2 ng-model to an object property in the following way:
ng-model="object['propertyName']"

I get the following error in the console:
Cannot set property 'propertyName' of undefined

Note that it occurs when the object is still not present, for example has not returned from the server yet.

I created the following plunker to demonstrate: http://plnkr.co/edit/nbbiu5RovZKWcsfPQVQe?p=preview

If I bind to the property like this: ng-model="object.propertyName" then no error is thrown.
Also, this does not occur in the angular-ui select directive, only when using select2.

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-select2

Please reopen this issue there if it is still relevant.
