### ISSUE TITLE
Calendar .fullCalendar() methods

### ISSUE THREAD

**Issue by akath19** [angular-ui/angular-ui-OLDREPO#462]
Hi:

I need to change the calendar event source when a select2 action is performed, currently I can get the select2 action and reassign the event source url like this:

'''javascript

```
   $scope.selectMachine = function()
    {               
        var url = 'http://localhost/prensas/web/app.php/machines' + $scope.machine + '/schedule';

        $scope.event_source = {
            url: url,
            className: 'gcal-event',
            currentTimezone: 'America/Bogota'
        };

        $scope.events = [$scope.event_source];
    }
```

My problem is that even thought the event source is properly changed, the calendar doesn't update. I checked fullCalendar's doc and it says there's a method refetchEvents that refreshes all event sources, however I can't seem to be able to find a way to call this event.

Is there any way to pass this event to fullCalendar via the config object?
Or is there any way to call the event from Angular?

**Comment by joshkurz** [comment]
yes. the calendar is located on the scope that you are using it on. so you can call $scope.calendar.fullCalendar('refetchEvents')

**Comment by joshkurz** [comment]
The reason the calendar is not updating is because you are switching out one event source for another. Since the calendar looks for the length of either the eventSources or the individual events inside the eventSources the calendar thinks that nothing has changed. This is why the equalsTracker attribute has been added to the calendar. You can create a $scope.equalsTracker and pass it into the calendar 

``` html
<div ui-calendar="options" equals-tracker="equalsTracker"> 
```

and then inside your select method when you change the eventSource url you can update the equalsTracker++, which will in turn fire the update method of the calendar.

**Comment by akath19** [comment]
Thank you Josh, I had to both change the event source with .fullCalendar('addEventSource') and move the equalsTracker, I do have one technical question:

Since Angular does two-way data binding, shouldn't changing the eventSource url and adding to the equalsTracker be enough?, I mean, technically there shouldn't be a need to change the event source via fullCalendar but only move the equalsTracker, right?

**Comment by joshkurz** [comment]
yes you are right. if you could post a plunker we can investigate further.

On Tue, Feb 26, 2013 at 2:39 PM, Julian C. notifications@github.com wrote:

> Thank you Josh, I had to both change the event source with
> .fullCalendar('addEventSource') and move the equalsTracker, I do have one
> technical question:
> 
> Since Angular does two-way data binding, shouldn't changing the
> eventSource url and adding to the equalsTracker be enough?, I mean,
> technically there shouldn't be a need to change the event source via
> fullCalendar but only move the equalsTracker, right?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/462#issuecomment-14135061
> .

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by joshkurz** [comment]
im thinking that maybe the calendar should call refetchEvents any time it needs to be updated. Maybe this would save it from having to tear down and be built again, killing two birds with one stone. Ill play with it and see what comes up. 

#469

**Comment by joshkurz** [comment]
There is a couple of PR's that supports this claim, and I believe are the correct solution. Once we move them to https://github.com/angular-ui/ui-calendar then this will be solved and we can rely on the calendar to make the view adjustments regardless of eventSource length or type. Follow along the progress of the PR's and the resolution to this issue will reveal itself.

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-calendar

Please reopen this issue there if it is still relevant.
