### ISSUE TITLE
ui-select2 doesn't work within ng-repeat loop

### ISSUE THREAD

**Issue by elutz** [angular-ui/angular-ui-OLDREPO#463]
I you use an `ui-select2` directive within a `ng-repeat` loop, the initial populate of the selection doesn't work and the (direct) binding of the `ng-model` doesn't work too, see this plnk: http://plnkr.co/edit/bhojhLXr7yglDSfNX44y

I found a workaround (rather a hack):
1. utilizing the `initSelection` ([Docs](http://ivaynberg.github.com/select2/#documentation)) property of _Select2_ in your controller and set the value there.
2. don't use the ng-model directly (e.g. `ng-repeat="item in items"` and `ng-model="item"`) but use a part of the iterator object like `ng-model="item.part"`.

To illustrate the workaround (hack) see this plnk: http://plnkr.co/edit/K5TMyz (unfortunataly not accessible atm)

**Comment by elutz** [comment]
Another workaround in `ui-select2`, this time as a patch of the directive itself and an appropriate plnk: http://plnkr.co/edit/Gi7ID5

``` javascript
if (opts.initSelection) {
    var initSelection = opts.initSelection;
    opts.initSelection = function (element, callback) {
        initSelection(element, function (value) {
            if (value) {
                // normal callback
                controller.$setViewValue(value);
                callback(value);
            }
            else {
                // to circumvent issue #463
                // if you want to use ui-select2 within ng-repeat
                // you have to provide a initSelection callback without any arg
                value = scope.$eval(attrs.ngModel);
                controller.$setViewValue(value);
                callback(value);
            }
        });
    };
}
```

You have to provide an `initSelection` option in your controller and call in this function the callback **without** a value.

Here as a patch:

``` patch
--- plunk/angular-ui.js (revision )
+++ plunk/angular-ui.js (revision )
@@ -103,8 +103,19 @@
                             var initSelection = opts.initSelection;
                             opts.initSelection = function (element, callback) {
                                 initSelection(element, function (value) {
+                                    if (value) {
+                                        // normal callback
-                                    controller.$setViewValue(value);
-                                    callback(value);
+                                        controller.$setViewValue(value);
+                                        callback(value);
+                                    }
+                                    else {
+                                        // to circumvent issue #463
+                                        // if you want to use ui-select2 within ng-repeat
+                                        // you have to provide a initSelection callback without any arg
+                                        value = scope.$eval(attrs.ngModel);
+                                        controller.$setViewValue(value);
+                                        callback(value);
+                                    }
                                 });
                             };
                         }

```

**Comment by dobladez** [comment]
I'm experiencing similar issues on ng-repeat.
I'm also having other init problems even outside of ng-repeat.

Here's my minimal plunk:

http://plnkr.co/edit/d6sE3fgKKP3gdQwh1ese?p=preview

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-select2 (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-select2

Please reopen this issue there if it is still relevant.
