### ISSUE TITLE
Google Maps wroke image under Chrome

### ISSUE THREAD

**Issue by alanloffler** [angular-ui/angular-ui-OLDREPO#464]
The Google Maps directive does'nt work under Chrome version 25.
When the map is clicked, it's attached a big grey box when has to attach the marker.
With Safari it works fine.
I'm under Mac Os 10.8.2

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-map (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-map

Please reopen this issue there if it is still relevant.
