### ISSUE TITLE
Select2: selected option for input value is the object and not the id of the data 

### ISSUE THREAD

**Issue by jonchay** [angular-ui/angular-ui-OLDREPO#465]
Hi there,

I'm wondering if this is an expected behavior. If you initialize a select element for ui-select2, any options selected in the dropdown will resort to the "value" of the option. 

However, if you were to do the same for an input box with an array of id and text, the value selected is the object itself {id:1, text:'test'}. I would think it would select the id of the data as the value for the input.

This makes it a bit difficult when binding it to an ngModel.

Plunkr: http://plnkr.co/edit/IoNTyT?p=preview

**Comment by vpratti** [comment]
@jonchay 

I am having the same issue. How did you fix this issue with the object being selected with the when a input box is used. Can you please share the solution.

Thanks,

**Comment by jonchay** [comment]
@vpratti Sorry, we've removed this functionality and went ahead with a jQuery implementation. Good luck!

**Comment by vpratti** [comment]
@jonchay Thank you.

**Comment by ephraimm** [comment]
@vpratti Having the same issue, did you find a solution?

**Comment by dev-mraj** [comment]
did you find a solution?

**Comment by webpartisan** [comment]
I have the same issue. What is the best way to solve this problem?
