### ISSUE TITLE
uiMap allows map to zoom out too far ( z > 15 )

### ISSUE THREAD

**Issue by JakobJingleheimer** [angular-ui/angular-ui-OLDREPO#466]
I originally thought this was an option I neglected to set, but after a bit of googling, I'm <a href="http://stackoverflow.com/a/2990316/758177">seeing</a> that restricting the zoom to the map's minimum requires a check in the `bounds_changed` event.

It's kind of stupid that the Google Maps API allows the map to be zoomed out farther than it can display, but apparently it does.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-map (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-map

Please reopen this issue there if it is still relevant.
