### ISSUE TITLE
CodeMirror won't show code if I use `ng-show`

### ISSUE THREAD

**Issue by freewind** [angular-ui/angular-ui-OLDREPO#468]
See the demo: http://plnkr.co/edit/bQbN5LYJmrUOYupUA7K5?p=preview
1. Click the button: Show editor and set code
2. The editor is shown, but it's empty
3. Click the editor, scroll your middle-button of the mouse
4. The code will show

**Comment by nateabele** [comment]
This is a CodeMirror issue. It needs to be told to redraw. I'm sure it has an API for this.

**Comment by freewind** [comment]
I think I can use `ui-refersh` to fix it, but I found this line of code: https://github.com/angular-ui/angular-ui/blob/master/modules/directives/codemirror/codemirror.js#L69

```
$timeout(codeMirror.refresh);
```

should be changed to

```
$timeout(function() { codeMirror.refresh()} );
```

Otherwise there will be some error happens when refreshing:

> TypeError: Cannot read property 'curOp' of undefined
>     at http://localhost:9000/public/libs/codemirror/3.1/lib/codemirror.js:1289:41
>     at http://localhost:9000/public/libs/angular/1.0.4/angular.js:9281:28
>     at completeOutstandingRequest (http://localhost:9000/public/libs/angular/1.0.4/angular.js:2956:10)
>     at http://localhost:9000/public/libs/angular/1.0.4/angular.js:3236:7 

But everything will be fine if I use `$timeout(function() { codeMirror.refresh()} );`

**Comment by nateabele** [comment]
Ah, I see, thanks for that. As soon as someone has a chance to write a test for this, we'll patch it and merge. Thanks.
- Nate

**Comment by freewind** [comment]
Is there any update for this issue?

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-codemirror (after confirming it's still necessary with the latest code)?

You may want to try using `ui-refresh` to help you out with this.

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-codemirror

Please reopen this issue there if it is still relevant.

**Comment by amirnissim** [comment]
you can use the [`ui-refresh`](https://github.com/angular-ui/ui-codemirror#ui-refresh-directive) attribute. It will trigger a refresh when the expression changes.

```
<div ng-show="isEditing">
    <textarea ui-codemirror="editorOptions" ui-refresh="isEditing"></textarea>
</div>
```

(I had a similar problem, and Google sent me here. So in the spirit of helping others I shared what worked for me)
