### ISSUE TITLE
uiCalendar > Re-creating the calendar on every update?

### ISSUE THREAD

**Issue by saurabhnanda** [angular-ui/angular-ui-OLDREPO#469]
If I understand https://github.com/angular-ui/angular-ui/blob/master/modules/directives/calendar/calendar.js#L37 correctly, is the directive basically destroying and re-creating the calendar every time `update()` is called? And `update()` is called whenever _anything_ changes in the events data?

Isn't this extremely inefficient? I understand if this is still WIP, and I'd be happy to contribute in making this better.

**Comment by joshkurz** [comment]
Well pretty much that is what it is doing to keep angular and the calendar
in sync with each other. It seems that this is somewhat of the norm for
directives of this nature. The elm.html('') method is called every time
update is called, options are recreated, and then the fullcalendar method
is called again to re-sync the whole process.

yes this is still certainly a WIP, so if you have any suggestions or ideas
then please send some PR's so we can mull over them.

On Sat, Mar 2, 2013 at 3:08 AM, Saurabh Nanda notifications@github.comwrote:

> If I understand
> https://github.com/angular-ui/angular-ui/blob/master/modules/directives/calendar/calendar.js#L37correctly, is the directive basically destroying and re-creating the
> calendar every time update() is called? And update() is called whenever *
> anything\* changes in the events data?
> 
> Isn't this extremely inefficient? I understand if this is still WIP, and
> I'd be happy to contribute in making this better.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/469
> .

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by saurabhnanda** [comment]
@joshkurz : I'm unable to run `grunt` in the `angular-ui` source directory. I get the following error:

> grunt-cli: The grunt command line interface. (v0.1.6)
> Fatal error: Unable to find local grunt.
> If you're seeing this message, either a Gruntfile wasn't found or grunt
> hasn't been installed locally to your project. For more information about
> installing and configuring grunt, please see the Getting Started guide:
> http://gruntjs.com/getting-started

I installed node.js globally, and followed it up with the commands given below:

```
sudo npm install
sudo npm install -g grunt-cli
sudo npm install -g grunt
```

Any help would be appreciated.

**Comment by ghinda** [comment]
@saurabhnanda You'll have to install the 0.3.x version of Grunt, locally.

Inside the angular-ui folder (where grunt.js is located):

```
npm uninstall grunt (if you previously installed it)
sudo npm install -g grunt-cli
npm install grunt@0.3.x
```

**Comment by Raibaz** [comment]
How about using `removeEventSource` http://arshaw.com/fullcalendar/docs/event_data/removeEventSource/ and `addEventSource` http://arshaw.com/fullcalendar/docs/event_data/addEventSource/ to refresh just the events instead of recreating the whole calendar?

I had a pretty rough afternoon yesterday because of this issue, since my calendar kept on going back to the current month whenever I updated the events (and I update them upon changing the displayed month, since I load them on a monthly basis).

So basically what I had was that i changed the month, fetched the events for the chosen month, and then had `update()` refresh the whole calendar and get back to the current date.

I ended up keeping the year and month to display in the scope and then passing them as options to have them displayed upon calling `update()`, but I think it would be better to have just the events updated when they change instead of destroying and recreating the whole calendar.

Will give a try with `removeEventSource` and `addEventSource` in the weekend hopefully.

**Comment by joshkurz** [comment]
I think you are on the right track. I thought about this method as well. I
posted something on SO showing the two fixes for this issue you
are referring too.
http://stackoverflow.com/questions/15676918/using-gotodate-in-fullcalendar-with-angular-ui/15705275#15705275

On Fri, Mar 29, 2013 at 4:18 AM, Mattia Tommasone
notifications@github.comwrote:

> How about using removeEventSource
> http://arshaw.com/fullcalendar/docs/event_data/removeEventSource/ and
> addEventSource
> http://arshaw.com/fullcalendar/docs/event_data/addEventSource/ to refresh
> just the events instead of recreating the whole calendar?
> 
> I had a pretty rough afternoon yesterday because of this issue, since my
> calendar kept on going back to the current month whenever I updated the
> events (and I update them upon changing the displayed month, since I load
> them on a monthly basis).
> 
> So basically what I had was that i changed the month, fetched the events
> for the chosen month, and then had update() refresh the whole calendar
> and get back to the current date.
> 
> I ended up keeping the year and month to display in the scope and then
> passing them as options to have them displayed upon calling update(), but
> I think it would be better to have just the events updated when they change
> instead of destroying and recreating the whole calendar.
> 
> Will give a try with removeEventSource and addEventSource in the weekend
> hopefully.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/469#issuecomment-15632295
> .

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by Raibaz** [comment]
Yep, what you said on SO is exactly what i've been doing to deal with the
whole rebuilding of the calendar...i wish i had stumbled upon your answer
before spending an afternoon trying to get it :)
Il giorno 29/mar/2013 15:30, "Josh Kurz" notifications@github.com ha
scritto:

> I think you are on the right track. I thought about this method as well. I
> posted something on SO showing the two fixes for this issue you
> are referring too.
> 
> http://stackoverflow.com/questions/15676918/using-gotodate-in-fullcalendar-with-angular-ui/15705275#15705275
> 
> On Fri, Mar 29, 2013 at 4:18 AM, Mattia Tommasone

**Comment by joshkurz** [comment]
well I just wrote it so that would have been impressive as it did not
exist.

On Fri, Mar 29, 2013 at 3:48 PM, Mattia Tommasone
notifications@github.comwrote:

> Yep, what you said on SO is exactly what i've been doing to deal with the
> whole rebuilding of the calendar...i wish i had stumbled upon your answer
> before spending an afternoon trying to get it :)
> Il giorno 29/mar/2013 15:30, "Josh Kurz" notifications@github.com ha
> scritto:
> 
> > I think you are on the right track. I thought about this method as well.
> > I
> > posted something on SO showing the two fixes for this issue you
> > are referring too.
> > 
> > http://stackoverflow.com/questions/15676918/using-gotodate-in-fullcalendar-with-angular-ui/15705275#15705275
> > 
> > On Fri, Mar 29, 2013 at 4:18 AM, Mattia Tommasone
> > notifications@github.comwrote:
> > 
> > > How about using removeEventSource
> > > http://arshaw.com/fullcalendar/docs/event_data/removeEventSource/ and
> > > addEventSource
> > > http://arshaw.com/fullcalendar/docs/event_data/addEventSource/ to
> > > refresh
> > > just the events instead of recreating the whole calendar?
> > > 
> > > I had a pretty rough afternoon yesterday because of this issue, since
> > > my
> > > calendar kept on going back to the current month whenever I updated
> > > the
> > > events (and I update them upon changing the displayed month, since I
> > > load
> > > them on a monthly basis).
> > > 
> > > So basically what I had was that i changed the month, fetched the
> > > events
> > > for the chosen month, and then had update() refresh the whole calendar
> > > and get back to the current date.
> > > 
> > > I ended up keeping the year and month to display in the scope and then
> > > passing them as options to have them displayed upon calling update(),
> > > but
> > > I think it would be better to have just the events updated when they
> > > change
> > > instead of destroying and recreating the whole calendar.
> > > 
> > > Will give a try with removeEventSource and addEventSource in the
> > > weekend
> > > hopefully.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/angular-ui/angular-ui/issues/469#issuecomment-15632295>
> > 
> > > .
> > 
> > ## 
> > 
> > _Josh Kurz_
> > http://dillingermediaonline.com/wordpress
> > http://dillingermediaonline.com
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/angular-ui/angular-ui/issues/469#issuecomment-15643087>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/469#issuecomment-15657506
> .

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com
