### ISSUE TITLE
uiCalendar > Any way to have use lazily evaluated function as an eventSource?

### ISSUE THREAD

**Issue by saurabhnanda** [angular-ui/angular-ui-OLDREPO#470]
The subject line says it all. Basically, what's analogous to http://arshaw.com/fullcalendar/docs/event_data/events_function/

**Comment by joshkurz** [comment]
yes this is 100% possible. All event types can be created and inserted into the event sources array. 
One example is here http://angular-ui.github.com the calendar pulls in a google calendar source
Another custom example is here
http://plnkr.co/edit/pIDltQRV6TQGD4KQYnj7?p=preview
