### ISSUE TITLE
Request: Native Angular Slider Component

### ISSUE THREAD

**Issue by bblechman** [angular-ui/angular-ui-OLDREPO#471]
Please add a native angular slider directive.  Dealing with wrapping the JQuery UI one is a PITA, and not fully functional.

Thank you!

**Comment by dandoyon** [comment]
I would like us to do this also , I've wrapped jquery ui slider and it is painful .  I might try taking a first cut at it

Great suggestion

**Comment by heralight** [comment]
You can try fd-slider https://github.com/freqdec/fd-slider and my directive at:
http://www.hera.cc/2013/04/utiser-fd-slider-avec-angularjs-par-lintermediaire-dune-directive/

**Comment by skyl** [comment]
would be nice to have the "range" bit in the native angular version, http://jqueryui.com/slider/#range

**Comment by aaronleesmith** [comment]
I use a self-written implementation in my application. It could use some polish and more features, but it might be a good start. It includes the option to use range or a single value. It could also be extended to enable the changing of the min and max and other settings on the fly with watch expressions.

http://jsfiddle.net/ADukg/2391/
(Compiled from CoffeeScript)

**Comment by ProLoser** [comment]
https://github.com/angular-ui/ui-slider
