### ISSUE TITLE
ui-date-format doesn't display the model value

### ISSUE THREAD

**Issue by ialtamirano** [angular-ui/angular-ui-OLDREPO#474]
When i trying to use the ui-date with ui-date-format applied,

the input associated to the ng-model doesn't display anything.

here is the plunk: http://plnkr.co/edit/ssjH3p?p=preview

**Comment by petebacondarwin** [comment]
Hi @ialtamirano 
You were including the date directive twice!  Once in the main angular-ui.js file and once with the date.js file.
This meant that two date-format $parsers were being attached to the ng-model for that input and the second time this parser was attached it blew up.
Here is a fixed Plnkr (removing the unnecessary date.js): http://plnkr.co/edit/NAVL3h?p=preview

**Comment by ialtamirano** [comment]
now i see, thank you pete !
