### ISSUE TITLE
Pagination Directive click event

### ISSUE THREAD

**Issue by richcouzzi** [angular-ui/angular-ui-OLDREPO#477]
My `<pagination>` directive automatically adds `ng-click="selectPage(page.number)"`, which is all well and good as it controls the pagination bar, but how can I update corresponding data when a page number is clicked? Can I listen for this event? I tried doing this: `<pagination ng-click="myFunction()">`, but no luck.

In short, my params for the pagination setup come from a JSONP response, so I'd like clicking the page numbers to rerun the function to get _that_ page — one of the get vars in my JSONP request is `&page=n`.

Thanks for any and all help.

Also, I apologize if this is in the wrong place, I've never posted an issue on Github before.

**Comment by pkozlowski-opensource** [comment]
Maybe this will help you: http://stackoverflow.com/questions/15076449/angular-pagination-update-data-onclick/15076912#15076912

BTW: I guess you wanted to open an issue here: https://github.com/angular-ui/bootstrap

**Comment by richcouzzi** [comment]
Yes! This is exactly what I needed. Thank you. The only remaining issue is that my index starts with `0` and the pagination starts at `1`. Maybe there's a better way to do this? http://pastebin.com/qU8nkGzX

**Comment by wesleycho** [comment]
This repository is discontinued - if you are still having issues, I recommend opening a new issue in the `angular-ui/bootstrap` repository.
