### ISSUE TITLE
ui-validate-watch triggered validations don't update $modelValue and $viewValue

### ISSUE THREAD

**Issue by hcentelles** [angular-ui/angular-ui-OLDREPO#478]
http://jsfiddle.net/hcentelles/urkda/

The jsfiddle has the description

**Comment by ovax3** [comment]
https://github.com/angular-ui/angular-ui/pull/472 duplicate ?

**Comment by wesleycho** [comment]
Looks like this may be a duplicate - this repository is discontinued anyhow, and any current issues should be brought up in the `ui-utils` repository.
