### ISSUE TITLE
tinymce not updating model in keypress event (found issue/fix)

### ISSUE THREAD

**Issue by mac1175** [angular-ui/angular-ui-OLDREPO#480]
Tested with
- Chrome Version 25.0.1364.160
- Firefox 19.0
- tinymce v3.5.8
- Mac OSX Lion
  I found that the example for [tinymce](http://angular-ui.github.com/#directives-tinymce) doesn't work for me.  Turns out  it is in the keypress when assigning the textarea's val() to the ngModel using

``` js
ngModel.$setViewValue(elm.val());
```

_It works if I use_ 

``` js
ngModel.$setViewValue(this.getContent());
```

Thanks.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-tinymce (after confirming it's still necessary with the latest code)?

**Comment by wesleycho** [comment]
This repository is discontinued, I recommend opening up a new issue in the aforementioned repository that @ProLoser mentioned if it is still an issue.
