### ISSUE TITLE
ui-if and ng-repeat

### ISSUE THREAD

**Issue by johannesjo** [angular-ui/angular-ui-OLDREPO#481]
When I want to use ui-if with ng-repeat (and I think it would be most useful there) I Get an error:
Error: Multiple directives [uiIf, ngRepeat] asking for transclusion on: 

Is there any way to combine those two?

**Comment by joshkurz** [comment]
you could put the ui-if in the outside container.

<div ui-if="">
  <div ng-repeat="">

On Sun, Mar 10, 2013 at 12:55 PM, johannesjo notifications@github.comwrote:

> When I want to use ui-if with ng-repeat (and I think it would be most
> useful there) I Get an error:
> Error: Multiple directives [uiIf, ngRepeat] asking for transclusion on:
> 
> 
> 
> Is there any way to combine those two?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/481
> .

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by johannesjo** [comment]
Sure but I would like tu use a value of the repeat.

Am 10.03.2013 18:16, schrieb Josh Kurz:

> you could put the ui-if in the outside container.
> 
> <div ui-if="">
> <div ng-repeat="">
> 
> On Sun, Mar 10, 2013 at 12:55 PM, johannesjo 
> notifications@github.comwrote:
> 
> > When I want to use ui-if with ng-repeat (and I think it would be most
> > useful there) I Get an error:
> > Error: Multiple directives [uiIf, ngRepeat] asking for transclusion on:
> > 
> > 
> > 
> > Is there any way to combine those two?
> > 
> > —
> > Reply to this email directly or view it on 
> > GitHubhttps://github.com/angular-ui/angular-ui/issues/481
> > .
> 
> ## 
> 
> _Josh Kurz_
> http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com 
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14684845.

## 

Johannes Millan
Pannierstr. 56
12047 Berlin
Tel.: 01523 3940160
Internet: www.designworlds.de

**Comment by joshkurz** [comment]
then you have to do something like

<div ng-repeat="">
  <div ui-if="">

Could mess up your html structure, but its the only way I have found so
far. Its not possible from my understanding to put ui-if and ng-repeat on
the same element.

On Sun, Mar 10, 2013 at 1:18 PM, johannesjo notifications@github.comwrote:

> Sure but I would like tu use a value of the repeat.
> 
> Am 10.03.2013 18:16, schrieb Josh Kurz:
> 
> > you could put the ui-if in the outside container.
> > 
> > <div ui-if="">
> > <div ng-repeat="">
> > 
> > On Sun, Mar 10, 2013 at 12:55 PM, johannesjo
> > notifications@github.comwrote:
> > 
> > > When I want to use ui-if with ng-repeat (and I think it would be most
> > > useful there) I Get an error:
> > > Error: Multiple directives [uiIf, ngRepeat] asking for transclusion on:
> > > 
> > > 
> > > 
> > > Is there any way to combine those two?
> > > 
> > > —
> > > Reply to this email directly or view it on
> > > GitHubhttps://github.com/angular-ui/angular-ui/issues/481
> > > .
> > 
> > ## 
> > 
> > _Josh Kurz_
> > http://dillingermediaonline.com/wordpress
> > http://dillingermediaonline.com
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14684845
> > .
> 
> ## 
> 
> Johannes Millan
> Pannierstr. 56
> 12047 Berlin
> Tel.: 01523 3940160
> Internet: www.designworlds.de
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/481#issuecomment-14684878
> .

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by johannesjo** [comment]
Thank you, but this kinda defeats the purpose to style it efficiently 
with css (eg. the first-child-selector).

Am 10.03.2013 18:22, schrieb Josh Kurz:

> then you have to do something like
> 
> <div ng-repeat="">
> <div ui-if="">
> 
> Could mess up your html structure, but its the only way I have found so
> far. Its not possible from my understanding to put ui-if and ng-repeat on
> the same element.
> 
> On Sun, Mar 10, 2013 at 1:18 PM, johannesjo 
> notifications@github.comwrote:
> 
> > Sure but I would like tu use a value of the repeat.
> > 
> > Am 10.03.2013 18:16, schrieb Josh Kurz:
> > 
> > > you could put the ui-if in the outside container.
> > > 
> > > <div ui-if="">
> > > <div ng-repeat="">
> > > 
> > > On Sun, Mar 10, 2013 at 12:55 PM, johannesjo
> > > notifications@github.comwrote:
> > > 
> > > > When I want to use ui-if with ng-repeat (and I think it would be 
> > > > most
> > > > useful there) I Get an error:
> > > > Error: Multiple directives [uiIf, ngRepeat] asking for 
> > > > transclusion on:
> > > > 
> > > > 
> > > > 
> > > > Is there any way to combine those two?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on
> > > > GitHubhttps://github.com/angular-ui/angular-ui/issues/481
> > > > .
> > > 
> > > ## 
> > > 
> > > _Josh Kurz_
> > > http://dillingermediaonline.com/wordpress
> > > http://dillingermediaonline.com
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14684845
> > 
> > > .
> > 
> > ## 
> > 
> > Johannes Millan
> > Pannierstr. 56
> > 12047 Berlin
> > Tel.: 01523 3940160
> > Internet: www.designworlds.de
> > 
> > —
> > Reply to this email directly or view it on 
> > GitHubhttps://github.com/angular-ui/angular-ui/issues/481#issuecomment-14684878
> > .
> 
> ## 
> 
> _Josh Kurz_
> http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com 
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14684960.

## 

Johannes Millan
Pannierstr. 56
12047 Berlin
Tel.: 01523 3940160
Internet: www.designworlds.de

**Comment by joshkurz** [comment]
I feel you, but im not sure what else to do in a situation like this. Anyone else?

**Comment by joshkurz** [comment]
maybe we could try to rewrite ng-repeat to take an attribute that
checks whether or not to create the element. Not sure if this is already in
place or not. I haven't seen anything about it yet.

On Sun, Mar 10, 2013 at 2:11 PM, Josh Kurz jkurz25@gmail.com wrote:

> I feel you, but im not sure what else to do in a situation like this.
> Anyone else?
> 
> Sent from my iPhone
> 
> On Mar 10, 2013, at 1:24 PM, johannesjo notifications@github.com wrote:
> 
> Thank you, but this kinda defeats the purpose to style it efficiently
> with css (eg. the first-child-selector).
> 
> Am 10.03.2013 18:22, schrieb Josh Kurz:
> 
> > then you have to do something like
> > 
> > <div ng-repeat="">
> > <div ui-if="">
> > 
> > Could mess up your html structure, but its the only way I have found so
> > far. Its not possible from my understanding to put ui-if and ng-repeat on
> > the same element.
> > 
> > On Sun, Mar 10, 2013 at 1:18 PM, johannesjo
> > notifications@github.comwrote:
> > 
> > > Sure but I would like tu use a value of the repeat.
> > > 
> > > Am 10.03.2013 18:16, schrieb Josh Kurz:
> > > 
> > > > you could put the ui-if in the outside container.
> > > > 
> > > > <div ui-if="">
> > > > <div ng-repeat="">
> > > > 
> > > > On Sun, Mar 10, 2013 at 12:55 PM, johannesjo
> > > > notifications@github.comwrote:
> > > > 
> > > > > When I want to use ui-if with ng-repeat (and I think it would be
> > > > > most
> > > > > useful there) I Get an error:
> > > > > Error: Multiple directives [uiIf, ngRepeat] asking for
> > > > > transclusion on:
> > > > > 
> > > > > 
> > > > > 
> > > > > Is there any way to combine those two?
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on
> > > > > GitHubhttps://github.com/angular-ui/angular-ui/issues/481
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > _Josh Kurz_
> > > > http://dillingermediaonline.com/wordpress
> > > > http://dillingermediaonline.com
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14684845
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Johannes Millan
> > > Pannierstr. 56
> > > 12047 Berlin
> > > Tel.: 01523 3940160
> > > Internet: www.designworlds.de
> > > 
> > > —
> > > Reply to this email directly or view it on
> > > GitHub<
> > > https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14684878>
> > > .
> > 
> > ## 
> > 
> > _Josh Kurz_
> > http://dillingermediaonline.com/wordpress
> > http://dillingermediaonline.com
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14684960
> > .
> 
> ## 
> 
> Johannes Millan
> Pannierstr. 56
> 12047 Berlin
> Tel.: 01523 3940160
> Internet: www.designworlds.de
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/481#issuecomment-14685004
> .

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by johannesjo** [comment]
Havent tried it yet, but maybe the best approach would be to use a 
filter for that, now that i'm thinking about it. but i still think it 
would be nice, to have a built-in-functionality for ng-repeat.

Am 10.03.2013 21:53, schrieb Josh Kurz:

> maybe we could try to rewrite ng-repeat to take an attribute that
> checks whether or not to create the element. Not sure if this is 
> already in
> place or not. I haven't seen anything about it yet.
> 
> On Sun, Mar 10, 2013 at 2:11 PM, Josh Kurz jkurz25@gmail.com wrote:
> 
> > I feel you, but im not sure what else to do in a situation like this.
> > Anyone else?
> > 
> > Sent from my iPhone
> > 
> > On Mar 10, 2013, at 1:24 PM, johannesjo notifications@github.com 
> > wrote:
> > 
> > Thank you, but this kinda defeats the purpose to style it efficiently
> > with css (eg. the first-child-selector).
> > 
> > Am 10.03.2013 18:22, schrieb Josh Kurz:
> > 
> > > then you have to do something like
> > > 
> > > <div ng-repeat="">
> > > <div ui-if="">
> > > 
> > > Could mess up your html structure, but its the only way I have 
> > > found so
> > > far. Its not possible from my understanding to put ui-if and 
> > > ng-repeat on
> > > the same element.
> > > 
> > > On Sun, Mar 10, 2013 at 1:18 PM, johannesjo
> > > notifications@github.comwrote:
> > > 
> > > > Sure but I would like tu use a value of the repeat.
> > > > 
> > > > Am 10.03.2013 18:16, schrieb Josh Kurz:
> > > > 
> > > > > you could put the ui-if in the outside container.
> > > > > 
> > > > > <div ui-if="">
> > > > > <div ng-repeat="">
> > > > > 
> > > > > On Sun, Mar 10, 2013 at 12:55 PM, johannesjo
> > > > > notifications@github.comwrote:
> > > > > 
> > > > > > When I want to use ui-if with ng-repeat (and I think it 
> > > > > > would be
> > > > > > most
> > > > > > useful there) I Get an error:
> > > > > > Error: Multiple directives [uiIf, ngRepeat] asking for
> > > > > > transclusion on:
> > > > > > 
> > > > > > 
> > > > > > 
> > > > > > Is there any way to combine those two?
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on
> > > > > > GitHubhttps://github.com/angular-ui/angular-ui/issues/481
> > > > > > .
> > > > > 
> > > > > ## 
> > > > > 
> > > > > _Josh Kurz_
> > > > > http://dillingermediaonline.com/wordpress
> > > > > http://dillingermediaonline.com
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > 
> > https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14684845
> > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Johannes Millan
> > > > Pannierstr. 56
> > > > 12047 Berlin
> > > > Tel.: 01523 3940160
> > > > Internet: www.designworlds.de
> > > > 
> > > > —
> > > > Reply to this email directly or view it on
> > > > GitHub<
> > 
> > https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14684878>
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > _Josh Kurz_
> > > http://dillingermediaonline.com/wordpress
> > > http://dillingermediaonline.com
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14684960
> > 
> > > .
> > 
> > ## 
> > 
> > Johannes Millan
> > Pannierstr. 56
> > 12047 Berlin
> > Tel.: 01523 3940160
> > Internet: www.designworlds.de
> > 
> > —
> > Reply to this email directly or view it on 
> > GitHubhttps://github.com/angular-ui/angular-ui/issues/481#issuecomment-14685004
> > .
> 
> ## 
> 
> _Josh Kurz_
> http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com 
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14689040.

## 

Johannes Millan
Pannierstr. 56
12047 Berlin
Tel.: 01523 3940160
Internet: www.designworlds.de

**Comment by joshkurz** [comment]
yeah but I think your right that a filter on ng-repeat would do the trick.

On Sun, Mar 10, 2013 at 4:59 PM, johannesjo notifications@github.comwrote:

> Havent tried it yet, but maybe the best approach would be to use a
> filter for that, now that i'm thinking about it. but i still think it
> would be nice, to have a built-in-functionality for ng-repeat.
> 
> Am 10.03.2013 21:53, schrieb Josh Kurz:
> 
> > maybe we could try to rewrite ng-repeat to take an attribute that
> > checks whether or not to create the element. Not sure if this is
> > already in
> > place or not. I haven't seen anything about it yet.
> > 
> > On Sun, Mar 10, 2013 at 2:11 PM, Josh Kurz jkurz25@gmail.com wrote:
> > 
> > > I feel you, but im not sure what else to do in a situation like this.
> > > Anyone else?
> > > 
> > > Sent from my iPhone
> > > 
> > > On Mar 10, 2013, at 1:24 PM, johannesjo notifications@github.com
> > > wrote:
> > > 
> > > Thank you, but this kinda defeats the purpose to style it efficiently
> > > with css (eg. the first-child-selector).
> > > 
> > > Am 10.03.2013 18:22, schrieb Josh Kurz:
> > > 
> > > > then you have to do something like
> > > > 
> > > > <div ng-repeat="">
> > > > <div ui-if="">
> > > > 
> > > > Could mess up your html structure, but its the only way I have
> > > > found so
> > > > far. Its not possible from my understanding to put ui-if and
> > > > ng-repeat on
> > > > the same element.
> > > > 
> > > > On Sun, Mar 10, 2013 at 1:18 PM, johannesjo
> > > > notifications@github.comwrote:
> > > > 
> > > > > Sure but I would like tu use a value of the repeat.
> > > > > 
> > > > > Am 10.03.2013 18:16, schrieb Josh Kurz:
> > > > > 
> > > > > > you could put the ui-if in the outside container.
> > > > > > 
> > > > > > <div ui-if="">
> > > > > > <div ng-repeat="">
> > > > > > 
> > > > > > On Sun, Mar 10, 2013 at 12:55 PM, johannesjo
> > > > > > notifications@github.comwrote:
> > > > > > 
> > > > > > > When I want to use ui-if with ng-repeat (and I think it
> > > > > > > would be
> > > > > > > most
> > > > > > > useful there) I Get an error:
> > > > > > > Error: Multiple directives [uiIf, ngRepeat] asking for
> > > > > > > transclusion on:
> > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > Is there any way to combine those two?
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on
> > > > > > > GitHubhttps://github.com/angular-ui/angular-ui/issues/481
> > > > > > > .
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > _Josh Kurz_
> > > > > > http://dillingermediaonline.com/wordpress
> > > > > > http://dillingermediaonline.com
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > 
> > https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14684845
> > 
> > > > > > .
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Johannes Millan
> > > > > Pannierstr. 56
> > > > > 12047 Berlin
> > > > > Tel.: 01523 3940160
> > > > > Internet: www.designworlds.de
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on
> > > > > GitHub<
> > 
> > https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14684878>
> > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > _Josh Kurz_
> > > > http://dillingermediaonline.com/wordpress
> > > > http://dillingermediaonline.com
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14684960
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Johannes Millan
> > > Pannierstr. 56
> > > 12047 Berlin
> > > Tel.: 01523 3940160
> > > Internet: www.designworlds.de
> > > 
> > > —
> > > Reply to this email directly or view it on
> > > GitHub<
> > > https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14685004>
> > > 
> > > .
> > 
> > ## 
> > 
> > _Josh Kurz_
> > http://dillingermediaonline.com/wordpress
> > http://dillingermediaonline.com
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/angular-ui/angular-ui/issues/481#issuecomment-14689040
> > .
> 
> ## 
> 
> Johannes Millan
> Pannierstr. 56
> 12047 Berlin
> Tel.: 01523 3940160
> Internet: www.designworlds.de
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/481#issuecomment-14689152
> .

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com

**Comment by ProLoser** [comment]
Definitely should be using a filter.
