### ISSUE TITLE
select2 doesn't update the view when dynamically changing ng-model values

### ISSUE THREAD

**Issue by vlamic** [angular-ui/angular-ui-OLDREPO#483]
After page has been loaded, the bound value is displayed correctly, but if ng-model was changed, the view gets broken.

With select2 version 3.3.1: http://plnkr.co/edit/vTFqP9pSn9QgJUkPuzRx?p=preview
You can see that after page has been loaded, the selected values are displayed. If you click "Change tags" or "Change tags2" the view gets broken.

With select version 3.2: http://plnkr.co/edit/NITfYJ1tPYatJFmK4UQJ?p=preview the view get bound to correct number of items if you click "Change tags" or "Change tags2", but the values displayed are still broken.

**Comment by vlamic** [comment]
I guess it could work if you keep specific for select2 data format {id: "someId", text: "sometext" }, but then we loose benefits of data binding. It would be at least nice to have ability set some proxy functions to set data to and from select2 and keep bound object to ng-model the same structure as it was before.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-select2 (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-select2

Please reopen this issue there if it is still relevant.
