### ISSUE TITLE
Angular UI website build seems to be down

### ISSUE THREAD

**Issue by drewhamlett** [angular-ui/angular-ui-OLDREPO#484]
When I go to github page and click create build I get

failed http://50.116.42.77:3001/api/angular-ui

**Comment by bennlich** [comment]
I also am not able to add any modules--the autocomplete shows no results.

**Comment by just-boris** [comment]
Please, update your build-server. I want to get build with new version of ui-mask directive, but server is down

**Comment by ajoslin** [comment]
Fixed! Sorry :-)
