### ISSUE TITLE
Select2 mobile support issue

### ISSUE THREAD

**Issue by pablocaselas** [angular-ui/angular-ui-OLDREPO#488]
Hi,

I am testing angular-ui's select2 in an ipad and a nexus 7 and it fails.

In iPad it won't show the options and it will reload the page, and on a nexus 7 it shows the options but when I try to filter it will close itself.

If you have an iOS device or an Android device you can try it here...

http://plnkr.co/edit/Hmt1OXYvtHOAZPzW7YK3?p=preview

**Comment by ProLoser** [comment]
Is this problem specific to AngularUI or is it a problem with Select2 it self? If this is a bug with Select2 itself (which I believe it is) then you should close this bug and open a new one on the relevant project.

**Comment by pablocaselas** [comment]
It works fine on select2 3.3.1 but not in AngularUI's implementation.

**Comment by pablocaselas** [comment]
My apologies, I've upgraded select2.js to 3.3.1 and works like a charm!

Thanks Dean!
