### ISSUE TITLE
"Ctrl-space" keypress differences on OS X / Windows and Firefox / Chrome

### ISSUE THREAD

**Issue by arnaudbreton** [angular-ui/angular-ui-OLDREPO#492]
Hi,

I'm using the KeyPress directive to handle keyboards events.

I don't why but the "space" key is not well handled by this directive on OS X (Mountain Lion 10.8). I have to handle "ctrl-0" to make it work on Chrome. In Firefox, it's ctrl-O which match to this combination..
On Windows, "ctrl-space" is OK in Chrome, not in Firefox.

What can explain these differences?

Thanks.

**Comment by arturgspb** [comment]
+1 vote

**Comment by ProLoser** [comment]
Can you please relocate this to @angular-ui/ui-utils

**Comment by ProLoser** [comment]
This project is discontinued. Please reopen this issue on angular-ui/ui-utils
