### ISSUE TITLE
Keypress 'ctrl-enter' doesn't work?

### ISSUE THREAD

**Issue by freewind** [angular-ui/angular-ui-OLDREPO#493]
live demo: http://plnkr.co/edit/yRQXxFasz1KCYubDNYwS?p=preview

Key code:

```
<input ui-keypress="{'ctrl-enter': 'run($event)'}" placeholder="press ctrl+enter" />
```

and 

```
  $scope.run = function( $event){
    alert('pressed');
    $event.preventDefault();
  }
```

When I press on the input with "ctrl+enter", nothing happens. My browser is chrome.

**Comment by freewind** [comment]
But it does work on firefox. Is it a chrome issue?

**Comment by shaungrady** [comment]
Works for me, Mac Chrome 25.0.1364.172

**Comment by arnaudbreton** [comment]
Same than https://github.com/angular-ui/angular-ui/issues/492 I guess

**Comment by ProLoser** [comment]
Can you please relocate this to @angular-ui/ui-utils

**Comment by wesleycho** [comment]
If this is still an issue, I recommend filing a new issue with the `ui-utils` repository.
