### ISSUE TITLE
Ui-mask doesn't work with some mask expressions

### ISSUE THREAD

**Issue by kliniki-online** [angular-ui/angular-ui-OLDREPO#494]
When mask expression contains numbers in placeholders, model value is parsed incorrectly.
Try to input phone number in this example:
http://plnkr.co/edit/e5TQcS

**Comment by shaungrady** [comment]
It's far from an easy problem to solve, but it's one I'm aware of, and one that still exists in the refactored directive coming out with the next release. Can't promise I'll be able to solve it anytime soon.

**Comment by shaungrady** [comment]
I think I've developed a solution that will work in most cases when a mask definition contains maskable character. It works with your example. It only requires that there has to be at least one mask character of separation exists between the potentially maskable character and the non-mask characters. E.g., a mask definition of '999 5 999' would work, but '9995 999' or '999 5999' would lead to bleeding problems in some cases.

You can try out the new directive here: https://github.com/angular-ui/ui-utils/tree/master/modules/mask
If you don't want to bring it over to your project, you can simply clone the repo and open the index.html in the /demo/ directory to give it a try.

Let me know if you find any problems with it.

**Comment by just-boris** [comment]
New version of directive has made the trick. I will be wait it in next release angular-ui.
