### ISSUE TITLE
Provided jquery.maskedinput.js incompatible with jQuery 1.9

### ISSUE THREAD

**Issue by jdpedrie** [angular-ui/angular-ui-OLDREPO#495]
The version of jquery.maskedinput.js found [here](http://angular-ui.github.com/lib/maskedinput/jquery.maskedinput.js) causes an error with jQuery 1.9:

```
Uncaught TypeError: Cannot read property 'msie' of undefined (line 8)
```

According to [this](http://stackoverflow.com/questions/14337859/jquery-browser-javascript-uncaught-typeerror) post on StackOverflow, `$.browser` was removed in jQuery 1.9. Accordingly, removing the reference to `$.browser` from the plugin fixes the error.

**Comment by shaungrady** [comment]
I've refactored the uiMask directive from the ground up and it no longer has any dependencies. It will be out with the next AngularUI release.

**Comment by jdpedrie** [comment]
Is there an expected release date?

**Comment by shaungrady** [comment]
I'm not responsible for those decisions, so I don't know. The codebase is being reorganized, so things are in a bit of a state of flux at the moment. 

You can grab the directive yourself from the repo and add it to your project by hand:
https://github.com/angular-ui/angular-ui/tree/master/modules/directives/mask

It's been pretty thoroughly tested and should be able to stand up to a production enviro, but I always welcome any feedback and bug reports.
