### ISSUE TITLE
Directive uiDateFormat Not Handling null Values

### ISSUE THREAD

**Issue by kevinastone** [angular-ui/angular-ui-OLDREPO#496]
When you clear a model, `uiDateFormat` converts it from null to undefined because the $parsers don't return any value (hence `undefined`) when the value is false.  Needed for both default ISO formatting and custom formatting.

```
        modelCtrl.$parsers.push(function(value){
          if (value) {
            return value.toISOString();
          }
        }
```

Needs extra return:

```
        modelCtrl.$parsers.push(function(value){
          if (value) {
            return value.toISOString();
          }
          return value;
        }
```

**Comment by petebacondarwin** [comment]
Sounds reasonable.  If you fancied making a Pull Request, with a unit test that demonstrates the problem I can merge it in.  Otherwise I can do a fix but not this week.

**Comment by kevinastone** [comment]
For my needs, I'm still back on 0.3.2, so I just patched my copy.  I just don't have the time to build a proper pull-request for such a simple one-liner, but thought I could at least report it.

Thanks.

**Comment by petebacondarwin** [comment]
Thank you for reporting it.
I am glad that you are benefiting from this community built directive.
I hope it is helping you get your work done faster.

**Comment by petebacondarwin** [comment]
By the way, uiDate has now moved to a new project repos: https://github.com/angular-ui/ui-date

**Comment by petebacondarwin** [comment]
Fixed in https://github.com/angular-ui/ui-date/commit/37687199651f3c6d4b78bebfcf46a4db28716f81
