### ISSUE TITLE
Select2 closeOnSelect issue

### ISSUE THREAD

**Issue by johntom** [angular-ui/angular-ui-OLDREPO#498]
Hi,
I'm using version 3.3.1 of select2, 0.4.0 of angular-ui and setting  multiple="multiple" and                  closeOnSelect='false' but the close event happens regardless of setting. The following illustrates issue.
http://plnkr.co/edit/y4tTumkYPjlwqomWfKNQ?p=preview
TIA
John

**Comment by johntom** [comment]
Hi,
Just checking in and want to explain the request a little further. If using the multiple tag, it would be nice to let the user select one or more options from the list, closeOnSelect is the select2 alternative to having check boxes next to each selection.
Thanks,
John

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-select2 (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-select2

Please reopen this issue there if it is still relevant.
