### ISSUE TITLE
Select2 in custom build of AngularUI doesn't work the same as Select2 in the full version

### ISSUE THREAD

**Issue by fxck** [angular-ui/angular-ui-OLDREPO#500]
Custom build with just Select2 directive
http://plnkr.co/edit/Qcl0bqjqt04rGuYXyp3E?p=preview

Full AngularUI
http://plnkr.co/edit/VGLYHKheu78Ea4mGQKaA?p=preview

No options are selected in the custom version. There's no mention of any additional modules needed to get select2 to work on the website. So why does work in the full version?

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-select2 (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-select2

Please reopen this issue there if it is still relevant.
