### ISSUE TITLE
[Proposal] Scrollfix should accept an option to define the scrolling element.

### ISSUE THREAD

**Issue by mjsarfatti** [angular-ui/angular-ui-OLDREPO#501]
At the moment scrollfix watches only the window scrolling. In my implementation the element I would like to apply ui-scrollfix to is in an absolutely positioned div, which is the one that scrolls. The window never scrolls instead, and ui-scrollfix is never triggered.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-utils (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-utils

Please reopen this issue there if it is still relevant.
