### ISSUE TITLE
ui-keypress - On Div/Body: Not working as expected in IE

### ISSUE THREAD

**Issue by OClement** [angular-ui/angular-ui-OLDREPO#502]
ui-keypress/keydown/etc won't work when set on a div or body in IE, unless you specifically clicked or focused on that element before.

Event seems to bubble up just fine in FF and Chrome (I assume this is what's happening

http://plnkr.co/edit/g8olLlKjuB7bZBQtcJd7
(Not sure if plunk will work fine, had weird problems in setting this up and couldn't load it in my VM for IE. I'm using a mac othwerwise)

I want to be able to use ui-keypress directive's application-wide, so that no matter what the user is doing, he can hit ctrl-enter and trigger a function

**Comment by wesleycho** [comment]
If this is still an issue, I recommend opening up a new issue in the `ui-utils` repository - this repository is discontinued.
