### ISSUE TITLE
ui-date-format support for unix timestamp as a number

### ISSUE THREAD

**Issue by derickson82** [angular-ui/angular-ui-OLDREPO#504]
I attempted to use the jquery date format '@' to interpret a unix timestamp (a number in my model), but it doesn't work because ui-date-format only appears to work with strings.

**Comment by jrschumacher** [comment]
Looking at the code it seems right. Is your unix timestamp in sec or milliseconds?

See [date.js:85-94](https://github.com/angular-ui/angular-ui/blob/master/modules/directives/date/date.js#L85-94):

``` javascript
        modelCtrl.$formatters.push(function(value) {
          if (angular.isString(value) ) {
            return $.datepicker.parseDate(dateFormat, value);
          }
        });
        modelCtrl.$parsers.push(function(value){
          if (value) {
            return $.datepicker.formatDate(dateFormat, value);
          }
        });
```

Valid DateFormats: http://docs.jquery.com/UI/Datepicker/formatDate

**Comment by jrschumacher** [comment]
So I was wrong see my patch #554

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-date (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-date

Please reopen this issue there if it is still relevant.
