### ISSUE TITLE
ui-sortable updates model but does not trigger event required to notify...

### ISSUE THREAD

**Issue by robertjchristian** [angular-ui/angular-ui-OLDREPO#506]
I have elements displayed 3 by N via NG-repeat in a tab, tied to model foo.  Just above the repeat I use ui-sortable with the option below....

```
// http://api.jqueryui.com/sortable/#option-axis
$scope.sortableOptions = {
    update: function(e, ui) {
      console.log('Order of list updated...');
}
```

When I sort, the log call is made as expected, and my bound raw print out of the model is changed to accurately reflect the new order.

However my scope.watch on the same model is not triggered.  Is this as designed?  Seems like if the ordering within a list foo is changed, then watch foo should be called as well?

**Comment by robertjchristian** [comment]
My intention is to sort items in model foo within one view, and have them update in another view where they reside in a ng-grid.  But ng-grid does not update.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-sortable (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-sortable

Please reopen this issue there if it is still relevant.
