### ISSUE TITLE
ui-sortable does not bind model for more then one applications on page

### ISSUE THREAD

**Issue by musukvl** [angular-ui/angular-ui-OLDREPO#507]
I have created angularjs application with sortable list. My application can be included to the page few times with other different applications. 

http://jsfiddle.net/X2h8W/

![angular-ui](https://f.cloud.github.com/assets/3954761/295181/b7f458a2-9462-11e2-9a8f-48f1ff773047.png)

For this case ui-sortable works only for last application in a page. This code: angular.bootstrap(document, ['myapp']); fixes problem, but I want have few isolated application on a page.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-sortable (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-sortable

Please reopen this issue there if it is still relevant.
