### ISSUE TITLE
scrollfix requires jQuery

### ISSUE THREAD

**Issue by aknoerig** [angular-ui/angular-ui-OLDREPO#508]
Since scrollfix makes use of elem.offset(), jQuery is required.
It would be good to mention this in the docs to avoid confusion. :)

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-utils (after confirming it's still necessary with the latest code)?

**Comment by aknoerig** [comment]
Sure, I just recreated the issue over there.
