### ISSUE TITLE
Just a few ideas/comments

### ISSUE THREAD

**Issue by freeslugs** [angular-ui/angular-ui-OLDREPO#509]
So I would just make step 6. more clear - maybe show some code, (angular.module('demoApp', ['ui'], function($locationProvider) {
    $locationProvider.hashPrefix('');
    // Make code pretty
    window.prettyPrint && prettyPrint();
});
also, i would like a datetime picker, not just a date picker. maybe use http://trentrichardson.com/examples/timepicker/#basic_examples
and thanks, you really saved my but with your extensions

**Comment by joshkurz** [comment]
I have used the datepicker with the timepicker successfully. At first I had
to make zero tweeks, but then made it so custom that I couldnt show it, but
I can assure you that the same directive works with that file as well.

On Mon, Mar 25, 2013 at 1:48 PM, freeslugs notifications@github.com wrote:

> So I would just make step 6. more clear - maybe show some code,
> (angular.module('demoApp', ['ui'], function($locationProvider) {
> $locationProvider.hashPrefix('');
> // Make code pretty
> window.prettyPrint && prettyPrint();
> });
> also, i would like a datetime picker, not just a date picker. maybe use
> http://trentrichardson.com/examples/timepicker/#basic_examples
> and thanks, you really saved my but with your extensions
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/509
> .

## 

_Josh Kurz_
http://dillingermediaonline.com/wordpresshttp://dillingermediaonline.com
