### ISSUE TITLE
ui-config requires user to use all modules not just 'ui.directives' or 'ui.filters'

### ISSUE THREAD

**Issue by dandoyon** [angular-ui/angular-ui-OLDREPO#51]
When I created unit test for updated uiCurrency, i realized that I had to inject 'ui' instead of just 'ui.directives' in order for it to work.

Using below, my test now work but am not sure if this is good solution. 

angular.module('ui.filters', []).value('ui.config', {});
angular.module('ui.directives', []).value('ui.config', {});
angular.module('ui', [
  'ui.filters', 
  'ui.directives'
]).value('ui.config', {});

**Comment by ProLoser** [comment]
The way it's setup, including ui includes all directives, all filters and also the default ui.config value, yes.

You should not be including anything else however, only ui. I was toying with the idea of letting people include whatever modules they want, but concluded that this would clutter the project with lots of modules and instead opted against it. Instead I think it's better to simply have 1 point of entry (including ui) and let people delete or add files as they wish, or adding them to their minified package. This way, when you add a module, you do not have to make any changes to your code.

You should not be declaring the value on each module however. Just use the common/modules.js as is without modification and the directive you want to use and you should be good. No custom code is necessary.

**Comment by dandoyon** [comment]
Got it, I agree
