### ISSUE TITLE
Keypress directive on Firefox Windows get all keys

### ISSUE THREAD

**Issue by arnaudbreton** [angular-ui/angular-ui-OLDREPO#511]
Hi,

I've just seen that under the last stable version of Firefox (19.0.2) for Windows (Seven, 64 bits) the Keypress directive intercept all the keys, not only the one declared in the directive.

It works under the same version for Mac OS X.

Thanks for your help.

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-utils

Please reopen this issue there if it is still relevant.
