### ISSUE TITLE
"ctrl-enter" keypress of "uiKeypress" for chrome

### ISSUE THREAD

**Issue by freewind** [angular-ui/angular-ui-OLDREPO#516]
```
<textarea ui-keypress="{'ctrl-enter': 'doSomething($event)'}"></textarea>  
```

This works on firefox, but not for chrome. Because when pressing `ctrl-enter`, the keycode of `enter` is not `13` not more, instead, it's `10`.

So the right code is:

```
<textarea ui-keypress="{'ctrl-enter ctrl-10': 'doSomething($event)'}"></textarea>  
```

I think it can be fixed in the code, or documented in the web page.

**Comment by arnaudbreton** [comment]
Experienced the same with space.

Cf. https://github.com/angular-ui/angular-ui/issues/492

**Comment by ProLoser** [comment]
Can you please relocate this to @angular-ui/ui-utils

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-utils

Please reopen this issue there if it is still relevant.
