### ISSUE TITLE
"uiKeypress" doesn't work with "codeMirror"

### ISSUE THREAD

**Issue by freewind** [angular-ui/angular-ui-OLDREPO#517]
```
<textarea ui-codemirror="{theme:'lesser-dark','lineNumbers': true}"
                      ui-keypress="{'ctrl-10 ctrl-enter':'xxx($event)'}"
                    ></textarea>
```

The key bindings doesn't work if there is `ui-codemirror`

**Comment by ProLoser** [comment]
That's because the editor is not a `<textarea>` and as such most events don't get sent to it. You should look at the CodeMirror API for adding such an event.
