### ISSUE TITLE
Issue when two ui-dates share the same ngModel and then you change one of them.

### ISSUE THREAD

**Issue by bs-thomas** [angular-ui/angular-ui-OLDREPO#521]
I rectified an issue when two ui-dates share the same ngModel.  The format becomes screwed up.

Anyway, here is my commit, hopefully it will help:

https://github.com/thomas83/angular-ui/commit/0cbfb373f09dcea633e8b78f212e72db7ed5133e

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-date

Please reopen this issue there if it is still relevant.
