### ISSUE TITLE
Remaining Repos

### ISSUE THREAD

**Issue by joshkurz** [angular-ui/angular-ui-OLDREPO#522]
The calendar has been moved, tested, tagged, and registered on bower.

Now we need to do the same with the rest of the 6 or 7 remaining repos. Is everyone ok with the structure that the calendar is using?

If so then we go ahead and move the rest of the directives over to their respected repos.

**Comment by ProLoser** [comment]
Alright I'll see if i can take care of some myself. Can you help relocate all the open PRs and issues to the calendar repo? I also recommend that you start pushing releases of uiCalendar independently.

**Comment by joshkurz** [comment]
Already started the relocation of the PR's and the one open issue which was
angular-ui/angular-ui#469https://github.com/angular-ui/angular-ui/issues/469
.

  I also recommend that you start pushing releases of uiCalendar
independently.
You mean fork on my own branch and merge PR's instead of writing commits
directly to the repo?

**Comment by ProLoser** [comment]
No I mean don't worry about AngularUI releases. uiCalendar will have it's
own independent versioning and releases, so you don't have to feel blocked.
I'm just reiterating what you probably already know just in case you feel
like you had to wait for the next version of the AngularUI repo or
something.

On Sat, Mar 30, 2013 at 5:44 PM, Josh Kurz notifications@github.com wrote:

> Already started the relocation of the PR's and the one open issue which was
> angular-ui/angular-ui#469<
> https://github.com/angular-ui/angular-ui/issues/469>
> .
> 
> I also recommend that you start pushing releases of uiCalendar
> independently.
> You mean fork on my own branch and merge PR's instead of writing commits
> directly to the repo?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/522#issuecomment-15684628
> .

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by joshkurz** [comment]
oh ok. Yeah no holding back anymore. Now we are going to go all out with
#TDD.

On Sat, Mar 30, 2013 at 8:49 PM, Dean Sofer notifications@github.comwrote:

> No I mean don't worry about AngularUI releases. uiCalendar will have it's
> own independent versioning and releases, so you don't have to feel
> blocked.
> I'm just reiterating what you probably already know just in case you feel
> like you had to wait for the next version of the AngularUI repo or
> something.
> 
> On Sat, Mar 30, 2013 at 5:44 PM, Josh Kurz notifications@github.com
> wrote:
> 
> > Already started the relocation of the PR's and the one open issue which
> > was
> > angular-ui/angular-ui#469<
> > https://github.com/angular-ui/angular-ui/issues/469>
> > .
> > 
> > I also recommend that you start pushing releases of uiCalendar
> > independently.
> > You mean fork on my own branch and merge PR's instead of writing commits
> > directly to the repo?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/angular-ui/angular-ui/issues/522#issuecomment-15684628>
> > 
> > .
> 
> ## 
> 
> Dean J Sofer
> DeanSofer@gmail.com
> 
> BS Computer Information Systems
> California State Polytechnic University, Pomona
> Telephone: 714-900-2254
> Website: www.DeanSofer.com
> Github: github.com/ProLoser
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/522#issuecomment-15684672
> .

## 

_Josh Kurz_
www.atlantacarlocksmith.com  http://www.atlantacarlocksmith.com

**Comment by ProLoser** [comment]
I've done the basic moves although a lot of work still remains. One part I still don't even know how to tackle is the doc generation.
