### ISSUE TITLE
Latest version not published on NuGet

### ISSUE THREAD

**Issue by adebisi-fa** [angular-ui/angular-ui-OLDREPO#523]
Hello,

[v0.3.3](https://github.com/angular-ui/angular-ui/tree/v0.3.3) and [0.4.0](https://github.com/angular-ui/angular-ui/tree/v0.4.0) have not been published to NuGet. Any idea of when that's going to happen?

Thank you for this great work.

**Comment by ProLoser** [comment]
Not sure how to publish to Nuget. As such, this repo is being discontinued. You'll have to reopen the issue on any relevant sibling repo under the Angular-UI org
