### ISSUE TITLE
bindMapEvents called on undefined object

### ISSUE THREAD

**Issue by sburt413** [angular-ui/angular-ui-OLDREPO#525]
I'm using the ui-map directive and populating it with a set of markers in scope via ng-repeat as per the example on the Angular UI homepage.  When removing markers from myMarkers, I'm getting a browser error from google maps code stating a variable is undefined.

A quick glance over things shows that there is a watch on uiMapMarker, which calls bindMapEvents on the changed object.  In this case, the object being watched was removed, so the new object is undefined.  This watch should have protections put in for null and undefined objects thrown to it.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-map (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-map

Please reopen this issue there if it is still relevant.
