### ISSUE TITLE
select2 event $scope data   not refreshed

### ISSUE THREAD

**Issue by payallmoney** [angular-ui/angular-ui-OLDREPO#526]
<input  ng-model="test"ui-select2="{formatSearching:testSearching}"/>
$scope.testSearching= function(){}
when $scope.testSearching  function excute , the $scope is not the newest data  but the initial state

using : select2 3.3.2 anglur ui v0.4.0

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-select2 (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-select2

Please reopen this issue there if it is still relevant.
