### ISSUE TITLE
assignning ng-model via cellTemplate in ngGrid

### ISSUE THREAD

**Issue by chenyang** [angular-ui/angular-ui-OLDREPO#527]
Hi I'm a beginner in AngularJS and ng-grid. I have a problem in assigning model value when I try to use self-defined column definition.

Here is a sample piece of code:
columnDefs:[{ field: "name", displayName:"Name", cellTemplate:''}];

What I want is : without double clicking the cell, (no enableCellEdit), when change the content of the input, the cell's raw data will change, have the same effect as editing the cell manually.

Does anyone got some idea? Great thanks in advance!!

**Comment by ProLoser** [comment]
@chenyang can you open this on https://github.com/angular-ui/ng-grid

**Comment by chenyang** [comment]
Hi @ProLoser thanks for your answer, I think I got the answer by assigning the cellTemplate like this  
<input ng-model="row.entity.the_colname"> will work
