### ISSUE TITLE
Tab resizing on Firefox has different behavior than Chrome

### ISSUE THREAD

**Issue by keenedge** [angular-ui/angular-ui-OLDREPO#529]
Firefox 20.0
Chrome Version 26.0.1410.43 m

Here is the plunk.  http://plnkr.co/edit/Dplqfn?p=preview

On Chrome it behaves exactly as desired. All the auto re-sizing is correct.
![chome](https://f.cloud.github.com/assets/531085/348431/e1c641b2-9f53-11e2-826b-a8e6b4f2c19c.PNG)

But on Firefox you can see it is very different
![tab problems](https://f.cloud.github.com/assets/531085/348427/b4095250-9f53-11e2-8985-7deaa3a36f6e.PNG)

Problems On Firefox:

Problem 1: Tab Content area does not grow to the width of Buttons
- Select "Problem Tab" on the left side tabs and "Tab 1" on the top tabs.
- The Tab Content area does not grow so a scroll bar is shown.  

Problem 2: Tabs wrap onto two lines
- Select "Problem Tab" on the left side tabs and "Tab 2" on the top tabs.
- Again, the content area is not large enough so the tabs are wrapped and stacked instead of staying on one line. 

I've tried to look into it but I'm afraid the exact cause is beyond me.

**Comment by ProLoser** [comment]
How is this relevant to AngularUI?

**Comment by 0x-r4bbit** [comment]
This is CSS Fu. Not related to AngularUI at all.

**Comment by keenedge** [comment]
You are right.. i recreated the problem with bootstrap alone.  Sorry for jumping to conclusions.
