### ISSUE TITLE
ui-date, invalid isolate scope definition for directive uiDate

### ISSUE THREAD

**Issue by jkrajniak** [angular-ui/angular-ui-OLDREPO#53]
Hi,
I've tried to use ui-date directive (from the example) and what I have got is such error:

Error: Invalid isolate scope definition for directive uiDate: 
("","uiDate")@http://127.0.0.1:8000/media/app2/lib/angular/angular.js:4178
forEach([object Object],(function (definiton, scopeName) {"use strict";var match = definiton.match(LOCAL_REGEXP) || [], 

One way to solve this error is to remove scope from ui-date directive.

**Comment by ProLoser** [comment]
It's this happening in the latest version?

**Comment by ProLoser** [comment]
@MrTheodor any chance you can test this with the latest version? uiDate no longer directly references the scope object for models, as they are now passed as attribute expressions. Would like to close this issue.

**Comment by jkrajniak** [comment]
Ok, it works with latest version of Angular, thanks!
