### ISSUE TITLE
ui-sortable not updating model when dragging down / seriously bugged

### ISSUE THREAD

**Issue by smajl** [angular-ui/angular-ui-OLDREPO#530]
Hi, ui-sortable directive is broken hard. E.g. on demo page try dragging/sorting top level or children level elements from top to down - model doesn't update! Suprisingly, opposite direction works. This leads to some serious UI quirks.

This is critical bug!

**Comment by smajl** [comment]
I have found out where the problem is! I was using the complete build:
https://github.com/angular-ui/angular-ui/blob/master/build/angular-ui.js

In this file on lines 1134-1135:

``` javascript
              if (start < end)
                end--;
```

I don't know who wrote this complete nonsense there, but as I have found out while debugging, these lines totally broke ui-sortable directive! So I deleted them and it works flawlessly.

OK, so I digged around the site and found out, that is the same as: https://github.com/angular-ui/angular-ui/issues/460 and it is already fixed in stand-alone directive file!

So the main problem is, that the build doesn't have the updates included. Why the duck is that?!? :( So much waisted time..

**Comment by vizo** [comment]
I get gray hair too :) Please update build .. and thanks @smajl!

**Comment by ericschwarz** [comment]
I'm also looking to get this fix which, while in the master, is not in the latest version 0.4.0.  I'm using bower (i.e. bower install angular-ui) which pulls using a version tag.  Any chance of getting a new version which includes this fix?

**Comment by honzajde** [comment]
+1 for fixing this issue properly

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-sortable (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-sortable

Please reopen this issue there if it is still relevant.
