### ISSUE TITLE
select2 is never marked valid

### ISSUE THREAD

**Issue by Coneko** [angular-ui/angular-ui-OLDREPO#531]
http://plnkr.co/edit/foEUd1

It's correctly marked as `ng-invalid` and `ng-invalid-required`, but when you choose an option the classes aren't updated. Note that if you inspect the `select` element which select2 hides, that one's classes are updated correctly.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-select2 (after confirming it's still necessary with the latest code)?

**Comment by Coneko** [comment]
Ok, I'll check later, thanks.
