### ISSUE TITLE
ReferenceError:  is not defined

### ISSUE THREAD

**Issue by ghholt** [angular-ui/angular-ui-OLDREPO#532]
Hi Angular-UI, 

I've got my angular_ui build recognized on my site but cannot get any of the angular-ui directives to work. I've been testing with CodeMirror and it keeps giving me a "ReferenceError: CodeMirror is not defined"

Here is the order in which I am adding my js files: 

https://github.com/ghholt/portfolio/blob/master/app/index.html

How can I get the angular-ui directives to run. 
![Screen Shot 2013-04-08 at 5 23 54 PM](https://f.cloud.github.com/assets/1932772/354030/a9e95ea6-a092-11e2-934d-e505710d871c.png)

**Comment by glebm** [comment]
Looks like you don't have CodeMirror included. You can get it [here](http://codemirror.net/)

**Comment by ghholt** [comment]
Hi glebm, 

Thanks for the help. It should be include in the angular_ui.js and angular_ui.css files but just isn't registering that it is there. I could add from codemirror as you noted but it's a larger problem with all the angular ui components for me. Check it out http://angular-ui.github.io/.

**Comment by ProLoser** [comment]
AngularUI should not have third party code included. It is your responsibility to resolve the external dependencies yourself, however, our transition to leveraging twitter/bower may alleviate this process for you.

Step 3 of the **Getting Started** block state:

> Optional Include any jQuery(UI) plugins you wish to use (plugins are not bundled with AngularUI)
