### ISSUE TITLE
Sortable directive folder has a "REDME" file in it :P

### ISSUE THREAD

**Issue by boxed** [angular-ui/angular-ui-OLDREPO#534]

**Comment by ProLoser** [comment]
That's because you should have finished reading it already.

**Comment by ProLoser** [comment]
You mind relocating this to https://github.com/angular-ui/ui-sortable

**Comment by boxed** [comment]
Why? It's correct in that repo.

**Comment by ProLoser** [comment]
oh lol

**Comment by boxed** [comment]
Why is the issue closed when it's still broken? You know you can just rename it from within github by clicking edit when viewing the file right? Super fast and simple.

**Comment by ProLoser** [comment]
Because we are discontinuing development on the angular-ui repo. You said that it's correct in the ui-sortable repo. I am just still sorting out the details of the restructure.

**Comment by boxed** [comment]
Aha, cool.
