### ISSUE TITLE
ui-map does not work for IE8

### ISSUE THREAD

**Issue by llozano** [angular-ui/angular-ui-OLDREPO#535]
Even including the ie-shim js ui-map does not load the map. Any workarounds or whatever?

Help!

**Comment by llozano** [comment]
@ajoslin , someone pointed me on this direction. Do you have any advise of how to get around this problem?

**Comment by ajoslin** [comment]
I'm not sure .. and I don't have access to IE8 either.  Can you create a plunker of what you're doing?

**Comment by llozano** [comment]
I could. But if you go to the angular ui page using IE8 the map won't load up. Also, I noticed something weird when I add ng-click to the marker. When ng-click is called the action executes as many markers were opened before. So if you click 10 markers and finally you do ng-click the function associated to ng-click is called 11 times in this example.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-map (after confirming it's still necessary with the latest code)?

**Comment by nateabele** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-map

Please reopen this issue there if it is still relevant.
