### ISSUE TITLE
Creating a proper Mac / Windows shortcuts map

### ISSUE THREAD

**Issue by arnaudbreton** [angular-ui/angular-ui-OLDREPO#536]
Hi,

I'm trying to add shortcuts in my app, using the ui-keypress directive.
I want to build a proper shortcuts map according to the OS standard.

My app is a text editor, so I'll have to bind classic action like save (ctrl / cmd + s), etc.

Seems like the directive is handling the cmd key (meta?) only halfway. It handles it with the "altPressed" condition but not in the "altRequired" condition.

Any idea on how to achieve this in a proper way?

Thanks.

**Comment by arnaudbreton** [comment]
Keep cool man! I thought I had given enough information to make it understandable.
Just published a Plunkr to make it more clear for you: http://plnkr.co/edit/EwB8pO

For an unknown reason, ui-keypress doesn't want to work in Plunkr, works in my real app.
Now I need to figure out how to handle Mac "cmd" key.

I actually managed to do it by modifying the code, as you can see in the "angular-ui-keypress-modified.js" file in the plunkr. It works but don't know if it will on all browsers / platforms.
My update is based on the jQuery.hotkeys plugin, available here: https://github.com/tzuryby/jquery.hotkeys/blob/master/jquery.hotkeys.js

Thanks for your help.

**Comment by ProLoser** [comment]
Can you relocate this to /ui-utils?

Also, you should open a PR with your patch instead of the plunker so we can merge in your fix.

**Comment by arnaudbreton** [comment]
What's the difference between angular-ui / ui-utils PLEASE?

Yes I could do that but I would like to have your opinion on my solution before doing it.

Thanks.

**Comment by ProLoser** [comment]
AngularUI is being broken apart into smaller projects to make maintenance and development easier and faster. ui-utils contains all modules that do not have external dependencies.

If you opened a Pull Request it would be much easier for me to review the diff and comment on the changes inline.

**Comment by arnaudbreton** [comment]
Ok, I'm just finishing implementation on my side and I'll do that next, once everything is clean
