### ISSUE TITLE
Modals and Dialog don't disappear when the back button is pressed.

### ISSUE THREAD

**Issue by jamasters** [angular-ui/angular-ui-OLDREPO#538]
I have run into an issue with Modals and Dialogs when a browsers back button is pressed while a modal and glassis visible. (in a multi page app).

The application changes the view and controller while the modal stays activated and visible. As the controller has been swapped out from underneath the modal, strange things start happening.

How do we get around this issue? Is there a way to make sure the modal / dialog is dismissed when the back button is dismissed or the route is changed.

**Comment by ProLoser** [comment]
1: create a plunker or demo so we can see your code
2: Is this intended for angular-ui/bootstrap?

**Comment by pkozlowski-opensource** [comment]
@jamasters I've created https://github.com/angular-ui/bootstrap/issues/335 in the https://github.com/angular-ui/bootstrap based on this one.

**Comment by FindBoat** [comment]
I'm not sure if this has been solved, but you can refer to my solution [here](http://www.sgzhaohang.com/blog/2014/11/28/angularjs-hack-browser-back-button-to-dismiss-modal/).
