### ISSUE TITLE
ui-sortable update event fires before scope variable is updated

### ISSUE THREAD

**Issue by coli** [angular-ui/angular-ui-OLDREPO#539]
The update event is useful to handle changes to the corresponding ng-model variable. But it fires before the variable is changed! 

The variable is changed after the "stop" event, but that one fires even if nothing has changed.

**Comment by ghost** [comment]
We encountered something similar to what you're describing.  Essentially we had an "ordinal" field on our records.  The records were being returned NOT ordered by "ordinal" and instead had orderBy:'Ordinal' in the ng-repeat.  This meant that the scope variable was in one order, the view was in another order, and when we did the drag-and-drop reorder it ended up moving the element at the same _position_, but not the same _element_.  Once we returned the data from the server in the proper "Ordinal" order and removed the orderBy, then everything worked.  Perhaps this should noted in the documentation?

**Comment by coli** [comment]
I think update event should be fired after the scope variable is updated :)

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-sortable (after confirming it's still necessary with the latest code)?
