### ISSUE TITLE
setAttribute and setDraggables error

### ISSUE THREAD

**Issue by DavidRogersDev** [angular-ui/angular-ui-OLDREPO#542]
When prototyping the ng-grid in my ASP.NET MVC environment, it works fine.

But in a CakePhp environment, I get this error at the js console:

TypeError: Object 3 has no method 'setAttribute'
    at l.setDraggables (http://localhost/js/ng-grid.min.js:1:16266)
    at Object.n [as forEach](http://localhost/js/angular.min.js:6:494)
    at l.setDraggables (http://localhost/js/ng-grid.min.js:1:16242)
    at <error: illegal access>
    at e (http://localhost/js/angular.min.js:30:369)
    at http://localhost/js/angular.min.js:33:480 

I've kept my code very simple:

```
myUsersModule.controller('UsersController', function($scope, $http, $timeout) { 

    $http.get('http://localhost/users/getUsersJson').success(function(data) {
        $scope.people = data;
  });        


    $scope.gridOptions = { 
            data : 'people',                
            columnDefs: [
                { field: 'User.id', displayName: 'Id' },
                { field: 'User.username', displayName: 'Name'},
                { field: 'User.email', displayName: 'Email'}
            ]
        };

})
```

Data is being returned is fine and the View is simply:

```
<div ng-app="usersModule">
    <div ng-controller="UsersController">

        <div ng-grid="gridOptions" style="height: 500px;"></div>

    </div>
</div>
```

**Comment by ProLoser** [comment]
Please relocate this issue to the proper location: https://github.com/angular-ui/ng-grid
