### ISSUE TITLE
select2 doesn't get initialized correctly when using nested ng-repeat with optgroup

### ISSUE THREAD

**Issue by tadchristiansen** [angular-ui/angular-ui-OLDREPO#545]
I posted the following issue stackoverflow (contains a jsfiddle that shows the issue):

http://stackoverflow.com/questions/16123704/how-to-get-select2-tags-initializing-correctly-with-angular-ui-when-option-group

I have tried digging in to angular-ui to see if I can find what keeps it from getting initialized but the code looks correct:

if (isSelect) {
     elm.select2('val', controller.$modelValue);
}

controller.$modelValue is set correctly so it seems like its some kind of refresh issue.

**Comment by ulius** [comment]
I have this same issue while using ng-repeat on a plain option (not optgroup) tag.

**Comment by tadchristiansen** [comment]
That should work fine, create a jsfiddle and I will take a look at it.

**Comment by ulius** [comment]
After trying a bunch of stackoverflow/github suggestions, I removed angular select2 and still had the same issue. What am I doing wrong here?: http://jsfiddle.net/ulius/YDbuc/

**Comment by ProLoser** [comment]
This repo is discontinued. The project has been relocated here: https://github.com/angular-ui/ui-select2

Please reopen this issue there if it is still relevant.
