### ISSUE TITLE
SelectDateWidget (feature request)

### ISSUE THREAD

**Issue by rtpm** [angular-ui/angular-ui-OLDREPO#548]
This is a feature request that I'd love to see in angular-ui.

It would be great, if there was a simple "select date widget" built on f 3 selects side by side (first one with years), second with months 01-12 and the third 1-28/31.

That would work on any platform (especially mobile) I suppose and would not require any external libraries.

Something like SelectDateWidget() in Django framework:
https://github.com/django/django/blob/master/django/forms/extras/widgets.py

 Will try to code and share to community myself.. but won't get that done soon as I am not an advanced angularjs & javascript coder.

Thanks

**Comment by rtpm** [comment]
Just saw there's a jquery similar plugin @ https://github.com/NickABusey/jQuery-Date-Select-Boxes-Plugin

**Comment by ProLoser** [comment]
You can do this with vanilla selects or use `ui-jq` for the plugin you linked to.
