### ISSUE TITLE
"Create a Build" doesn't work in Firefox

### ISSUE THREAD

**Issue by moehnen** [angular-ui/angular-ui-OLDREPO#550]
the Modal/Select2-Box **"Create a Build"** on http://angular-ui.github.io/ doesn't work in Firefox.
Shows always "no matches found".

Tested on Mac&Windows
Chrome is OK.

**Comment by ProLoser** [comment]
Yeah... we're undergoing a project restructure so this will continue to be broken until we explicitly bring it back. At this time, that's not going to be a critical concern, but if you're interested in helping us out with this let me know!
