### ISSUE TITLE
ui-if changes order of rendered items

### ISSUE THREAD

**Issue by montlebalm** [angular-ui/angular-ui-OLDREPO#551]
I have a situation where some items in a collection are dependent on a "ui-if" condition to render. The problem is that, when they render, they appear below the items without an "if" condition.

```
<tab>
    <pane ui-if="someCondition"></pane>
    <pane></pane>
</tab>
```

Here's how it actually gets rendered:

```
<div class="tab">
    <div class="pane"></div>
    <div class="pane" ui-if="someCondition"></div>
</div>
```

I realize this is probably because the directive needs to watch the attr, so it takes longer to process. However, I wonder if the directive append logic could be changed so that we could preserve the order of html elements.

**Comment by montlebalm** [comment]
Btw, I've tried putting both `ui-if="true"` and `ui-if="someCondition || !someCondition"` on the panes that should always show, but neither seem to work reliably.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-utils (after confirming it's still necessary with the latest code)?
