### ISSUE TITLE
Undocumented jQuery dependency for uiMap

### ISSUE THREAD

**Issue by solidspark** [angular-ui/angular-ui-OLDREPO#552]
GoogleMaps event listeners, e.g. map-idle, map-click, inside of ui-event require jQuery for event binding. jQuery is listed as "optional" in the documentation.

**Comment by vpixle** [comment]
Yeah, this is definitely one of the most ugliest bug I ever traced. uiMap struggles to survive just on jQuery.lite that is part of the Angular so there is no Error in your console. You owe me two day of my live guys ;)

**Comment by dmitryevseev** [comment]
+1 absolutely. Made a hard way chasing it down.
It comes down to `uiEvent` directive that requires jQuery.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-map (after confirming it's still necessary with the latest code)?

Also, we are transitioning to leverage bower and have more thoroughly refactored ui-event (which is now part of ui-utils) to remove the jQuery dependency completely. Dependencies are managed by bower for you in the component.json (soon to be bower.json)

**Comment by dmitryevseev** [comment]
Solved by https://github.com/angular-ui/ui-map/commit/410951b960babcc2c6ab90ff78ce235eab90833a
Can be closed
