### ISSUE TITLE
ui-date does not close in IE 10 after date is selected

### ISSUE THREAD

**Issue by Jonas82** [angular-ui/angular-ui-OLDREPO#553]
When selecting a date the datepicker does not close in IE 10.
This can be verified in the plnkr:
http://plnkr.co/edit/VeutZ0?p=preview

Works in chrome. I do unfortunately not have IE8 or 9 available to test.

Jonas

**Comment by AkosLukacs** [comment]
It's present in IE8 too, and visible on the official example page too: http://angular-ui.github.io/#directives-date

**Comment by keithharvey** [comment]
+1 in IE8

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-date (after confirming it's still necessary with the latest code)?
