### ISSUE TITLE
Global Trace Addition

### ISSUE THREAD

**Issue by wbyoko** [angular-ui/angular-ui-OLDREPO#555]
hopefully something similar to 

```
 window['angularUi'] = '0.4.0'; // Current Version Number or Anything truthy
```

could be added to the source, so you can check for existence after cdn call with the pattern

```
<!-- Angular-UI 0.4.0 -->
<script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui/0.4.0/angular-ui.min.js"></script>
<script>window.angularUi || document.write('<script src="js/angular-ui.min.js"><\/script>')</script>
```

Is there some other way to check for the existence of Angular-UI?

Thanks.

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure and is being broken up into multiple parts. What you're asking for, although sensible before, would be like expecting every single plugin to declare a global variable. If you have a suggestion on how to do this a bit more reasonably across all projects please feel free to suggest it.
