### ISSUE TITLE
Cannot load CDN from fiddle.tinymce.com in demo

### ISSUE THREAD

**Issue by anhtran** [angular-ui/angular-ui-OLDREPO#558]
I go to ping the url. The result from ping.eu: 

--- PING fiddle.tinymce.com (168.62.48.183) 56(84) bytes of data. ---
--- fiddle.tinymce.com ping statistics ---
packets transmitted     9
received    0
packet loss     100 %
time    8062 ms

**Comment by ProLoser** [comment]
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-tinymce (after confirming it's still necessary with the latest code)?

**Comment by wesleycho** [comment]
I recommend trying the updated repository for the ui-tinymce plugin that @ProLoser linked, and if it is still an issue, file one there.
