### ISSUE TITLE
Maps support infobubble

### ISSUE THREAD

**Issue by Dashue** [angular-ui/angular-ui-OLDREPO#559]
Since google maps infowindow has a very limited set of customizations infobubble was created. https://code.google.com/p/google-maps-utility-library-v3/wiki/Libraries

Would be awesome if support for this was added.

I would love to contribute, a bit of a beginner when it comes angular and js so would need a some pointers

Edit.
Added this to the maps project, please remove this.

**Comment by ProLoser** [comment]
This project has been relocated to https://github.com/angular-ui/ui-map please reopen this issue there.
