### ISSUE TITLE
Unit tests not seeming to work

### ISSUE THREAD

**Issue by dandoyon** [angular-ui/angular-ui-OLDREPO#56]
@petebacondarwin  I pulled down latest, saw the new jake stuff. I tried running tests, no errors but then no tests ran either. 

debug: Execution (fired by autoWatch)
debug: All browsers are ready, executing
debug (web server): serving: /opt/local/lib/node_modules/testacular/static/context.html

Chrome 19.0: Executed 0 of 0 SUCCESS (0.073 / 0 secs)

**Comment by petebacondarwin** [comment]
Yes there are problems. Taking a look on Monday if you don't first

Pete
...from my mobile.
On Jul 14, 2012 5:54 AM, "dandoyon" <
reply@reply.github.com>
wrote:

**Comment by ajoslin** [comment]
It should be fixed now.
