### ISSUE TITLE
ui-tree

### ISSUE THREAD

**Issue by tamtakoe** [angular-ui/angular-ui-OLDREPO#560]
Make, please, module for tree-structures (catalog, menu, list). F.e. http://jsfiddle.net/brendanowen/uXbn6/8/
http://jsfiddle.net/uXbn6/296/

**Comment by ProLoser** [comment]
Your solution seems to be perfectly adequate, why do you need a new
directive?

**Comment by tamtakoe** [comment]
Because it is widespread case.
- Menu. Even there is tree menu in official angular site: top-menu, and left-menus, especially in API reference.
- Catalog. More products catalogs are trees. More they are collapse-trees. It is good if ui-tree will combined with your ui-collapse.
- List. Structure of articles etc. in admin panels is tree, often is sortable tree.

Now I need collapse-tree menu for site like this demo: http://tamtakoe.ru/annaverdi. You can click "sign in" → "Войти" (without password) and see admin panel and play with menu settings (first link up to menu — sorting with jQ ui-sortable, second — making new items). It is very difficult case, but I don't now how make it in Angular.

**Comment by ProLoser** [comment]
Again, I don't understand why you need a directive to do this when you can simply use `ng-repeat`

**Comment by tamtakoe** [comment]
I put two links in first message. It is absolutely not simple for use. It means individual html-file for item template (comparative with ng-repeat, which use item template from main page).
