### ISSUE TITLE
ui-sortable spotty when dragging in horizontal list

### ISSUE THREAD

**Issue by mb21** [angular-ui/angular-ui-OLDREPO#561]
When in a horizontal list (like here: http://jsfiddle.net/hKYWr/582/) the items don't reshuffle to make space for the one dragging – when you drag it perfectly horizontally. As soon as you make some vertical movements it works, but sometimes you have to try quite a lot.

This seems to work in jQuery-UI: http://jsfiddle.net/UAcC7/427/

**Comment by ProLoser** [comment]
This plugin has been relocated to https://github.com/angular-ui/ui-sortable
