### ISSUE TITLE
Is somewhere datepicker directive example for form input?

### ISSUE THREAD

**Issue by lichtner** [angular-ui/angular-ui-OLDREPO#563]
In documentation is example of datepicker but haven't seen datepicker directive for form input. Is somewhere a example how to use it in form? Thanks.

**Comment by lpaulger** [comment]
http://angular-ui.github.io/bootstrap/#/datepicker (I think you have to navigate via the navbar to datepicker; hashbang navigation isnt working)

**Comment by ProLoser** [comment]
If you want the jquery-ui version, check this repo out: https://github.com/angular-ui/ui-date if you want the bootstrap version checkout https://github.com/angular-ui/bootstrap
