### ISSUE TITLE
modal window doesn't work in 2.3.2

### ISSUE THREAD

**Issue by danielzzz** [angular-ui/angular-ui-OLDREPO#565]
hi, I have the same problem with angular (angular, angular-mobile) 1.1.5 and bootstrap 2.3.2 as described in this issue: https://github.com/angular-ui/angular-ui/issues/327

I have checked the solutions proposed there, but they did not work for me.
I am getting the modal fade, but no dialog...
what else could cause the problem?

moreover, this plunk from an example given there is no longer working:
http://plnkr.co/edit/a0kIUDEpkOofGkAG6xid?p=preview

thanks, dan

**Comment by ProLoser** [comment]
This repo is discontinued. You may want to checkout angular-ui/bootstrap instead

**Comment by danielzzz** [comment]
thanks!
