### ISSUE TITLE
ngForm inside a Carousel Slide in UI Bootstrap not working

### ISSUE THREAD

**Issue by ebeltran1981** [angular-ui/angular-ui-OLDREPO#567]
I  am using the a Carousel for its effect of sliding, but I want to insert a form per slide, After inserting the ngForm, the $scope does not have the instance of that ngForm. If I place the ngForm outside of the Carousel, then the instance appear in the $scope. Example:

data:carousel
    <data:slide active="slides[0].active">
        <form name="formGI" data-ng-submit="SaveAndNext(cosvr.company)" novalidate>
            <div class="row-fluid text-center topSmallPad">
                <div class="span12">
                </div>
            </div>
        </form>
    /data:slide
/data:carousel
the code above is not working, the $scope should have an instance: $scope.formGI. but, If place the form outside the Carousel like this:

<form name="formGI" data-ng-submit="SaveAndNext(cosvr.company)" novalidate>
    <data:carousel>
        <data:slide active="slides[0].active">
            <div class="row-fluid text-center topSmallPad">
                <div class="span12">
                </div>
            </div>
        </data:slide>
    </data:carousel>
</form>

Works correctly... any ideas?

http://stackoverflow.com/questions/18218602/ngform-inside-a-carousel-slide-in-ui-bootstrap-not-working

**Comment by ProLoser** [comment]
You should move this to angular-ui/bootstrap
