### ISSUE TITLE
bs-timpicker directive 

### ISSUE THREAD

**Issue by jianhaozh** [angular-ui/angular-ui-OLDREPO#570]
here is the  scenario：i use this directive to provide a time input,after i load the data from server, this directive sets the input elem an "ng-dirty" class and also the form elem will also has the same css class, but i want them have a "ng-pristine" class that told me this data has not modified ,so i modified some source code at the bs-timpicker directive part:

angular.module('$strap.directives').directive('bsTimepicker', [
  '$timeout',
  '$strapConfig',
  function ($timeout, $strapConfig) {
    var TIME_REGEXP = '((?:(?:[0-1][0-9])|(?:[2][0-3])|(?:[0-9])):(?:[0-5][0-9])(?::[0-5][0-9])?(?:\s?(?:am|AM|pm|PM))?)';
    return {
      restrict: 'A',
      require: '?ngModel',
      link: function postLink(scope, element, attrs, controller) {
        if (controller) {
          element.on('changeTime.timepicker', function (ev) {
            $timeout(function () {
          // add the if clause to check the value from model and from the elem
              if(element.val() != controller.$viewValue){
                controller.$setViewValue(element.val());
             }
            });
          });
          var timeRegExp = new RegExp('^' + TIME_REGEXP + '$', ['i']);
          controller.$parsers.unshift(function (viewValue) {
            if (!viewValue || timeRegExp.test(viewValue)) {
              controller.$setValidity('time', true);
              return viewValue;
            } else {
              controller.$setValidity('time', false);
              return;
            }
          });
        }
        element.attr('data-toggle', 'timepicker');
        element.parent().addClass('bootstrap-timepicker');
        element.timepicker($strapConfig.timepicker || {});
        var timepicker = element.data('timepicker');
        var component = element.siblings('[data-toggle="timepicker"]');
        if (component.length) {
          component.on('click', $.proxy(timepicker.showWidget, timepicker));
        }
      }
    };
  }
]);

**Comment by nateabele** [comment]
This repository has been discontinued, and broken up into other repositories within this organization. Please reopen the issue against the appropriate repo.
