### ISSUE TITLE
uiScrollfix causes memory leaks due to no window unbinding

### ISSUE THREAD

**Issue by btiernay** [angular-ui/angular-ui-OLDREPO#572]
From https://github.com/angular-ui/angular-ui/blob/master/modules/directives/scrollfix/scrollfix.js:

``` javascript
angular.element($window).on('scroll.ui-scrollfix', function () {
 ... elm ...
}
```

The previous code closes over the reference to `elm` and adds a global handler to `window`. This should be unbound when the scope is destroyed to prevent memory leaks.

**Comment by ProLoser** [comment]
This project is discontinued.

https://github.com/angular-ui/ui-utils/tree/master/modules/scrollfix

**Comment by btiernay** [comment]
@ProLoser thanks. Looks like this is still a problem in that script as well. I will open a new ticket.
