### ISSUE TITLE
Directive for Jcrop Image Cropping Plugin

### ISSUE THREAD

**Issue by uniwalk** [angular-ui/angular-ui-OLDREPO#574]
There is a jquery image cropping plugin - https://github.com/tapmodo/Jcrop

Someone points that Jquery passthrough option does not provide sufficient integrationi (http://www.verious.com/qa/image-crop-with-angular-js/)

Would the Angular-ui Team create a custom one for us; or is there a complete and working directive on the web?

**Comment by lukemadera** [comment]
Hi @heapwalker I'm in the same situation - I searched the bower components and couldn't find one (though I am trying to stay away from any jQuery dependency) so I decided to a build a standalone directive that I should have done by the weekend (potentially even today/tomorrow). It's lightweight so likely won't have (at least not yet) all the features of JCrop (which I too have used in the past) but should get the job done. If you're interested, I can let you know when it's published.

**Comment by uniwalk** [comment]
Hi @lukemadera I am still in the searching for this fantastic (but-missing) directive on the web. Yet haven't got any clue of a possible new born tool... Really appreciate your hard work :). May I know are you going to publish your on your github too?

**Comment by lukemadera** [comment]
Hi @heapwalker - here's a version I built: https://github.com/jackrabbitsgroup/angular-image-upload

The demo requires a backend and unfortunately (AFAIK) that's not supported on Github pages but if you included it in your app and use the demo code, it should work and support crop - I'm using it on one of my sites/projects right now! Any questions or feedback just open issues for the directive / let me know!

**Comment by semiomant** [comment]
I tried a few ways to make jcrop and angluar work together, nothing worked. So I decided to isolate them from each other by iframe. And yay, jcrop worked again. The main problem then becomes hiding the cut-out from the user by css.
