### ISSUE TITLE
Closing this repo

### ISSUE THREAD

**Issue by nateabele** [angular-ui/angular-ui-OLDREPO#577]
This repo has been discontinued for months now, yet people still seem to occasionally be opening issues against it. I think it's time to tank it for good. /cc @ProLoser

**Comment by ProLoser** [comment]
You think we should delete it?

**Comment by nateabele** [comment]
It's too bad you can't archive it, but yeah, I think we should.

**Comment by ProLoser** [comment]
My concern (despite the stupidity) is that there are still resources and code references that until they are properly implemented I kind of don't want to lose (such as the pull request for ui-input)

**Comment by ProLoser** [comment]
So we need to remove the star and fork buttons.

**Comment by nateabele** [comment]
> the pull request for ui-input

Why not just pull it down and throw it in the angular-ui/ui-input repo?

**Comment by nateabele** [comment]
Let me know if you need help with the git-fu for that.

**Comment by ProLoser** [comment]
@nateabele uh yeah perhaps you could if you find time to do so. Off the top of my head i'm not sure of how to do this easily.

**Comment by nateabele** [comment]
Cool, I'll try and take care of it in the next week or so.

**Comment by nateabele** [comment]
@ProLoser To be clear, are you talking about #191?
