### ISSUE TITLE
Validation Suite

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#6]
Coming from the tail-end of this discussion: https://groups.google.com/forum/?fromgroups#!topic/angular-ui/OCKRx3n-kpI
Example http://jsfiddle.net/xPSzE/1/ (coupled with a datepicker)

It would be nice if we could provide a set of commonly-used validation rules, or perhaps make the work involved with adding new rules easier (possibly?).

I think validation should be decoupled from visual widgets (such as a date validation from a datepicker) so that you are not forced to pass configuration options every time you call ui-date.

Thoughts?

**Comment by joseym** [comment]
Seems like this sparked uiValidate. Close?
