### ISSUE TITLE
Add npm dependencies for Jake & Testacular?

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#60]
I was just thinking, why not add jake and testacular to the npm dependencies? I mean we're already using npm for building anyway, might as well just use it for all of angular-ui's dependencies anyways. I realize some/most/all might be expected to have some of these tools installed globally, however I don't really see a big reason to have someone enter:

```
npm install
sudo npm install -g testacular
sudo npm install -g jake
```

When you can just do `npm install`

**Comment by petebacondarwin** [comment]
I am not sure you can add --global dependencies in the package.json.  Both
of these are command line tools that need to be installed with -g.
Pete

On 15 July 2012 13:57, Dean Sofer <
reply@reply.github.com

**Comment by ProLoser** [comment]
I realize you can't add global dependencies, but I'm saying I don't think
these _have_ to be global. You could be right about the fact that they are
CLI

On Mon, Jul 16, 2012 at 2:09 AM, Pete Bacon Darwin <
reply@reply.github.com

**Comment by petebacondarwin** [comment]
OK, so if you add them locally then I believe you have to add their
binaries to the path manually which defeats the point of including them in
the package.json.
A simple
npm -g install jake testacular
seems reasonable, if you are going to develop on angular-ui.  Of course
people who are just going to use the library don't need any of this.
Pete

On 16 July 2012 10:13, Dean Sofer <
reply@reply.github.com

**Comment by ProLoser** [comment]
Alright closing this then as invalid
