### ISSUE TITLE
Changes to Prettify filter

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#61]
So I actually thought this was for the Prettifier javascript lib. I think we should rename it to prevent confusion.

In CakePHP, there is a lib called "Inflector" that contains methods such as `Inflector.underscore()`, `Inflector.variable()` and `Inflector.humanize()`.

I think we should rename the filter to either **humanize** if that's the only thing it will do, OR go the CakePHP route and name it `inflector` with the intention of supporting more/future inflections as options. It could of course humanize by default.

So it would be like: `{{ item.columnName | inflector:'humanize' }}`

Pinging @blackbarn for his thoughts and @petebacondarwin since he merged this in.

@blackbarn, if you agree perhaps you might be willing to make this change?

**Comment by ProLoser** [comment]
It would also be nice to have an additional demo for this filter.

**Comment by pkozlowski-opensource** [comment]
+1 for renaming it to either `inflector` or `humanize` : I was also confusing this one with the Prettifier javascript lib (btw: would find a directive for the Prettifier lib handy).

**Comment by ProLoser** [comment]
If you can test out using prettifier lib on passthrough that would help. If
it works we can use it on the demo page.

On Sat, Jul 21, 2012 at 12:45 PM, Pawel Kozlowski <
reply@reply.github.com

**Comment by boneskull** [comment]
I wonder if it would be possible to move this code out of master until it's feature-complete and the tests pass?  Just a thought.
