### ISSUE TITLE
CodeMirror throws an error if model isn't initialized

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#62]
CodeMirror apparently does not take kindly to falsey non-string values (NaN, undefined, etc).

I tried the following fix:

```
ngModel.$render = function() {
  if (ngModel.$viewValue) {
    codemirror.setValue(ngModel.$viewValue);
  } else {
    codemirror.setValue('');
  }
};
```

However this actually causes another `$apply()` to fire since the model value is changed from `undefined` to `''` (empty string).

**Comment by boneskull** [comment]
I have a fix for this that I'll submit later today.
