### ISSUE TITLE
Testing: Watching files or forcing 'jake'?

### ISSUE THREAD

**Issue by ajoslin** [angular-ui/angular-ui-OLDREPO#67]
So on the testing, there are two possible approaches to building the test/test-config.js file:
1. We can make the testacular server watch source files for changes and re-test on each change.
2. We can make the testacular server watch the compiled build files for changes and re-test on each change.

Isn't it easier to make it watch the source files for changes, instead of having people re-run jake each time they want to test again?

The version of test-config currently on master forces people to re-build with `jake` to test.  We should settle on one approach though, I think we've switched between these two approaches three or four times now.

**Comment by petebacondarwin** [comment]
I guess it is fine to change the config to load up each of the source files
in turn rather than loading up the compiled file.  Slightly
problematically, if you change a .coffee file then you still have to build
the .js file to trigger the test run.  This can be automated, though, by
running coffee -cw ... to watch and compile automatically.
Pete

On 17 July 2012 19:24, Andy Joslin <
reply@reply.github.com

**Comment by ajoslin** [comment]
Ah, that makes sense.  I didn't think about the problem of coffee.

We could also make a seperate 'jake watch-test' task or something which will start the test server, and watch the modules/ directory for changes to re-build everything.  Then we could have auto-watch and compiled files being tested.

The `wr` npm module is really good at this: `wr "jake" dir1 dir2 dir3` will watch the dir list and run jake whenever one of the dirs' files changes.

**Comment by petebacondarwin** [comment]
Sounds good.

On 17 July 2012 20:09, Andy Joslin <
reply@reply.github.com

**Comment by ProLoser** [comment]
My vote is for watching source files. We should have another task/config that runs all the tests on the built version though to ensure consistency.

**Comment by dandoyon** [comment]
Sounds good to me, what needs to happen to run jake, i get a message about unable to find module async?
is that angular-ui or a missing npm install?

**Comment by petebacondarwin** [comment]
Have you run npm install?

Pete
...from my mobile.
On Jul 18, 2012 1:32 AM, "dandoyon" <
reply@reply.github.com>
wrote:

**Comment by dandoyon** [comment]
yeah, i think i may need updated node or npm module

**Comment by dandoyon** [comment]
So, not to muddy the waters, Igor suggested we use something called grunt, https://github.com/cowboy/grunt, angular has rake (but that is legacy), they are using grunt. Food for thought

**Comment by ProLoser** [comment]
Grunt is quite heavily used by jQuery as their new build process and I've
mentioned it a few times. However I don't want to void the work Pete has
done to get Jake up and running. I can take a look as soon as I have an
opportunity on setting up Grunt since it was something I had considered
doing anyway.

At this time, I believe there are still a few build tasks that jake is not
doing that the makefile is, so I have actually been using the makefile.

On Wed, Jul 18, 2012 at 11:29 AM, dandoyon <
reply@reply.github.com

**Comment by petebacondarwin** [comment]
I'll take a look at this and see if it is easy to migrate to from Jakefile.
 One thing to note is that I have actually factored out a lot of the work
from the Jakefile into files in the jake folder to prevent the Jakefile
from becoming massive and unmaintainable.

On 18 July 2012 19:29, dandoyon <
reply@reply.github.com

**Comment by ProLoser** [comment]
Pete: I actually noticed that myself. It seemed unusual that the amount of
work to accomplish this build process in jake was so high, when we had so
few lines of code in our makefile. I'm hoping maybe we can see a reduction
in file size if we go with grunt? The massive files also make it difficult
for me to understand what's going on overall.

On Wed, Jul 18, 2012 at 12:44 PM, Pete Bacon Darwin <
reply@reply.github.com

**Comment by petebacondarwin** [comment]
Hi Dean
The Jakefile now does everything the makefile does and more (i.e. jake
test-server) so feel free to use it.
The problem with the makefile is that it relies upon command line
utilities, such as cat, cp, uglifyjs, lessc, coffee.  I have basically
recreated these in javascript using the relevant npm modules.  It was
slightly frustrating that jake didn't come with these (or that 3rd parties
had not provided them) but I think if you look at each of the files in the
jake folder they are fairly small and self explanatory.  Take concat.coffee
for example:

fs = require('fs')
util = require('./util')

### File concatenation helper

concatenateFiles = (files, target)->
  files = util.ensureFileList(files)
  jake.logger.log 'Updating ' + target
  filesContent = files.toArray().map (file)->
    fs.readFileSync(file, util.FILE_ENCODING)
  fs.writeFileSync(target, filesContent.join(util.EOL), util.FILE_ENCODING)

module.exports = concatenateFiles

It basically uses straight nodejs to load up all the files and save them to
a single file.

I like the fact that grunt seems to have a number of these basic tasks
already built in and it also seems to have a well defined API for creating
your own tasks, which jake is not so good for.

I will see if I can knock out a grunt file tomorrow.  I expect that it
should be fairly straightforward.

Pete

On 18 July 2012 20:51, Dean Sofer <
reply@reply.github.com

**Comment by dandoyon** [comment]
I figured out problem with jake, for some reason not finding async in global node_modules folder. had to symlink to it from inside angular-ui

**Comment by petebacondarwin** [comment]
Or just install it locally?

On 19 July 2012 05:17, dandoyon <
reply@reply.github.com

**Comment by ajoslin** [comment]
This issue is fixed in the grunt build version, grunt is awesome =)
