### ISSUE TITLE
LICENSE file is missing

### ISSUE THREAD

**Issue by bradleydwyer** [angular-ui/angular-ui-OLDREPO#69]
What is the license of this project?

**Comment by ProLoser** [comment]
We were actually [just discussing this today](https://groups.google.com/forum/?fromgroups#!topic/angular-ui/b1LyRgtpuPI). I think I'll go ahead and throw up the MIT license as that looks to be what we'll be going with unless someone else says differently @petebacondarwin & @ajoslin ? It appears to be what AngularJS is using.

**Comment by petebacondarwin** [comment]
OK with me.

**Comment by ajoslin** [comment]
Sure.

**Comment by ProLoser** [comment]
Aw, was hoping the word 'fix' and '#69' in the same commit message would have closed the issue.

**Comment by bradleydwyer** [comment]
Nice commit message :)

**Comment by jeveloper** [comment]
funny :)

**Comment by wesalvaro** [comment]
Except it's not. Very unprofessional.
