### ISSUE TITLE
Simplify the README

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui-OLDREPO#72]
Most modern web frameworks and tools are going the super minimalist approach of having 3 big sentences, 2 lines of terminal, and a shiny huge button for you to click and that's about it.

We could probably reduce the word-count of the readme fairly easily (especially considering the upcoming changes to jake).

The main thing however is that we need to put our  coding standards on the page (so people don't commit their built files anymore). Perhaps now would be the time to decide if we break up the README into a github wiki or use the github pages repo?

**Comment by petebacondarwin** [comment]
Either is fine by me.  Probably easiest to have github wiki pages (oriented
toward contributors to the project) and keep the
angular-ui.github.comoriented toward users of the library.
Pete

On 18 July 2012 10:49, Dean Sofer <
reply@reply.github.com
