### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by ajoslin** [angular-ui/angular-ui-OLDREPO#79]
We've just added codemirror directive and a few other things. Let's update the package.json version name (decide on an initial version, maybe 1.0.1), run grunt, and commit the new build files?

**Comment by ProLoser** [comment]
![](https://scentsofself.files.wordpress.com/2012/02/make-it-so.jpg)

**Comment by ajoslin** [comment]
Can you do it and tell us how you updated the git version tag and all that fanciness

**Comment by ProLoser** [comment]
Sure. Are we going with v1.0.1? My only reservation is that v1 would imply we are stable, and I don't know if we can make those sort of promises (since the API may still be very volatile in some directives). For instance I know that I was hoping to break keypress into 3 directives asap, i could even do that today.

I think it would be nice to get that refactor in before a major release, it seemed sort of core.

**Comment by petebacondarwin** [comment]
How about 0.2.0?  By the way there are a few issue with grunt on Windows.
 Mainly around running command line utilities like coffee.  I have fixed
the coffee issue by using the grunt-coffee npm module but this has a
problem with compiling coffee files into the same folder as the source.  I
have submitted a pull request to the owner of this npm module with a fix.
In the meantime now is as good a time as any to consider if coffee files
should be compiled somewhere other than next to the source file.  This
would also help with getting git to ignore them.  Perhaps to a compiled
folder?
Pete

On 20 July 2012 18:25, Andy Joslin <
reply@reply.github.com

**Comment by ajoslin** [comment]
How about a coffee folder in each module, optional?  It compiles to the src folder in that module.

**Comment by petebacondarwin** [comment]
Not sure if that would really help.  I would say, either a central place or
leave them as they are.  At least where they are now it is easy to flick
between the two if needs be.

On 20 July 2012 19:25, Andy Joslin <
reply@reply.github.com
