### ISSUE TITLE
CodeMirror demo

### ISSUE THREAD

**Issue by boneskull** [angular-ui/angular-ui-OLDREPO#80]
There is no demo of the CodeMirror directive on the site.  Should probably add one.

**Comment by ProLoser** [comment]
There is a demo.

**Comment by ProLoser** [comment]
It just broke (apparently) and I forgot to add it to the navigation bar. Perhaps you can add it to the nav. I think when I push the new build the codemirror should be fixed.

**Comment by boneskull** [comment]
Ah, alrighty, totally missed it, sorry.  But yeah it's not working atm.

**Comment by ProLoser** [comment]
Go ahead and add a link to the nav bar. When we push the new version of angular-ui today it SHOULD fix codemirror.

**Comment by ProLoser** [comment]
Also, these bugs can go on angular-ui.github.com repo.

**Comment by boneskull** [comment]
OK, I'll create an issue there.
