### ISSUE TITLE
Problems with grunt and testacular

### ISSUE THREAD

**Issue by dandoyon** [angular-ui/angular-ui-OLDREPO#86]
Having issues. Testacular is not seeing updates.

I did have problems doing npm install -g testacular ( see bottom, but even so it is running and I had already installed)

I did grunt server, loaded up http://localhost:8080 in browsers

grunt does not seem to know about testacular

Running "watch" task
Waiting...^Cbash-3.2$ grunt watch
path.existsSync is now called `fs.existsSync`.
Running "watch" task
Waiting...OK

> > File "modules/directives/currency/test/currencySpec.js" changed.

Running "coffee:build" (coffee) task

Running "concat:basic" (concat) task
File "build/angular-ui.js" created.

Running "test" task
<WARN> Make sure the testacular server is online: run `grunt server`.
Also make sure you have a browser open to http://localhost:8080/.
 Use --force to continue. </WARN>

Running "watch" task

Waiting..

sudo npm install -g testacular

npm ERR! TypeError: options.uid should be a number
npm ERR!     at ChildProcess.spawn (child_process.js:777:24)
npm ERR!     at Object.exports.spawn (child_process.js:614:9)
npm ERR!     at spawn (/opt/local/lib/node_modules/npm/lib/utils/exec.js:103:22)
npm ERR!     at exec (/opt/local/lib/node_modules/npm/lib/utils/exec.js:40:12)
npm ERR!     at /opt/local/lib/node_modules/npm/lib/utils/lifecycle.js:146:5
npm ERR!     at process.startup.processNextTick.process._tickCallback (node.js:244:9)
npm ERR! You may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/opt/local/bin/npm" "install" "-g" "testacular"
npm ERR! cwd /Applications/MAMP/htdocs/angular-ui
npm ERR! node -v v0.8.2
npm ERR! npm -v 1.1.16
npm ERR! message options.uid should be a number
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Applications/MAMP/htdocs/angular-ui/npm-debug.log

**Comment by ajoslin** [comment]
Are you on windows?  Pete is trying to fix windows issues for testacular on his own fork right now

@pkozlowski-opensource, you said you got it working on windows, though.

**Comment by dandoyon** [comment]
no mac

**Comment by dandoyon** [comment]
so, i had a branch based on old master and that still works. 

.debug (web server): serving: /Applications/MAMP/htdocs/angular-ui/templates/test/templateSpec.js
.
Chrome 22.0: Executed 1 of 68 (skipped 67) SUCCESS (0.752 / 0.018 secs)
Safari 5.1: Executed 1 of 68 (skipped 67) SUCCESS (0.652 / 0.014 secs)
TOTAL: 2 SUCCESS

**Comment by ajoslin** [comment]
The following steps work for me on Mac OSX:
1. `npm install -g testacular grunt coffee-script`
2. `npm install`
3. New terminal tab - > `grunt server`
4. Open localhost:8080 in browser
5. New terminal tab -> `grunt`
6. All tests run 

Do those work for you?

**Comment by petebacondarwin** [comment]
Have a look at test-config.js. I remember seeing someone changed it to not
watch for changes

Pete
...from my mobile.
On Jul 21, 2012 11:10 PM, "dandoyon" <
reply@reply.github.com>
wrote:

**Comment by pkozlowski-opensource** [comment]
@ajoslin, I kind of got it working on win, the only remaining problem is that testacular doesn't handle path wildcards correctly. So I can run individual tests adding them to the test-config.js but can't run the whole test suite using the default config... I believe that I'm bumping into the same issues as @petebacondarwin reported in https://github.com/vojtajina/testacular/issues/11.

**Comment by dandoyon** [comment]
Pete zeroed in on the problem. autowatch was turned off https://github.com/angular-ui/angular-ui/commit/6021c37301e751a56e3ab799736cf0ba3d468725 I pinged Andy for understanding. Anyone have any issues with it turned on?

**Comment by ajoslin** [comment]
The auto watch is supposed to be off now, because grunt watch takes care of that now ( it rebuilds coffee, rebuilds angular-ui.js, and tests on changes )

You can run grunt watch now to watch for changes

**Comment by dandoyon** [comment]
nope, not working for me. I have grunt server and grunt watch.  I'll use testacular watching for now.

**Comment by dandoyon** [comment]
Reopening until we can establish if this is just a problem on my end.

**Comment by petebacondarwin** [comment]
I suspect the problem is that the testacular server has to either sit and
watch the files or it has to be restarted on every build.  I imagine that
the current grunt only re-runs the testacular-runner on changes, which mean
that we still need to have a testacular server running and watching for
file changes.

On 22 July 2012 19:09, dandoyon <
reply@reply.github.com

**Comment by ajoslin** [comment]
Grunt watch and grunt server do fine for me, though... interesting..

**Comment by dandoyon** [comment]
windows or mac?

**Comment by ajoslin** [comment]
Mac

**Comment by boneskull** [comment]
Both work fine for me on Mac.

**Comment by dandoyon** [comment]
something must be wack on my end. hopefully npm guy gets back to my issue. I'll close this for now.
