### ISSUE TITLE
Fix the unique filter

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular-ui/angular-ui-OLDREPO#87]
The unique filter is currently broken and needs to be fixed. On top of this it doesn't have unit tests so those should be added as well.

**Comment by petebacondarwin** [comment]
Oops I was thinking of the unique directive

Pete
...from my mobile.
On Jul 22, 2012 3:28 PM, "Pawel Kozlowski" <
reply@reply.github.com>
wrote:

**Comment by pkozlowski-opensource** [comment]
Fixed in #111.
