### ISSUE TITLE
create test for tinymce directive

### ISSUE THREAD

**Issue by boneskull** [angular-ui/angular-ui-OLDREPO#93]

**Comment by boneskull** [comment]
Assigning to ProLoser so he'll get pinged -- was curious, when the model updates is the tinymce editor supposed to update too?

**Comment by ProLoser** [comment]
I think I forgot to implement that lol. I haven't tested it.

On Sun, Aug 5, 2012 at 11:14 AM, Christopher Hiller <
reply@reply.github.com

> wrote:
> 
> Assigning to ProLoser so he'll get pinged -- was curious, when the model
> updates is the tinymce editor supposed to update too?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/angular-ui/angular-ui/issues/93#issuecomment-7511803

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser
